### ISSUE TITLE
Make bootstrap mode optional

### ISSUE THREAD

**Issue by kstewart** [heptio/contour#1]
Contour is currently deployed as a daemonset on each node with the bootstrap configuration provided by Contour in a shared Volume Mount. The configuration is written via an init container, which is Contour with the `-initconfig` flag.

There is no fixed requirement for this to be requirement when deploying Contour, this information could be provided by a ConfigMap, or perhaps a PV, noting that hot reloading of configuration via the filesystem is not the recommended use case for Contour.

This issue exists mainly for documentation of the use of `-initconfig` and the options for providing it in other ways.

**Comment by davecheney** [comment]
I'm going to mark this complete, as of 0.4 we have the ability to elide the requirement to co-host envoy and contour which clears the way for other mechanisms of generating the bootstrap configuration.
