### ISSUE TITLE
Issue with Contour after upgrading Kubernetes to 1.8.4

### ISSUE THREAD

**Issue by cdelpinogeo** [heptio/contour#100]
Hello,

We recently were trying out contour on our 1.7.7 k8s dev cluster. We needed to upgrade the cluster to 1.8.4 in order to resolve a bug. The cluster itself was deployed using kops, so it was upgraded using this tool. The upgrade went fine, but noticed that the contour deployment was trying to run on a node that no longer existed:

`node 'ip-172-20-95-73.ec2.internal' not found`

I deleted the deployment, service, namespace, service account, cluster role, and cluster role binding. Tried redeploying, and I still keep getting the same error. Any thoughts on how to resolve this? I was using the following to deploy contour:

`kubectl apply -f https://j.hept.io/contour-deployment-rbac`

Please let me know if you require further info. TIA!

**Comment by timothysc** [comment]
@cdelpinogeo Do you have the exact error you're seeing?

**Comment by davecheney** [comment]
Hi @cdelpinogeo 

Thanks for raising this issue. I hope I don't sound like I'm passing the buck but this smells like a kubernetes bug. I say this because there's nothing special about contour, it's just a regular old deployment.

I'd try 
```
kubectl delete -f https://j.hept.io/contour-deployment-rbac
```
Then 
```
kubectl get ns -w
```
and wait for the `heptio-contour` namespace to disappear then 
```
kubectl create -f https://j.hept.io/contour-deployment-rbac
```
If that doesn't seem to fix the problem, can you please paste the output of
```
kubectl get nodes
```
Thanks

Dave

**Comment by cdelpinogeo** [comment]
@timothysc, I've attached a screenshot of the error:

![screenshot from 2017-12-13 22-07-51](https://user-images.githubusercontent.com/8877760/33973719-4a330fb6-e052-11e7-82af-253edc1a5d0f.png)

There are no logged messages in the container:

![screenshot from 2017-12-13 22-10-17](https://user-images.githubusercontent.com/8877760/33973738-6c79201a-e052-11e7-8e8c-5f9a0208fcd0.png)

Thanks!

**Comment by cdelpinogeo** [comment]
@davecheney, thanks for following up. I've tried the steps you mentioned, but I get the same result. Here are the nodes:

    NAME                             STATUS    ROLES     AGE       VERSION
    ip-172-20-100-83.ec2.internal    Ready     node      6h        v1.8.4
    ip-172-20-117-169.ec2.internal   Ready     master    6h        v1.8.4
    ip-172-20-125-118.ec2.internal   Ready     node      6h        v1.8.4
    ip-172-20-43-164.ec2.internal    Ready     node      6h        v1.8.4
    ip-172-20-47-36.ec2.internal     Ready     node      6h        v1.8.4
    ip-172-20-50-158.ec2.internal    Ready     master    7h        v1.8.4
    ip-172-20-74-166.ec2.internal    Ready     node      6h        v1.8.4
    ip-172-20-85-161.ec2.internal    Ready     master    6h        v1.8.4
    ip-172-20-90-216.ec2.internal    Ready     node      6h        v1.8.4

Thanks again!

**Comment by davecheney** [comment]
@cdelpinogeo thanks for this information. Sadly I don't think I can assist you, that error is coming from the pod scheduler. Somehow you kubernetes thinks that node is still alive, even though it is not listed in `get nodes`.

**Comment by cdelpinogeo** [comment]
Thanks for looking into @davecheney. I decided to restart the masters, which fixed the issue. I'll raise this with the kops sig to see if this is an issue. Thanks!
