### ISSUE TITLE
Enable Lua filter

### ISSUE THREAD

**Issue by A-And** [heptio/contour#1015]
Currently contour deploys [three Envoy http filters](https://github.com/heptio/contour/blob/f727b2d72d676fd16e991e3461e3097c70f2655c/internal/envoy/listener.go#L89) to each configured listener. The list doesn't seem to be extensible or definable. Is deploying additional user-configured filters a supported feature?

 

If this feature isn't available is there prior art to accomplishing this? I'm specifically looking into adding Lua filters for each listeners.

**Comment by davecheney** [comment]
Thank you for your question. In general we prefer too choose reasonable defaults, or enable requested features without an option to turn them off. Making things configurable means we have to be able to support, both in slack, issues, and our commercial support offerings, people wanting to change those configurations. This has a cost for our support staff and a cost for the development team to handle escalations.

Specifically adding support for Lua means we would commit to helping people debug their Lua scripts embedded in Envoy. To not do so, to enable the feature but say we can't help you use it is not an option for us -- once we sell a support contract, our customers are not interested in nit picking over which features are supported or not.

So, the short answer is its unlikely that we'll add general Lua support to Contour. Can I turn the question around and ask you what is the problem you are trying to solve, perhaps there is a way to solve it without having to open the can of worms that is Lua embedded inside Envoy.

**Comment by pbarker** [comment]
So one option I would like to propose here @davecheney is that perhaps there is a core library/api that configures envoy using primitives of some sort, which then ingress/ingress-route utilize to fulfill their apis. This way you sort of get the best of both worlds, advanced users can configure however they like using the primitives, and simple use cases can leverage the basic apis. WDYT?

**Comment by davecheney** [comment]
@pbarker without knowing the problems the @A-And is facing I'm wary about proposing any solution. As I said above

> Can I turn the question around and ask you what is the problem you are trying to solve, perhaps there is a way to solve it without having to open the can of worms that is Lua embedded inside Envoy.

**Comment by davecheney** [comment]
@pbarker its unlikely we'll enable the lua filter in envoy because there is no way to make it safe to use in a multi tenant environment--its too easy to lock up the LUA event loop and block other traffic.

If you want to use envoy as a host for some lua routing logic you may be better served deploying envoy directly and using a static configuration (not Contour's dynamic configuration) to handle traffic for your application. If that sounds interesting we can work together on this out of band.

**Comment by davecheney** [comment]
The decision is we will not enable the lua filter in Contour deployed Envoys because it is reasonable to audit the lua code that someone may inject into Envoy via Contour making the Lua filter unsuitable for use in a multi tenant environment.
