### ISSUE TITLE
internal/contour: holdoff triggers forced update on first change

### ISSUE THREAD

**Issue by mattalberts** [heptio/contour#1020]
**What steps did you take and what happened:**
While gathering information requested by #499, I've observed `HoldoffNotifier` trigger a forced update on first `OnChange`.

**What did you expect to happen:**
Expect `OnChanges` to be compacted by `holdoffDelay` and `holdoffMaxDelay` (especially during start where many resources may exist).

**Environment:**
- Contour version: master
- Kubernetes version: 1.10.11

**Comment by davecheney** [comment]
I don’t think this is a big deal. We only save one update over the entire run of a contour process.

**Comment by mattalberts** [comment]
I agree. I thought about it over dinner; I don't like the change set for it (doesn't really matter and I don't like adding a frivolous conditional into such a hot function)
