### ISSUE TITLE
allow-http and force-ssl annotations have surprising/confusing combined behaviour

### ISSUE THREAD

**Issue by ceralena** [heptio/contour#1023]
I'm not convinced that this is a bug, but I think it's worth discussion.

**What steps did you take and what happened:**

_Step 1_

Initially, we had an `Ingress` created several months ago with the following annotation:

```
annotations:
  kubernetes.io/ingress.allow-http: "false"
```

Insecure HTTP endpoints were responding with 404:

```
HTTP/1.1 404 Not Found
date: Tue, 16 Apr 2019 05:16:24 GMT
server: envoy
content-length: 0
```

This seems correct, as [the docs](https://github.com/heptio/contour/blob/master/docs/annotations.md#standard-kubernetes-ingress-annotations) have this to say:

> Instructs Contour to not create an Envoy HTTP route for the virtual host. The Ingress exists only for HTTPS requests.

_Step 2_

We added the `force-ssl-redirect` annotation, as we wanted insecure HTTP requests to be redirected to secure endpoints.

```
annotations:
  kubernetes.io/ingress.allow-http: "false"
  ingress.kubernetes.io/force-ssl-redirect: "true"
```

Insecure endpoints still returned a 404, rather than an SSL redirect:

```
HTTP/1.1 404 Not Found
date: Tue, 16 Apr 2019 05:23:36 GMT
server: envoy
content-length: 0
```

This caused some confusion for us - especially as we had forgotten the `allow-http` annotation was set.

_Step 3_

We suspected that `allow-http` being present was getting in the way of `force-ssl-redirect` having the desired effect, so we removed it:

```
annotations:
  ingress.kubernetes.io/force-ssl-redirect: "true"
```

Now we get the redirect as desired:

```
HTTP/1.1 301 Moved Permanently
location: https://www.example.com/api/health_check
date: Tue, 16 Apr 2019 05:28:58 GMT
server: envoy
content-length: 0
```

**What did you expect to happen:**

I'm not entirely sure, but it was surprising.

These annotations are arguably simply incompatible, and in an ideal world I think it should not be possible to specify them both.  Semantically, it doesn't make sense to have both of them - they contradict each other. But in this case we're using a standard `Ingress` resource, not an `IngressRoute` so according to my (limited) understanding, it would not be trivial to implement validation of that in Contour at deploy- / apply-time. I do not feel comfortable suggesting run-time validation and failure, because then consumers of Contour would have to be closely watching the logs to identify mistakes.

Since both annotations are grouped under `Standard Kubernetes Ingress annotations` in the Contour docs, this pain point could potentially be documented in that section. If that's the way forward, I'm happy to draft some copy for the docs and a put up a PR.

Alternatively, Contour could just ensure that `force-ssl-redirect` always wins, so the `allow-http` annotation basically becomes a no-op when they're both specified. This would be the correct behaviour in all use cases that I can think of, but that may be naive.

**Anything else you would like to add:**

:)

**Environment:**

- Contour version: `v0.11.0`
- Kubernetes version: (use `kubectl version`): `v1.14.0`
- Kubernetes installer & version: `1.11.7-gke.6`
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): nodes are running CoreOS, Contour and Envoy are both running on the standard images from manifest included in the Contour release

**Comment by davecheney** [comment]
Thank you for raising this issue. I agree that `ingress.kubernetes.io/force-ssl-redirect: "true"` should take priority.

**Comment by ceralena** [comment]
I'm happy to take on a fix, in that case.

From a quick look, it seems that we could just add another condition to this `if` statement, and update the comment:

https://github.com/heptio/contour/blob/c9902f2ce61c83f590f791ff6d778c6b94f3acd0/internal/dag/builder.go#L582-L583

I'd probably want to then pull that into a new function like `shouldCreateHttpRoute`, which is basically:

```go
return httpAllowed(ing) || tlsRequired(ing)
```

**Comment by davecheney** [comment]
Hmm, i'm not sure that's right. The logic should be, I think,

|             | true              | false                 |
|-------------|-------------------|-----------------------|
| force-http  | redirect to https | present route on http |
| tls-upgrade | redirect to https | redirect to https     |

I think the place for the fix is inside the `prefixRoute` function. It decides whether the route is a redirect to https or not.

**Comment by davecheney** [comment]
See also https://github.com/heptio/contour/blob/master/internal/dag/builder_test.go#L4104 which might only be used to IngressRoute processing.

**Comment by ceralena** [comment]
Hmm.

So we're on the same page, the annotations are:

* `ingress.kubernetes.io/force-ssl-redirect`
* `kubernetes.io/ingress.allow-http`

This is the logic I'd propose:

allow-http | force-ssl-redirect | behaviour | is this the current behaviour?
-- | -- | -- | --
undefined | undefined | present route on `http` and `https` | yes
false | undefined | do not register `http` route | yes
undefined | true | redirect `http` to `https` | yes
false | true | redirect `http` to `https` | **no**

So, as I understand it, the only case we need to modify is where `allow-http == false`, and `force-ssl-redirect == true`. Is that correct?

**Comment by davecheney** [comment]
> the only case we need to modify is where allow-http == false, and force-ssl-redirect
== true. Is that correct?

Yes. I believe that is correct

**Comment by rohandvora** [comment]
Hey @ceralena. Are you working on this issue? If you want, I could pick it up :)

**Comment by ceralena** [comment]
Hi @rohandvora ,

Yep, I'm planning to push up a PR within the next week - we're keen to make a contribution. I'll sing out if I get stuck and can't deliver it, though.

**Comment by rohandvora** [comment]
Hi @ceralena. Thanks for letting us know! We appreciate the help :)
