### ISSUE TITLE
RetryPolicy.Codes is not required for 0.12

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1024]
https://github.com/heptio/contour/blame/master/apis/contour/v1beta1/ingressroute.go#L144

Is not required for 0.12. This could have been my fault when merging #1018. Please remove it, then we'll have the diff we can merge if customers request it. For 0.12 I want the retry codes to be hard coded to `50x`

**Comment by rohandvora** [comment]
If no one is working on this, I can take this up,

**Comment by davecheney** [comment]
All yours, please get it done before apr 25. Thank you.
