### ISSUE TITLE
LBStrategy has no effect in contour v0.11.0

### ISSUE THREAD

**Issue by randmonkey** [heptio/contour#1030]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
0. create a service with 2 endpoints in k8s.
1. create an `IngressRoute` resource and set the `strategy` field of its services to `RingHash`.
2. access the domain of `IngressRoute`, and the two endpoints(pods) are chosen randomly.
3. dump the configuration of envoy, `lb_policy` field is set correctly for the `cluster`, but no `hash_policy` is set in the corresponding  `RouteAction`. So that no hash can be computed and backends are chosen randomly, thus the `RingHash` strategy takes no effect.
Also, `Maglev` strategy takes no effect for the same reason
**What did you expect to happen:**
some `hash_policy` in envoy is set by default or by some field in `spec` of `IngressRoute` resource, so that the hash strategy can take effect. The `hash_policy` should support the policies supported in envoy

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v0.11.0
- Kubernetes version: (use `kubectl version`): v1.11.6
- Kubernetes installer & version: kubeadm v1.11
- Cloud provider or hardware configuration: bare metal, Intel Xeon CPU E5-2609
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04 LTS, kernel 4.4.0.116

**Comment by davecheney** [comment]
Thank you for raising this issue. This was an oversite when we originally added IngressRoute, we blindly added the enumeration of supported load balancing strategies without realising some of those have additional configuration.

Sadly at the moment we do not have a way to supply the required configuration for RingHash to Envoy. See #361 and #937 for a design in progress.

**Comment by randmonkey** [comment]
So, the solution is to mark this field to be deprecated and eventually remove it from spec after sticky session is implemented?

**Comment by davecheney** [comment]
@randmonkey yes, that is likely going to happen. Perhaps we can fix it in place, but the major problem with the sticky session design is _all_ load balancer properties are _per backend_ (k8s service) no per route. It was a mistake to put the load balancer properties on the route and we have to correct that mistake first.

**Comment by kidlj** [comment]
> @randmonkey yes, that is likely going to happen. Perhaps we can fix it in place, but the major problem with the sticky session design is _all_ load balancer properties are _per backend_ (k8s service) no per route. It was a mistake to put the load balancer properties on the route and we have to correct that mistake first.

Are you talking about @phylake's [sticky session design](https://github.com/heptio/contour/issues/361#issuecomment-455706826) here? 

If so, I don't think that design is a mistake. Since one IngressRoute.Route is a combination of match and k8s services, where match part corresponds to Envoy's Route and k8s service to Envoy Cluster, we can say that **IngressRoute is a combination of Envoy Route and Cluster**. In Envoy, HashPolicy is configured in Route and lb_strategy is configured in Cluster, this IngressRoute design does the same, it puts HashPoliy to the match level and lb_strategy to the service level.

**Comment by davecheney** [comment]
Thank you for this issue. I am going to remove support for `Maglev` and `Ring_hash` as values for `strategy` as they cannot be used correctly in their current form.
