### ISSUE TITLE
Implementation for TimeoutPolicy design missed idle_timeout

### ISSUE THREAD

**Issue by rata** [heptio/contour#1052]
This design doc: https://github.com/heptio/contour/blob/master/design/custom-request-timeout.md#timeoutpolicy-for-route---envoy has been implemented and the section linked discusses the idle timeout parameter, however is not implemented.

The `timeout` param is implemented, but not the `idle_timeout`. See, for example: https://github.com/heptio/contour/blob/master/apis/contour/v1beta1/ingressroute.go#L128-L132

Talking to @stevesloka on slack, he probably forgot about it, it seems :)

This was implemented in commit 9f54b93287c2aabd22b6071b726021854f989c3a

**Environment:**

- Contour version: master

**Comment by davecheney** [comment]
@rata thank you for raising this issue. Can you please give me some user stories to help me understand the use case for idle_timeout. My goal is 

a. understand why envoy's default is not suitable (it's probably infinity, but I still needs to be asked)
b. see if there is a reasonable default we can apply for all users.

**Comment by rata** [comment]
@davecheney I think this is a duplicate of https://github.com/heptio/contour/issues/944? AFAIK, we can continue there. Let me know if I should re-open this :)

**Comment by davecheney** [comment]
SGTM. Thank you. If you're passionate about it, feel free to open a new issue about timeouts between envoy and the backend services, route timeout.
