### ISSUE TITLE
Randomly 503 HTTP Status code over Envoy

### ISSUE THREAD

**Issue by vn-patriot** [heptio/contour#1116]
**What steps did you take and what happened:**

On my K8s cluster I am using Contour ingress, running DS-HostNet mode. 2 Contour pods running separated with 6 Envoy pods. My client side randomly got 503 HTTP status code response from Envoy ingress.
Tracing down I did realise the envoy pod cause to 503 issue is try sending traffic to the old service endpoints IP address. This IP address  already terminated after We redeployed the service multiple times

**What did you expect to happen:**

I wondering all Envoy pods have updated all service's endpoint IP pods particularly

**Anything else you would like to add:**
These steps to figure out which Envoy pods cause to 503 issues 

List all envoy pods
```
 kubectl get pod -n heptio-contour | grep envoy

envoy-7dmz5 1/1 Running 3 20h
envoy-cp6hv 1/1 Running 2 1d
envoy-d8zq8 1/1 Running 8 1d
envoy-l767t 1/1 Running 9 1d
envoy-t5722 1/1 Running 8 1d
envoy-vhtsw 1/1 Running 9 1d
```

All my envoy pods listen for both HTTP & HTTPS (8080 & 8443). So I try to hit directly the particular service through envoy proxy

```
# kubectl port-forward envoy-cp6hv 8443:8443Forwarding from 127.0.0.1:8443 -> 8443Forwarding from [::1]:8443 -> 8443
--
```
then 

```
 while true; do curl -I https://localhost:8443 --resolve a.b.c:8443:127.0.0.1 -H "Host: a.b.c"; done


HTTP/2 503
content-length: 57
content-type: text/plain
date: Fri, 05 Apr 2019 04:29:09 GMT
server: envoy

HTTP/2 503
content-length: 57
content-type: text/plain
date: Fri, 05 Apr 2019 04:29:10 GMT
server: envoy
```

I try to get the endpoints of service-a on kubernetes cluster 

```
k get endpoints name-of-service-a
NAME ENDPOINTS AGE
name-of-service-a **100.96.15.105:80,100.96.9.229:80** 16h
```
But the log on this envoy pod showing the traffic is routing to different IP address 

```
GET /login HTTP/1.1" 503 UF 0 70 1176 - "118.201.231.96" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "f86f5635-6a13-428c-908e-c81d3f2f8215" "a.b.c" "**100.96.16.14:80**
```

I checked one more time via _localhost:9001/cluster_
The information also return the same IP address 100.96.16.14 on this pod. There is no correct IP address for name-of-service-a has updated on this envoy. 

**Environment:**

- Contour version: v0.11.0 
- Kubernetes version: (use `kubectl version`): 1.11.8
- Kubernetes installer & version: 1.11.8
- Cloud provider or hardware configuration: AWS 
- OS (e.g. from `/etc/os-release`):  CoreOS stable (2079.3.0)
- CNI : Cilium 1.5.1 (Upgrade to latest version)

**Comment by davecheney** [comment]
Thank you for raising this issue. Would you be able to restate the problem you are having as I am having difficulty parsing your information. It's great -- I just can't find the problem statement in there. Thank you.

**Comment by vn-patriot** [comment]
My problem is : The envoy pod sending traffic to wrong IP address of our backend service pod
That IP address being used has been changed to different IP address after We re-deploy our backend service several times. 
It similar with [this issue](https://github.com/heptio/contour/issues/293) which is mentioned long time ago

**Comment by davecheney** [comment]
Thank you for explaining. The first thing I need to you do is upgrade to contour 0.12.1. Please let me know when you've done that and if the issue remains.

**Comment by vn-patriot** [comment]
Actually you have recommended me upgrading to 0.11.0  when I used 0.9.1 
Now 0.12.0 & 0.12.1 just released I have read all change logs and other relevant issues but not strongly believe that 0.12.* can fix this problem to be honest.

**Comment by davecheney** [comment]
I agree, but we're not going to backport any fix to 0.9, so you'll have to
upgrade to the next release when we make the fix.

**Comment by vn-patriot** [comment]
Thanks Dave. I just update the contour to latest version as you recommended again. 

```
contour-6d65bd68c-hg6ks	contour	gcr.io/heptio-images/contour:v0.12.1
contour-6d65bd68c-t7v95	contour	gcr.io/heptio-images/contour:v0.12.1
envoy-5gnx2	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
envoy-bltsw	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
envoy-cdnjf	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
envoy-dg4n9	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
envoy-gzm7n	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
envoy-plgwb	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
envoy-tn68z	envoy	envoyproxy/envoy-alpine:v1.9.1	gcr.io/heptio-images/contour:v0.12.1
```
Will let you know when issue still happening or not

**Comment by stevesloka** [comment]
@vn-patriot I'd also recommend upgrading to Envoy v1.10.0

**Comment by vn-patriot** [comment]
Ok let me try

**Comment by vn-patriot** [comment]
My issue still happening ... Should I merge Envoy & Contour running same pod ?

**Comment by davecheney** [comment]
@vn-patriot yes please. Please let me know if using something like `examples/deployment-grpc-v2` fixes the problem.

**Comment by stevesloka** [comment]
Hey @vn-patriot just wanted to follow up here, were you able to try the `deployment-grpc-v2` model?

**Comment by vn-patriot** [comment]
@stevesloka thanks for your dedication. We now still running in Contour (deployment) & Envoy (daemon set) split mode. But so far there is no 503 UF anymore. Only 503 UC which is happening on some heavy pod. So not sure why 503 UF gone. but I definitely will try to run `deployment-grpc-v2` in near future. 
Sorry for this late response.

**Comment by stevesloka** [comment]
Ok good to hear @vn-patriot! I'm going to close this, but please let us know if you have more questions/issues in the future. =)
