### ISSUE TITLE
contour.heptio-contour invalid fqdn

### ISSUE THREAD

**Issue by DavidLangworthy** [heptio/contour#1117]
**What steps did you take and what happened:**
Attempted to use contour for internal traffic by specifying an fqdn of contour.heptio-contour: {"fqdn":"contour.heptio-contour"}

This results in an error:
validation failure list:
spec.virtualhost.fqdn in body should match '^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-z0-9]{2,}$'

**What did you expect to happen:**
I expected this to pass because it is a valid name.

**Anything else you would like to add:**
I think the validation test is overly conservative and should allow a hyphen in the last element to allow this.  

I've worked around this by using the cluster IP, but this has to be set per deployment which is not too nice.  

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by stevesloka** [comment]
@DavidLangworthy those rules have been getting us into trouble (which is leading me to go build an admission controller to replace). You can drop those rules defined on the CRD if it blocks your deployment. 

Also, I'm curious about your implementation. How are you sending traffic to `contour.heptio-contour`? I'd expect some internal DNS entry to point to the envoy endpoint so you could configure the internal routes per host.

**Comment by DavidLangworthy** [comment]
I have two services say foo and bar as below.  Occasionally foo needs to call bar.  I could use bar's internal dns name, but this would not be load balanced, so I am sending it back through the router.  Adding my own DNS entry for the router is a good idea.  

`  routes:
    - match: /foo
      services:
        - name: foo
          port: 80
    - match: /bar
      services:
        - name: bar
          port: 80
`

Thank you

**Comment by youngnick** [comment]
Hi @DavidLangworthy, I'm going to make a fix to the deployment yamls to do this, but a workaround for now is to use the service's FQDN inside Kube: `contour.heptio-contour.svc.cluster.local` (assuming you haven't changed the cluster default name from `cluster.local`). That will pass the validation.

Once we do make changes, your CRD definitions will need updating, as that's where the validation is performed.

**Comment by DavidLangworthy** [comment]
Thank you.
