### ISSUE TITLE
Rename deployment/ to example/

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1118]
Internally we always talk about the deployment/ directory as examples. They are samples designed to give the reader a starting point. 

Externally I think this is not as clear and suggests that the deployment/ directory is _the_ way to deploy contour. Sadly, given the current tooling available in the k8s ecosystem I don’t think it is possible to provide — let alone *unit test* — vetted, bulletproof, yaml manifests. 

The short term solution to this I think is to rename deployments/ to examples/.

**Comment by stevesloka** [comment]
We'll also need to coordinate the jump shortcut links which point to the `/deployments` directory today (e.g. `https://j.hept.io/contour-deployment-rbac`).

**Comment by davecheney** [comment]
@rochacon you're go to file a second PR that removes `deployment/`
