### ISSUE TITLE
deployment: Envoy use Contour dns name for gRPC connection

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#1127]
**Describe the solution you'd like**
Updating #1122, in the split deployment model, Envoy utilizes the built-in service environment variables (https://github.com/heptio/contour/blob/master/deployment/ds-hostnet-split/03-envoy.yaml#L67 && https://github.com/heptio/contour/blob/master/deployment/ds-hostnet-split/03-envoy.yaml#L69).

If the deployment or daemonset is created before the service exists, then these variables won't exist. 

We should look to have Envoy use the internal dns name of `contour` instead of the env variable. Last time I attempted this I ran into Envoy issues resolving that name properly. 

Also, if we switch to this model, the port cannot be automatically determined. Users will need to keep those numbers in sync (just noting so we can document properly).

**Comment by davecheney** [comment]
@stevesloka thanks for looking at this. Do you want to tackle this for 0.13, or punt til 0.14? Could you have a think about the best time to tackle this and label/milestone accordingly. Thanks

**Comment by stevesloka** [comment]
@davecheney this can be a 0.14.0 issue, it's not a critical block at the moment, but we should address soon so it doesn't affect other users.

**Comment by davecheney** [comment]
Ok, let’s bump it to 0.14.

**Comment by youngnick** [comment]
Picking up this one to work on in tandem with #862
