### ISSUE TITLE
Contour deletes its ingress routes when etcd cluster is down.

### ISSUE THREAD

**Issue by hmorikaw** [heptio/contour#1128]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We are running Contour and Envoy in different pods, Contour runs as a Deployment and Envoy runs as a Daemonset. 
Also, Envoy is running utilizing host networking within the Daemonset.

The issue we are seeing is that some of the Envoy's won't be able to connect to gRPC(etcd) cluster whose cluster is down state. 
In case, if we update ingressroute then it's disable all existing Envoy's ingress active entries.
And Envoy configuration 'dynamic_active_clusters' is deleted.
```
// ingressroute file
$ cat ingress-test.yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: foo
  namespace: foobar
spec:
  virtualhost:
    fqdn: foobar.com
  routes:
    - match: /
      services:
        - name: service0
          port: 80
          healthCheck:
            path: /healthy
            intervalSeconds: 3
            timeoutSeconds: 1
            unhealthyThresholdCount: 3
            healthyThresholdCount: 5
          strategy: WeightedLeastRequest
+        - name: add_later_service1
+          port: 80
+          strategy: WeightedLeastRequest
+          healthCheck:
+            path: /healthy
+            intervalSeconds: 3
+            timeoutSeconds: 1
+            unhealthyThresholdCount: 3
+            healthyThresholdCount: 5

// envoy logs
// gRPC(etcd) cluster is down
[2019-05-27 06:35:18.959][000001][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 13,
[2019-05-27 06:35:18.959][000001][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 13,

// add `add_later_service1`
// envoy removes its route
[2019-05-27 06:35:18.988][000001][info][upstream] [source/server/lds_api.cc:72] lds: remove listener 'ingress_https'
[2019-05-27 06:35:18.988][000001][info][upstream] [source/server/lds_api.cc:72] lds: remove listener 'ingress_http'
[2019-05-27 06:35:19.192][000001][info][upstream] [source/common/upstream/cluster_manager_impl.cc:554] removing cluster foo/bar/80/buz
[2019-05-27 06:35:23.386][000001][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 13,
[2019-05-27 06:35:23.386][000001][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 13,

// envoy configuration 'dynamic_active_clusters' is deleted when etcd cluster was down
--- config_dump_bad2    2019-05-29 08:14:25.541271926 +0900
+++ config_dump_normal  2019-05-29 07:53:07.589444053 +0900
@@ -263,6 +263,78 @@
      },
      "last_updated": "2019-05-27T06:59:32.046Z"
     }
+   ],
+   "dynamic_active_clusters": [
+    {
+     "version_info": "0",
+     "cluster": {
+      "name": "foo/bar/80/baz",
+      "type": "EDS",
+      "eds_cluster_config": {
+       "eds_config": {
+        "api_config_source": {
+         "api_type": "GRPC",
+         "grpc_services": [
+          {
+           "envoy_grpc": {
+            "cluster_name": "contour"
+           }
+          }
+         ]
+        }
+       },
+       "service_name": "foo/bar/port-80"
+      },
+      "connect_timeout": "0.250s",
+      "lb_policy": "LEAST_REQUEST",
+      "health_checks": [
+       {
+        "timeout": "1s",
+        "interval": "3s",
+        "unhealthy_threshold": 3,
+        "healthy_threshold": 5,
+        "http_health_check": {
+         "host": "contour-envoy-healthcheck",
+         "path": "/healthy"
+        }
+       }
+      ],
+      "common_lb_config": {
+       "healthy_panic_threshold": {}
+      },
+      "alt_stat_name": "foo_bar_80",
+      "drain_connections_on_host_removal": true
+     },
+     "last_updated": "2019-05-28T02:06:50.452Z"
+    },
+    {
...
```

**What did you expect to happen:**
If etcd cluster was down, Envoy pods did not update its traffic rule.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Contour version: v0.11.0
Kubernetes version: (use kubectl version): 1.14.0
Kubernetes installer & version: 1.14.0
Cloud provider or hardware configuration: Xeon E5-2683v4 2.10GHz / 2CPU / 512GBMEM RAM / SATA SSD 240GB x 1 / 10G Base-T*2
OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
CNI : Calico v3.4

**Comment by davecheney** [comment]
Thank you for raising this issue. I think there are two issues here. I want to talk about the second issue, envoy removing the cluster when you edit the ingressroute. What may be happening is the ingressroute object is not valid after editing and so the configuration associated with it is being removed. Do you think this is what could be happening?

**Comment by hmorikaw** [comment]
I think this issue is caused by read-only mode on etcd cluster. 
While etcd cluster was read-only mode, we update ingressroute. 
And then, Envoy pods expect a valid etcd entry(ingressroute object) but there is no data.
So, Envoy pods removed the invalid ingressroute object.

**Comment by davecheney** [comment]
Thank you for replying. If there is a problem with the etcd cluster underlying your k8s cluster, pretty much all bets are off. You need to address that problem first to restore the invariants that kubernetes relies on.

**Comment by hmorikaw** [comment]
In this case, even if we notice that etcd cluster is down by failures or hypervisor problems, users may not notice that.
And we cannot stop Contour system soon after the etcd failure.
So, we should disable for users to update ingressroute while etcd cluster is down.

**Comment by davecheney** [comment]
Contour relies on the invariants guaranteed by the Kubernetes api. 

I’m sorry but asking contour to diagnose the state of the api server’s backing etcd is not something we will do.

**Comment by davecheney** [comment]
@hmorikaw did I understand the issue correctly? Is the etcd server you refer to the API server for your k8s cluster?

If so, as there is nothing that Contour can do when deployed on a misbehaving k8s cluster, I would like to close this issue. Please let me know what you think.

**Comment by hmorikaw** [comment]
I mean some codes delete envoy routes if etcd cluster is read-only mode.
Does contour have some codes running like this behavior?

**Comment by davecheney** [comment]
@hmorikaw thank you for your reply.

Before I can answer your question I need to know more about the role of this etcd server? Is this etcd server the etcd server that backs your k8s cluster?

**Comment by davecheney** [comment]
@hmorikaw hello, would you be able to answer my previous question about the role of the faulty etcd server. Thank you

**Comment by hmorikaw** [comment]
yes. This etcd cluster backs my k8s cluster's API server and k8s nodes.

**Comment by davecheney** [comment]
@hmorikaw thank you for clarifying.

In that case my answer is the same as https://github.com/heptio/contour/issues/1128#issuecomment-498117102. If the underlying API sever is not behaving correctly then there is nothing Contour can do.

**Comment by hmorikaw** [comment]
I see. Thank you for your reply. I'll expand etcd servers and close this issue.
