### ISSUE TITLE
bug: does cmd/contour have to call flag.Parse unconditionally

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#113]
```
ERROR: logging before flag.Parse: W1218 11:31:33.776933   73199 reflector.go:341] github.com/heptio/contour/internal/k8s/watcher.go:61: watch of *v1.Endpoints ended with: too old resource version: 8605078 (8606302)
```
cmd/contour uses kingpin, not flag, but I suspect the glog infection via client-go requires flag.Parse to be called unconditionally.

**Comment by willmadison** [comment]
I'll take a look at this. Is the glog implicit dependency confirmed or simply suspected at this moment?

**Comment by davecheney** [comment]
We get it for free with client-go.

**Comment by willmadison** [comment]
Kewl I'll investigate further. I'd like to add an appropriate test for this bug but it sounds like it's as simple as adding an innocuous call to flag.Parse() but I'll look into it

**Comment by davecheney** [comment]
I'm fine with not having a test for this, a sufficiently scarey comment in
cmd/contour/contour.go will do

// we need this because (long rant about how glog is terrible)
func init() {
    flag.Parse()
}

**Comment by willmadison** [comment]
Fair enough. PR coming in just a sec...
