### ISSUE TITLE
Update j.hept.io shortlinks

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1144]
Hi @jbeda 

Could you please update the following j.hept.io shortlinks to point to these new locations

- [ ] `https://j.hept.io/contour-kuard-example` -> `https://raw.githubusercontent.com/heptio/contour/master/examples/example-workload/kuard.yaml`
- [ ] `https://j.hept.io/contour-deployment-rbac` -> `https://raw.githubusercontent.com/heptio/contour/master/examples/render/deployment-rbac.yaml`

Please feel free to close this issue once complete.

Updates #1118

**Comment by jbeda** [comment]
Updated! Let me know if they aren't working.

**Comment by davecheney** [comment]
Looks good 👍 thanks @jbeda 

@rochacon You're go to finish #1118
