### ISSUE TITLE
internal/dag: spec.virtualhost.fqdn should reject values with a *

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1167]
Wildcards in the form of `*.something.com` are permitted by envoy but prohibited by the ingressroute and ingress spec. Well, the former is firm but the latter is undefined.

We need a test to assert that an ingress or ingressroute with a `*` in the fqdn field is rejected. In fact we should define the set of valid values for the fqdn field in contour. It's ok to also have that validation included in the crd validation, but as the latter can be modified or removed, we need to have the canonical check inside Contour.

ref: https://github.com/heptio/contour/pull/1156#discussion_r292139552

**Comment by odacremolbap** [comment]
Can I be assigned this one?

**Comment by davecheney** [comment]
Go for it. If the implementation turns out to be more than trivial, please [talk about your change](https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#before-you-submit-a-pull-request) in this issue before sending code. Thanks

**Comment by odacremolbap** [comment]
Thanks,

I was thinking on doing a very simple regexp at [dag.validIngressRoutes](https://github.com/heptio/contour/blob/master/internal/dag/builder.go#L336), looks fairly trivial.
Regarding CRD, it looks like the regexp already does the filtering.

I'll pseudo code and share before pushing the PR.

**Comment by davecheney** [comment]
no regex please, a simple strings.Contains will suffice.
