### ISSUE TITLE
examples: Update deployment/daemonset to apps/v1

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#1181]
**Describe the solution you'd like**
The examples that use DaemonSet and Deployment resources will no longer be served from extensions/v1beta in v1.16. The examples need to migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

// ref: Kubernetes v1.15 release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#kubernetes-v115-release-notes

**Comment by davecheney** [comment]
@stevesloka Thanks for catching this, I think we can live with this for 0.13. Can you please schedule this ticket for 0.14 or 0.15 as you see fit and perhaps add “help wanted”/“good first issue” labels if appropriate. 

Thanks

**Comment by odacremolbap** [comment]
I'll start working on this one if that's ok with you.
@stevesloka @davecheney

**Comment by davecheney** [comment]
Go for it!
