### ISSUE TITLE
docs: Contributing nits on Pulling and Building

### ISSUE THREAD

**Issue by odacremolbap** [heptio/contour#1191]
**Go command missing?**

Probably a typo at https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#fetch-the-source
```sh
go github.com/heptio/contour
```
I guess there should be a `get` in there

**Building**

- Default `make` target executes `install`, which will create put the binary in `$GOPATH/bin/contour` instead of  `current working directory`
- It would also be worth replacing `go build` with `go build ./cmd/contour/` when mentioning building.

https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#building

**Container**
Nothing wrong here, but I like having a bash file to source when working that will setup my local env. With contour, setting `REGISTRY` sounds like a handy way for pushing images:
```sh
REGISTRY=docker.io/pmercado make push
```

https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#build-an-image

(_Very opinionated_) I like finding something like a `localdev/` entry in `.gitignore` so I can `source local/my-env-file`, specially for complex setups.

**Comment by davecheney** [comment]
@youngnick would option have time to look at this this week?

**Comment by youngnick** [comment]
Yes, definitely.
