### ISSUE TITLE
Contour should move to a leader election model

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1204]
Currently each Contour pod watches the API server and produces its own copy of the dag which it passes to a listening Envoy.

Once #881 is completed we will be able to decoupled the lifecycle of Contour and Envoy. This will allow us in turn to point Envoy to the ClusterIP of the active Contour instance. By deploying several contours, but having only one active at a time.

Related:
- [ ] #1178 

Blocked:
- [x] #881 
- [ ] #1185

**Comment by stevesloka** [comment]
I think we have enough work done on #881 to unblock this issue.

**Comment by davecheney** [comment]
Moving to beta1 milestone.

**Comment by youngnick** [comment]
Here's a status update on this one (note that this feature requires a split deployment to work):

Implementing a version of leader election into `contour serve` is relatively straightforward. I have a rough version working already. Currently it will:
- use the `contour` ConfigMap to hold the leader election annotation (used for the distributed lock coordination by the standard client-go election library.
- have the 'serve gRPC' goroutine block until it becomes the leader
- if deposed as the leader, the instance of contour will shut itself down.

As far as `contour serve` goes,  this gives us the ability to have only a single manager contour running and serving gRPC, which will help with all the Envoys having a consistent view of the world.

To make this work properly, though, we need to change the Readiness probe for the deployment to check the availability of the gRPC port. This is easily done inside the Deployment spec, but means that the RollingUpdate of the deployment when you change it will never finish, as not all pods will become Ready. So, we either need to fudge the readiness probe for a short period when the pod starts up (not ideal) or move away from using a RollingUpdate for the Deployment (also not ideal). I will think about this more.

**Comment by youngnick** [comment]
After some thought and discussion with @davecheney, we've decided on this approach:
- Move the Contour Deployment to 'Recreate' for its update strategy. This will mean that on updates to the Deployment spec, Kube will delete and recreate the pods. Until #1280 is complete, this means that the risk of Contour doing a partial update to Envoy and removing listeners briefly is still present. We've decided to proceed as this is no change from the current state.
- Readiness will be attached to a TCP probe of the gRPC port. So, only one contour Pod (the leader) will be Ready at any one time.
- I will add a `--disable-leader-election` flag for the single-pod case, going by the principle of least surprise. Remember that the single-pod deployment case is moving to deprecated in 0.15 though.

**Comment by davecheney** [comment]
> I will add a --disable-leader-election flag for the single-pod case

Why do we have to disable leader election in this case? Wouldn't it be simpler to assume that leader election always happens, even if there is only a single nominee?

**Comment by youngnick** [comment]
> Why do we have to disable leader election in this case? Wouldn't it be simpler to assume that leader election always happens, even if there is only a single nominee?
If we do that, the single-pod installation will break - only one Contour will serve any config to its attached Envoy. So we need to be able to disable the functionality.

**Comment by davecheney** [comment]
> If we do that, the single-pod installation will break - only one Contour will serve any config to its attached Envoy. So we need to be able to disable the functionality.

I'm sorry I don't think I understand. Do you mean that leader election requires at least two participants?

**Comment by youngnick** [comment]
No, only the instance that's a leader will open the gRPC port and actually serve xDS requests. When you run in a single-pod Daemonset, all the Contours will connect to the apiserver, elect a leader, and only that leader will serve config to its (local) Envoy. The other Envoys will have no listeners because their xDS server will be unavailable.

**Comment by davecheney** [comment]
Here's what I want to avoid. Currently we have --incluster and not --incluster mode. I don't want to have a --with-leader-election and --without-leader-election mode because that gives us four possible states that envoy can be deployed into.

Is it possible to have a successful leader election with only one candidate? If so, then what I'd like to see is all contours perform a leader election before opening their grpc port. Then, there is no difference between running stand alone, or running with some peers.

**Comment by youngnick** [comment]
Yes, it's definitely possible to have a leader election with only one candidate. It's only in the case that someone's running a single-pod-style arrangement with more than one replica it will be a problem. I have a PR incoming where we can discuss further.

**Comment by youngnick** [comment]
As merged above, leader election is *not* default at the moment. We'd like to gather some data about the approach we're using, since it has the effects listed above, namely needing the Deployment to be `Recreate` not `RollingUpdate`, and stopping single-pod installations from having multiple replicas. It will only be enabled in the `ds-hostnet-split` example deployment for 0.15, and there will be instructions in the upgrade documentation (see #1359  for that work).

**Comment by youngnick** [comment]
I'm closing this issue out, as we have the base functionality, and I'll open a new one to cover moving leader election to a multi-read, single-writer model.
