### ISSUE TITLE
Seeing several 503 requests from Contour under load

### ISSUE THREAD

**Issue by jdelgadillo** [heptio/contour#1205]
**What steps did you take and what happened:**
We have a service/pod deployed with a Contour IngressRoute configured for external access.  When we test with simultaneous users/requests, we see several 503 replies coming from contour.  If we eliminate Contour and use a Proxy to go directly to the service/pod, the 503 errors go away.

Here is documentation of the steps taken to reproduce the issue:
https://github.com/david618/adminnotes/tree/master/matServiceJMeter

**What did you expect to happen:**
Contour should be able to handle the simultaneous requests without issuing 503 errors.

**Anything else you would like to add:**

**Environment:**

- Contour version: 0.12.1 
- Kubernetes version: (use `kubectl version`): v1.12.5
- Kubernetes installer & version: Azure AKS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): centosy

**Comment by stevesloka** [comment]
Hey @jdelgadillo perf testing is always an interesting thing to try and dig into, so much relies on the environment, etc that makes things different/difficult to troubleshoot. 

How are you deployed? Contour? Envoy? Kubernetes? Are you sending traffic to a load balancer then to Envoy? Is Envoy on NodePort or hostnetworking? Have you deployed the monitoring dashboards? Those will help to monitor connections/latency, etc.

**Comment by stevesloka** [comment]
Hey @jdelgadillo, just wanted to follow up here on this issue. Let me know if you have any more details to share so that maybe I can help out. Like I said before, these issues can be difficult to track down but I'm happy to try and help you out! =)

I'm going to close for now, but please reopen if needed.
