### ISSUE TITLE
Default envoy grafana graph reports latency metrics in seconds and not milliseconds

### ISSUE THREAD

**Issue by mwhittington21** [heptio/contour#1207]
**What steps did you take and what happened:**

I installed Contour v0.13.0 and Envoy v1.10.0 and looked at the newly enabled latency metrics in the default provided envoy dashboard. The latency looked very high, and after a little bit of research it seems that the graph is tuned wrong. [The Y axis of the graph should be in milliseconds and not seconds.](https://www.envoyproxy.io/docs/envoy/latest/configuration/cluster_manager/cluster_stats#dynamic-http-statistics)

This should apply to both the "Downstream Latency" and "Upstream Latency" graph.

**Environment:**

- Contour version: v1.13.0

**Comment by davecheney** [comment]
Thanks for working on this @mwhittington21
