### ISSUE TITLE
Upgrade to client-go v12

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1213]
client-go v12 is out, but we just upgraded to v11 in 0.14 and I don't want to chase the bleeding edge to closely as the backwards compat story for client-go is underspecified.

Let's aim to upgrade to client-go v12 in the [0.15 milestone](https://github.com/heptio/contour/milestone/23)

**Comment by DylanGraham** [comment]
I'd like to have a look at this one

**Comment by davecheney** [comment]
Sure thing, but please hold til 0.15 in August

**Comment by stevesloka** [comment]
Hey @DylanGraham, are you still planning on working on this? We just released v0.14 so feel free to take this one if you'd still like to do that.

**Comment by DylanGraham** [comment]
Sure, I can have a look tonight

**Comment by DylanGraham** [comment]
The tests passed but should I be concerned about what `go mod` has removed from the indirect dependencies?

**Comment by davecheney** [comment]
Should be fine, CI always builds from what is in go.mod, so if it
doesn't complain then everything is fine.
