### ISSUE TITLE
Pod status/readiness

### ISSUE THREAD

**Issue by phylake** [heptio/contour#1237]
Does Contour look at pod status or readiness? If not, should it?

I saw `endpointstranslator.go` but it wasn't clear under what conditions `OnAdd()` would be called (i.e. maybe K8s would wait until the Pod was ready to inform Contour)

**Comment by bryanlatten** [comment]
+1, is Contour/Envoy removing the upstream when a pod is changed to terminating? Would like to implement graceful termination like example:
https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace

**Comment by stevesloka** [comment]
@phylake there are `readiness probes` defined for both contour & envoy (https://github.com/heptio/contour/blob/master/examples/ds-hostnet-split/03-envoy.yaml#L47 / https://github.com/heptio/contour/blob/master/examples/ds-hostnet-split/03-contour.yaml#L56) which should limit what pods get requests before they are ready to accept connections. 

For envoy, traffic shouldn't route to a non-ready pod. For contour, an envoy pod shouldn't connect to it unless it's ready to accept gRPC connections. In the event that a contour pod goes unhealthy, it should fail the probe and any envoy connected should reconnect to another healthy contour pod. 

Now for any upstream request which Envoy proxies TO, then contour will honor the status of the pod by only syncing endpoints that are healthy/ready. Another option would be to enable active health checks or wait for the passive health checks to be implemented (in the IngressRoute v1 design). 

Does that help answer your question?

**Comment by bryanlatten** [comment]
@stevesloka I believe both questions are related to envoy's upstreams (where it proxies TO).

Does your statement confirm that Contour will filter out endpoints/pods that are set to `terminating`?

**Comment by stevesloka** [comment]
@bryanlatten yes, any pod with status `Terminating` will not be `Ready` and won't be included in the set of endpoints for that service, so Contour will remove it from Envoy. 

@phylake does this answer your question as well since you were the author the issue?

**Comment by phylake** [comment]
@stevesloka Yes it does. Thank you!

**Comment by phylake** [comment]
@stevesloka Not a Contour issue but do you know if Envoy will drain connections to the `Terminating` Pod(s)? Contour would have updated EDS on the cluster but do you know what Envoy does with any keep-alive connections to the Pod(s)?

**Comment by stevesloka** [comment]
@phylake if you have the `preStop` hook enabled it should tell Envoy to start draining connections: https://github.com/heptio/contour/blob/master/examples/ds-hostnet-split/03-envoy.yaml#L60-L63

I'm not sure how quickly this happens though, we'd need to dig into that and see. I think there's a 30-second timeout?

**Comment by phylake** [comment]
I'm asking about Envoy's upstreams (read: endpoints/pod IPs), not Envoy or Contour

**Comment by stevesloka** [comment]
If an upstream pod has a connection, that's running through an Envoy and that instance of Envoy starts to shut down, then preStop hook will tell Envoy to stop accepting new connections as well as drain the connections that it's managing.

**Comment by phylake** [comment]
Again, I'm not asking about Envoy's lifecycle, I'm asking about upstream services

1. Upstream service Pod terminates
1. > any pod with status Terminating will not be Ready and won't be included in the set of endpoints for that service, so Contour will remove it from Envoy
1. What happens to the keep-alive connections to the Pod? The endpoint was removed from Envoy but I would hope Envoy wouldn't abruptly terminate connections to the Pod

**Comment by stevesloka** [comment]
Sorry, I'm following now. 🤕 

We'd have to check into how Envoy handles this scenario.  When the update to EDS happens, I **think** Envoy keeps a copy of that config until those connections are all gone, but the endpoint is gone, so a reconnect would have to happen somewhere. 

Let me see if I can find that in the Envoy docs.

**Comment by stevesloka** [comment]
Hey, @phylake, I haven't been able to find any docs specifically on this, but maybe look at configuring retry policies. In the event a backend pod terminates, Envoy could retry and pick a new backend. 

Also, interesting comments here in this thread: https://github.com/envoyproxy/envoy/issues/5023

**Comment by phylake** [comment]
No worries thanks for trying. I'm particularly interested in established connections being drained (not terminated) so retries aren't going to help in our case at least.

**Comment by phylake** [comment]
The answer is [`drain_connections_on_host_removal `](https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/api/v2/cds.proto#envoy-api-field-cluster-drain-connections-on-host-removal)
