### ISSUE TITLE
Add README.md files to the `examples` directory and its subdirs

### ISSUE THREAD

**Issue by youngnick** [heptio/contour#1239]
The `examples/` directory would be much easier to use if there was some explanation visible in the Github interface of:
- what each directory contains
- why you would use it

Similarly, inside each of the sub directories, there should be a README.md to explain:
- what's in that directory
- what it does
- why you would use it
- any sharp edges or other things you should know

**Comment by davecheney** [comment]
@youngnick did #1402 addressed this?

**Comment by youngnick** [comment]
Yup. Closed by #1402.
