### ISSUE TITLE
Upgrade to Envoy v1.11.0

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#1242]
**Describe the solution you'd like**
Envoy v1.11.0 has been released, should plan for an upgrade once this version marinates a bit: https://groups.google.com/forum/#!topic/envoy-announce/5zhbmgVCGoI

**Comment by davecheney** [comment]
Thanks Steve. It's too late in the cycle to do this upgrade for 0.14. Obviously there is the technical risk of upgrading late in the cycle, but also the features we want from envoy 1.11.0 need changes in contour to activate. I'll schedule this for early 0.15.

**Comment by rochacon** [comment]
Envoy v1.11.0 introduces a new [`/ready`](https://www.envoyproxy.io/docs/envoy/v1.11.0/operations/admin#get--ready) admin endpoint which improves readiness probes, this might be a nice thing to change for Contour 0.15 too, maybe even improving smoother Envoy rollouts as discussed on #145.
