### ISSUE TITLE
Contour should not log validation errors to stderr

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1252]
master is currently reporting an error whenever the dag is rebuilt. This error should not be logged because it will happen each time the dag is rebuilt, possible 10's of times a second. This will mean users will start to complain about log verbosity from contour again #1131. 
```
ERRO[0000] Error Setting Status of IngressRoute: IngressRoute.contour.heptio.com "httpbin2" is invalid: []: Invalid value: map[string]interface {}{"status":map[string]interface {}{"currentStatus":"valid", "description":"valid IngressRoute"}, "apiVersion":"contour.heptio.com/v1beta1", "kind":"IngressRoute", "metadata":map[string]interface {}{"uid":"5b284a81-882a-11e9-a1b8-42010a980029", "resourceVersion":"157935299", "generation":1, "creationTimestamp":"2019-06-06T07:11:51Z", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"contour.heptio.com/v1beta1\",\"kind\":\"IngressRoute\",\"metadata\":{\"annotations\":{},\"name\":\"httpbin2\",\"namespace\":\"default\"},\"spec\":{\"routes\":[{\"match\":\"/\",\"services\":[{\"name\":\"httpbin\",\"port\":8080},{\"name\":\"httpbin\",\"port\":8080}]}],\"virtualhost\":{\"fqdn\":\"httpbin2.davecheney.com\"}}}\n"}, "name":"httpbin2", "namespace":"default"}, "spec":map[string]interface {}{"routes":[]interface {}{map[string]interface {}{"match":"/", "services":[]interface {}{map[string]interface {}{"name":"httpbin", "port":8080, "strategy":"cookie"}, map[string]interface {}{"name":"httpbin", "port":8080}}}}, "virtualhost":map[string]interface {}{"fqdn":"httpbin2.davecheney.com", "tls":map[string]interface {}{"secretName":"my-certificate-authority"}}}}: validation failure list:
```
Marking this as a blocker on 0.14 because we'll have to do a 0.14.1 to fix it.

**Comment by stevesloka** [comment]
Do you have any steps to reproduce?

**Comment by davecheney** [comment]
I had an ingressroute with an invalid strategy, 'cookie', not 'Cookie'

**Comment by davecheney** [comment]
git blame says I was the last person to touch this. I'll take a look.

**Comment by davecheney** [comment]
ok, here's where the bug is occurring. The error _isn't_ the status message. It's the failure to set the status message. The reason the status message cannot be set is the crd validation prevents it. Here's the scenario

1. have an ingressroute record that doesn't pass validation but has been applied to the cluster in the past.
2. contour processes the record, find that it doesn't pass validation (crd validation and contours are separate) it will try to set status, but doing so it must apply the _entire_ record, including the part that doesn't pass crd validation.
3. That will fail, so we log at line `internal/contour/cachehandler.go:63`.

Given this scenario I'm going to close this bug. The log line _will_ continue to fire, but this _not_ because the ingressroute is invalid -- well, it is, however -- the contour installation is not correct, an invalid ingressroute got past the crd validation.
