### ISSUE TITLE
cmd/contour: Kubeconfig arg always overwrites config file

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#1260]
**What steps did you take and what happened:**
Looking through how the new config file work was done, I was testing it out by creating a config file to set the `kubeconfig` param. 

What I found is that since there's a default value set on the flag, it always overwrites the config file. When I take out the default value it works as expected and the value of the config file is respected.

Here's my config file:
```
{
  "kubeconfig": "/Users/stevesloka/.kube/aws-cluster"
}
```

Here's the command I used to start contour:
```
$ make install && contour serve -c config.json  --xds-address=0.0.0.0        
```

**Comment by davecheney** [comment]
Fixed in 46f7924
