### ISSUE TITLE
ingressroute: drop Ingress object support

### ISSUE THREAD

**Issue by odacremolbap** [heptio/contour#1274]
**Describe the solution you'd like**

Drop `Ingress` object to focus on `IngressRoute` only.

**Anything else you would like to add:**
Although this proposal would need to elaborate, I would like to know how feasible do you think it is. It looks like `Ingress` is mainly a backward compatible object, and that Contour behaves a lot more native with `IngressRoute`.

What about dropping completely `Ingress`, a component that will be able to sync `Ingress` to `IngressRoute` and vice versa:

- An `Ingress` is created/updated/deleted --> we c/u/d an `IngressRoute`.
- An `IngressRoute` is created/updated/deleted --> we c/u/d an `Ingress`.

Benefits:
- Backwards compatible with `Ingress`.
- Not tied to `Ingress` constraints nor undefined behaviors.
- Users would get used to `IngressRoute` even if they define `Ingress` objects.
- Implementation detail: if the translating component was an separate binary, that could be potentially used by other Ingress controllers that can benefit from `IngressRoute`.
- Translating `IngressRoute` back to `Ingress` would make it easy to opt-out of Contour, or use any previous Ingress tooling (externalDNS?).

Cons:
- `IngressRoute` to `Ingress` might lose information (delegation, ...)
- Need to keep in sync 2 objects and their statuses, which might bring confusion regarding who is the _status owner_.
- Keeping in sync 2 structures that don't 1 to 1 to each other might not be trivial.
- This is not something needed nor requested.

**Comment by stevesloka** [comment]
Contour has always supported upstream Kubernetes and will continue to do so. We're not going to drop support for Ingress. 

Additionally, having a translating layer would be very difficult to maintain, we'd end up having to hard code many provider annotations, etc. 

If folks want to use k8s Ingress then Contour will support, if they see value in IngressRoute then we'll support that as well, but I don't see those two streams crossing.

**Comment by odacremolbap** [comment]
Thanks for the explanation.
Closing
