### ISSUE TITLE
Envoy v1.11: Investigate using `/ready` endpoint for probes

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#1277]
**Describe the solution you'd like**
Mentioned in #1242, Envoy v1.11.0 introduces a new /ready admin endpoint which improves readiness probes, this might be a nice thing to change for Contour 0.15 too, maybe even improving smoother Envoy rollouts as discussed on #1245 

// cc @rochacon

**Comment by stevesloka** [comment]
The only nice thing about the way we expose today is that we don't need to expose the entire admin site to a port for the kubelet to check against. So let's keep that in mind when this is investigated such that we don't accidentally expose that admin UI.

**Comment by rochacon** [comment]
I've been testing Contour with Envoy 1.11 to evaluate the use of `/ready` and trim down the steps discussed at #145. It works pretty similar to the current `/healthz` endpoint, with the addition of a response body with the current state of the server (e.g. `LIVE` / `DRAINING`).

Contour requires this patch to passthrough `/ready` to the admin in the restricted listener (port 8002): https://github.com/heptio/contour/compare/master...rochacon:enable-ready-endpoint

I believe we should add the above patch to allow the use of `/ready` even though it won't change the current probe behavior it allows this more specific endpoint to be used. If you agree I'll open the PR for it.

**Comment by stevesloka** [comment]
@rochacon yup I think switching over to this endpoint is fine, happy to take a PR!

**Comment by davecheney** [comment]
@rochacon could you send that PR please.
