### ISSUE TITLE
Docker image for v0.14.1 release does not exist

### ISSUE THREAD

**Issue by annismckenzie** [heptio/contour#1292]
You guys released v0.14.1 a couple hours ago but the image doesn't exist:

```sh
$ docker pull gcr.io/heptio-images/contour:v0.14.1
Error response from daemon: manifest for gcr.io/heptio-images/contour:v0.14.1 not found
```

I wanted to roll it out to our fleet but the pods immediately errored on the image pull. Would be great if you fixed that so we can upgrade. :) Thanks for Contour!

**Comment by davecheney** [comment]
Oops. Fixing now

**Comment by davecheney** [comment]
Successfully built a36c38f2ae01
Successfully tagged gcr.io/heptio-images/contour:v0.14.1
docker push gcr.io/heptio-images/contour:v0.14.1
The push refers to repository [gcr.io/heptio-images/contour]
6b4ac599e96f: Preparing
6b4ac599e96f: Pushed
v0.14.1: digest: sha256:4405a52be5c8000a78c6f75d26054a92c766a007f05a506531c9b60ba0e944b1 size: 529
Finished: SUCCESS

**Comment by annismckenzie** [comment]
Thank you, Dave! Hopefully I didn't wake you with this – you tagged the release and it's only been 7 hours… 🙈
