### ISSUE TITLE
Backport klog fix

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1306]
Backport https://github.com/heptio/contour/pull/1302

**Comment by so0k** [comment]
until 0.14.2 is released, we should just mount `/tmp` into contour pod?

**Comment by davecheney** [comment]
You should mount a /tmp, we don't parse flags so `--lgtostderr` will not be recognised

**Comment by so0k** [comment]
0.14.2 is meant to drop on Monday anyway, for the Envoy 1.11.1 security release - right?

seems your plan is to backport this as well?

**Comment by so0k** [comment]
ah Pr is already there - cool

**Comment by davecheney** [comment]
Fixed in 6ce3df0994c04b9d2b350782f3f9af1393c7e3ce
