### ISSUE TITLE
Configure size of the client request body

### ISSUE THREAD

**Issue by pacifier17** [heptio/contour#1308]
Hi,
I am not able to find any Contour notation to control the size of the client request body. What is the max size that it allows by default? Is there a way to change it?

**Comment by davecheney** [comment]
I don’t believe we apply any restriction on the size of the client request body. I’m pretty confident that envoy doesn’t impose any limit by default. 

We could add a setting for this, but what is your use case? Why should envoy impose this restinction, not your backend application?

**Comment by pacifier17** [comment]
Thanks for responding. If Contour/envoy does not impose any restrictions then I think you are right, this restriction should be handled at the application level.

**Comment by davecheney** [comment]
Historically proxies like nginx and Apache buffered incoming requests to disk to ram, hence the need for a limit on how much to buffer. I don’t believe that envoy buffers the response any more than is necessary to forward it to a backend application server.

**Comment by pacifier17** [comment]
Ahh got it, that is why I see annotation of the same in nginx. Just curious, any idea why envoy does not buffer the requests to ram? Does it have a performance or any other kind of impact?

**Comment by davecheney** [comment]
I’m not sure, maybe it’s not necessary.

**Comment by pacifier17** [comment]
Ok thanks.
