### ISSUE TITLE
Minikube example link broken

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#133]
The minikube example link (https://github.com/heptio/contour#configuring-dns) does not work. 

Currently: https://j.hept.io/contour-kuard-minikube-example maps to: https://github.com/heptio/contour/raw/minikube/deployment/example-workload/kuard-minikube.yaml which is invalid.

**Comment by davecheney** [comment]
@rbankston this was #16. Can you please fix the shortlink or send a PR to revert this change. Thank you.

**Comment by rbankston** [comment]
The shortlink has been fixed and works as expected. @davecheney @stevesloka
