### ISSUE TITLE
Append --v2-config-only to all v2 grpc configs

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#138]
When Envoy finds something invalid in the contour.yaml bootstrap config it falls back to parsing it as json which leads to confusing and hard to debug errors #136.

We can use `--v2-config-only` to force envoy to treat the file as yaml, and make the error easier to understand.

**Comment by cmaloney** [comment]
I'd be interested in trying to put together a simple patch to do this / get into contributing to contour

**Comment by davecheney** [comment]
Sure thing. Go for it, but I probably won't look at it til 0.3 is released on Thursday as we're grinding down to code complete now.

The trick is to remember to run the `render.sh` script in the `deployment/` directory to regenerate the various rbac and non rbac versions of the manifests. Don't worry if you get it wrong, CI will catch it.
