### ISSUE TITLE
Misleading error message when TCPProxy IngressRoute references a service that is an HTTP Service

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#1399]
**What steps did you take and what happened:**
1. Created a deployment and service
2. Created a secret with a TLS cert
3. Created an Ingress resource with TLS that references the service
4. Created a TCPProxy IngressRoute that references the same service
5. Get the following IngressRoute status:

```
NAME    FQDN          TLS SECRET   FIRST ROUTE   STATUS    STATUS DESCRIPTION
nginx   example.com   ssl-cert                   invalid   tcpproxy: service default/nginx/80: not found
``` 

**What did you expect to happen:**
Contour to produce a meaningful error message. The current error message is misleading because the service does indeed exist.

**Anything else you would like to add:**
Gist with resources for repro: https://gist.github.com/alexbrand/ff0d8efc295c4535d682a968840f2ce4

I think the problem occurs when building the DAG. Because of the Ingress resource, Contour determines that the Service is a `dag.HTTPService` and adds it to the `dag.Builder.services` cache. When processing the IngressRoute, the DAG builder lookups up the service and gets a `dag.HTTPService` back. This results in the DAG builder taking the `default` case and returning `nil` (https://github.com/heptio/contour/blob/master/internal/dag/builder.go#L114). This `nil` is bubbled up to the `b.lookupTCPService` call site and thus the IngressRoute is marked as invalid (https://github.com/heptio/contour/blob/master/internal/dag/builder.go#L667).

**Environment:**

- Contour version: `master`

**Comment by davecheney** [comment]
@alexbrand thanks for you analysis. I believe this is correct, and in fact might even be non deterministic. Because b.services holds both tcpservices and httpservices its sort of a crapshoot which is populated first for that service. Its probably mostly deterministic if a single ingressroute mentions a service in a route then a tcpproxy. However that is probably not possible either at the moment because #910
