### ISSUE TITLE
Contour releases should pin envoy image to a known version

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#142]
/ht @stevesloka for pushing this.

For each Contour release we update the deployment manifests to point to a specific contour version, but the envoy version is left floating at `:latest`.

This caught me out for #136 and we should take steps to avoid this in the future. At the moment we need some features from master that aren't in 1.5, but for contour 0.4, or envoy 1.6 (whichever is the sooner) we should pin the deployment manifests on master and the release branch to a known version or hash.

**Comment by sevein** [comment]
#222 depends on Envoy 1.6.
