### ISSUE TITLE
install manifest in README broken in master

### ISSUE THREAD

**Issue by underrun** [heptio/contour#1443]
**What steps did you take and what happened:**
Attempted to install contour using README in master which suggests `kubectl apply -f https://raw.githubusercontent.com/heptio/contour/master/examples/render/contour.yaml` as a way to install contour.

applying this manifest fails as some of the yaml docs are not properly separated with `---` so that it appears as if an rbac role has a `spec` field in it and validation fails. properly separating the yaml documents in the manifest seems to fix the failed validation, but based on the breakage I'm not highly confident that everything was installed correctly.

**What did you expect to happen:**
contour to be installed successfully at either the latest release version (preferably) or current master branch.

**Anything else you would like to add:**
README in master are typically the first docs people see / use - my suggestion would be that the install instructions in master should always refer to latest stable version with an indication of how to install from master branch if that's desired for testing or contributing.

**Environment:**

- Contour version: 0.15 / master
- Kubernetes version: (use `kubectl version`): n/a
- Kubernetes installer & version: n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by davecheney** [comment]
@youngnick can you please take a look at the render issues

**Comment by davecheney** [comment]
@underrun sorry for the problems you experienced, we’ll get those fixed quickly. 

WRT to the first user experience, we do fork off manifests for each release, but that’s not much help when master is the default branch that GitHub shows users. 

Once we tag a stable 1.0 release we plan to switch all our documentation over to point to our stable release.

**Comment by davecheney** [comment]
@youngnick i'll fix the manifests
