### ISSUE TITLE
docker v0.2.1 image not released

### ISSUE THREAD

**Issue by glerchundi** [heptio/contour#153]
In `release-0.2` branch deployment specs point to an image that doesn't exist:

```
$> docker pull gcr.io/heptio-images/contour:v0.2.1
Error response from daemon: manifest for gcr.io/heptio-images/contour:v0.2.1 not found
```

**Comment by davecheney** [comment]
Fixed. This was my mistake, I didn't run the release tag job for 0.2.1. I've updated the release documentation to make sure I don't forget in the future.
