### ISSUE TITLE
Support inline certificate delivery

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#158]
When envoyproxy/envoy#1357 is closed switch from passing certificate material in `/config` to passing cert material in the `v2.DiscoveryResponse` message.

- [ ] remove `/config` volume mount from the `contour` container.
- [ ] send certificate data inline in `v2.DiscoveryResponse`.

**Comment by sevein** [comment]
The issue is now closed (commit https://github.com/envoyproxy/envoy/commit/01ee72548d0b075c29dadade7b96143cd116e9a9 fixes it) and it's planned to be included in Envoy 1.6.0 with no due date.

**Comment by sevein** [comment]
I've made an [attempt](https://github.com/heptio/contour/compare/master...sevein:inline-tls-certs?expand=1). Looking forward to hear your thoughts.

**Comment by davecheney** [comment]
@sevein looks pretty good from here, wanna push the "create PR button"?
