### ISSUE TITLE
Switch to logrus 

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#162]
Contour currently uses its on `internal/log` logging "framework". This dates back to a time when @ncdc and I were spitballling logger interfaces.

Contour is now [serious business][https://vignette.wikia.nocookie.net/lego/images/e/ee/Lord_Business_physical.png] so it is not appropriate to use it as a vehicle for experimentation.

logrus is already used across other Heptio products, so switch to it.

**Comment by ncdc** [comment]
I do still believe that we should define a logging interface and use that everywhere, just in case we decide to swap out logrus with something else at some point. There are, for example, some race conditions when using logrus hooks to manipulate a log entry in multiple goroutines.

**Comment by davecheney** [comment]
Logrus has this, https://godoc.org/github.com/sirupsen/logrus#StdLogger, which isn't really good enough because you loose WithFields :(

**Comment by ncdc** [comment]
@davecheney we've been using `FieldLogger` in Ark, although I still want to have a library-independent interface so we can swap implementations if desired without having to modify every .go file that imports logrus.
