### ISSUE TITLE
Allow setting upstream request timeout

### ISSUE THREAD

**Issue by cmaloney** [heptio/contour#164]
I have an application where some requests take quite a while to process (up to a couple minutes). By default, envoy has a per-request upstream timeout of 15 seconds (https://www.envoyproxy.io/docs/envoy/latest/api-v1/route_config/route.html#config-http-conn-man-route-table-route-timeout). That means that these requests timeout in envoy and so the client gets an HTTP 504.

I'd like to teach contour to be able to set a timeout, probably by adding an annotation (I'm not sure if there is a "standard" annotation for it yet).

**Comment by davecheney** [comment]
Yup. At the moment it’s hard coded but I can absolutely make this an annotation at the ingress or service level.

**Comment by cmaloney** [comment]
Some other lbs settings:
Nginx: nginx.ingress.kubernetes.io/upstream-fail-timeout https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md#custom-nginx-upstream-checks
Bluemix: ingress.bluemix.net/proxy-read-timeout https://console.bluemix.net/docs/containers/cs_annotations.html#proxy-connect-timeout
Torchbox TrafficServer: ingress.kubernetes.io/read-response-timeout https://torchbox.github.io/k8s-ts-ingress/annotations/

Given there isn't any one there that strongly matches for definition + is in the base spec I'd probably just say a new / contour-specific annotation until a standard emerges.

**Comment by davecheney** [comment]
Yeah, this annotation soup is not awesome :(

**Comment by arun17sep2018** [comment]
@cmaloney  . you helped me to understand envoy issue, Thanks a lot :)
