### ISSUE TITLE
Combine Contour and Istio?

### ISSUE THREAD

**Issue by StevenACoffman** [heptio/contour#184]
Let me start by saying I understand the differences between Contour and Istio. Contour seems equivalent to Datawire's Ambassador. Ambassador has documentation [for combining it with Istio](https://www.getambassador.io/user-guide/with-istio).

Can we use Contour as an Edge gateway ("north-south" traffic) combined with Istio for L7 observability, routing, and resilience to service-to-service traffic (aka “east-west” traffic)? Is there documentation for this?

**Comment by davecheney** [comment]
Hi @StevenACoffman, thanks for raising this issue.

>  Contour seems equivalent to Datawire's Ambassador.

Contour's a Kubernetes Ingress controller. That's all we do, ingress.

> Can we use Contour as an Edge gateway ("north-south" traffic) combined with Istio for L7 observability, routing, and resilience to service-to-service traffic (aka “east-west” traffic)?

In theory yes, but you'd have to express your edge as kubernetes ingress objects, which is probably not flexible enough, or convenient.

Given I have only a cursory knowledge of istio, I think your best approach would be to stick to an istio only solution.

**Comment by StevenACoffman** [comment]
Thanks! That saves me a lot of time.
