### ISSUE TITLE
Cannot route to services that have long enough namespace or name

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#186]
When a service is created in a namespace that has a long enough name, or when the service namespace + service name is long enough, any attempts to connect to the service via Contour result in a "No healthy upstream" response.

I believe the issue is that after translation, there is a mismatch between the Cluster's EDS configuration and the Cluster Load Assignments. More specifically, the `ClusterName` in the Cluster Load Assignment does not match up with the `ServiceName` in the Cluster's EDS configuration, because the `ClusterName` is being hashed when longer than 60 chars.

**Comment by davecheney** [comment]
Thanks for raising this issue, can you provide a sample service yaml and
I'll try to turn it into a unit test.

**Comment by alexbrand** [comment]
Sure thing. I used the sample deployments documented in Contour, just with a long namespace:
https://gist.github.com/alexbrand/fa4a715dc7e8e1dc5753955dde057ab1

**Comment by davecheney** [comment]
Thanks. I'll integrate that into the e2e tests i've been working on.
