### ISSUE TITLE
Cannot route requests with full URL in Path

### ISSUE THREAD

**Issue by sgringwe** [heptio/contour#188]
*Edited for more clarity*

If the Path of a request includes is the whole URL such as "GET https://foo.example.com/healthz ..." instead of simply "GET /healthz ..." with a Host header, the request fails to route to the right Host. This issue also seems to trigger if the leading "/" is left out such as GET healthz ...". This failure to route happens even if the proper Host header is sent.

These did work with other ingress controllers which is why I thought it was worth reporting (nginx, gce-ingress).

**Comment by sgringwe** [comment]
Hey @davecheney - sorry for the confusion here but I actually edited the issue a little bit after posting. Thought I got the edit in quick enough, but looks like you responded to the old issue content.

All in all, we'll be easily be able to work around this and ok to close if you'd like, but perhaps some of our users will run into this as well in our API.

**Comment by davecheney** [comment]
The sort answer is if there is no host header present on the request, envoy will route the request to the route registered with the vhost “*”. This is different to the nginx controller because of the way nginx will assign the default host to the first server defined. I don’t know how to gce controller handles this.

Can you tell me more about your ingress usage . I don’t think I understand your problem properly.

**Comment by sgringwe** [comment]
Happy to provide more detail. To clarify - this issue exists even when Host header is set properly. My initial post that I then edited incorrectly assumed that the Host header wasn't present, when it actually was.

To replicate the issue, my ingress looks like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: "contour"
spec:
  tls:
  - hosts:
    - foo.example.com
    secretName: tls
  rules:
    - host: foo.exmaple.com
      http:
        paths:
        - path: /
          backend:
            serviceName:web-service
            servicePort: 80
```

And the following ruby script shows the issue:

```
uri = URI.parse("https://foo.example.com")
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Post.new("https://foo.example.com/healthz")
request.add_field 'Content-Type', 'application/json'
response = http.request(request)
```

The issue is the line `Net::HTTP::Post.new("https://foo.example.com/healthz")`. The line `Net::HTTP::Post.new("healthz")` also causes the issue.

It outputs HTTP request that looks like:

```
<- "POST healthz HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nContent-Type: application/json\r\nConnection: close\r\nHost: foo.example.com\r\nContent-Length: 0\r\n\r\n"
<- ""
-> "HTTP/1.1 400 Bad Request\r\n"
-> "content-length: 0\r\n"
-> "connection: close\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes
Conn close
=> #<Net::HTTPBadRequest 400 Bad Request readbody=true>
```

However, this *does* work properly: `Net::HTTP::Post.new("/healthz")`. It performs an HTTP request that looks like:

```
<- "POST /healthz HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nContent-Type: application/json\r\nConnection: close\r\nHost: foo.example.com\r\nContent-Length: 0\r\n\r\n"
<- ""
-> "HTTP/1.1 200 OK\r\n"
-> "date: Mon, 29 Jan 2018 00:13:47 GMT\r\n"
-> "x-frame-options: SAMEORIGIN\r\n"
-> "x-xss-protection: 1; mode=block\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "last-modified: Mon, 29 Jan 2018 00:13:47 GMT\r\n"
-> "cache-control: private, no-cache, must-revalidate, max-age=1\r\n"
-> "content-type: text/plain; charset=utf-8\r\n"
-> "x-request-id: 15bd5397-bb41-4724-a9f6-93140660e6cb\r\n"
-> "x-runtime: 0.011855\r\n"
-> "strict-transport-security: max-age=15552000; includeSubDomains\r\n"
-> "x-envoy-upstream-service-time: 13\r\n"
-> "server: envoy\r\n"
-> "connection: close\r\n"
-> "transfer-encoding: chunked\r\n"
-> "\r\n"
-> "7\r\n"
reading 7 bytes...
-> ""
-> "success"
```

From what I can tell, it is a malformed Path that causes issues. A potential fix would be to intelligently fix bad request paths on the ingress side. For example if path comes in as a full url, remove the Host part from the url and only use the Path part. Or if the leading "/" is missing, add it in.

Sorry for lack of deep networking knowledge - I'm sure I got some lingo and assumptions wrong somewhere in here.

**Comment by davecheney** [comment]
```
"POST healthz HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nContent-Type: application/json\r\nConnection: close\r\nHost: foo.example.com\r\nContent-Length: 0\r\n\r\n"
```
Is a bad request because HTTP/1.1 requests should start with a `/`

**Comment by sgringwe** [comment]
👍 

After chatting with Dave about the full URL, Dave explained that for a proxy it is valid but for a reverse proxy it is invalid. Going to go ahead and close this out.
