### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sevein** [heptio/contour#189]
https://j.hept.io/contour-kuard-minikube-example (used in README.md) redirects to:

    https://raw.githubusercontent.com/heptio/contour/master/deployment/example-workload/kuard.yaml

I believe the URL should be:

    https://raw.githubusercontent.com/heptio/contour/master/deployment/example-workload/kuard-minikube.yaml

**Comment by davecheney** [comment]
I summon @jbeda as the keeper of the shortlinks!

**Comment by jbeda** [comment]
Fixed! Sorry about that!
