### ISSUE TITLE
Add benchmarks for v1 REST xDS APIs

### ISSUE THREAD

**Issue by kstewart** [heptio/contour#2]
Add some basic benchmarks for the CDS, SDS, and RDS for 1, 10, 100, and 10,000 cache entires.

The key things I want to see is the processing time, and the bytes allocated (JSON is expensive).

We need this information to judge the cost of making v1 REST a wrapper around v2 gRPC.Fetch.

**Comment by davecheney** [comment]
Not going to do this, REST API is end of life.
