### ISSUE TITLE
Non standard ingress ports break routing

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#210]
This issue was reported on #contour on the k8s slack. In essence, when using minikube the service load balancer will allocate a random high port as the ingress. This is problematic because this port is not a _well known_ (RFC 2616 gibberish) port so `curl(1)` or browsers will include the port number in the `Host:` header. This causes Envoy to misroute the request because the `domains` file the RDS `virtualhost` entry does not contain the matching `:port` suffix.

The problem is the port minikube chooses is not easily predictable, so it is not simply a matter of including various permutations of `hostname:port` in the `virtualhost.domains` array.

Supporting Envoy ticket, envoyproxy/envoy#1269.

### Workarounds

The workaround if you are using minikube is to either force the `Host:` header with something like
```
curl -H "Host: example.com" -v http://example.com:31847
```
Or use a OSX specific extension to curl
```
curl -v --connect-to example.com:80:example.com:31847 http://example.com/
```

**Comment by sevein** [comment]
As a workaround, I've also been using `socat` to set up a TCP proxy so I can access from my browser:

    $ socat TCP-LISTEN:80,fork TCP4:example.com:31847

This way the browser sends the `Host: example.com` header as expected by Envoy.
It should work as long as `example.com` resolves to `127.0.0.1`.

**Comment by davecheney** [comment]
I'm going to close this issue as there is nothing more to be done on the contour side for the moment.

- minikube specific issues are documented per #353 
- Host headers with explicit :port suffixes are handled per #398

**Comment by bitsofinfo** [comment]
https://github.com/envoyproxy/envoy/issues/886

**Comment by youngnick** [comment]
The spike in #1125 has meant that we can actually do this now. Reopening.

**Comment by youngnick** [comment]
Since the above PRs have been merged, it is now possible to use non-standard ingress ports as much as you like - any port in the Host header will now match.

This means that Minikube and kind will now work just fine for testing and development. Win!
