### ISSUE TITLE
Allow specifying envoy retry policy via annotations

### ISSUE THREAD

**Issue by cmaloney** [heptio/contour#221]
Envoy allows [setting a per-route retry policy](https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/rds.proto#routeaction-retrypolicy). It would be useful if contour allowed ingresses to specify their retry semantics via annotations.

In my particular use case this comes up because backends for a couple services come/go without a lot of warning when their k8s deployment is updated, and there is a brief period when a pod for various reasons will accept a tcp connection but the connection will end up being closed before any data is sent on the connection, meaning envoy will return a `upstream connect error or disconnect/reset before headers`. 

Setting the `retry_on` to `gateway-error` or `connect-failure`, envoy should see the failure, and then try again connecting to a still operating backend.

**Comment by davecheney** [comment]
@cmaloney with #241 landed, is there anything more to do here for 0.4?

**Comment by cmaloney** [comment]
I think it's all done / that covered all the bits I needed.

**Comment by davecheney** [comment]
👍
