### ISSUE TITLE
Remove unneeded items from Docker image context

### ISSUE THREAD

**Issue by sevein** [heptio/contour#235]
More than 99% of the Docker image context is used by `/.git` and `/vendor` but I think they're unused during the build. Here's a little experiment where I use `.dockerignore` to remove both directories from the context:

```
$ docker build -t sevein/contour:master .
Sending build context to Docker daemon  118.1MB
[...]

$ echo -e "/.git\n/vendor" > .dockerignore

$ docker build -t sevein/contour:master .
Sending build context to Docker daemon  641.5kB
[...]
```

It doesn't make a very big difference but sending the context to my local minikube goes down from 4.5 to 0.2 seconds.

Should it be added to the repo?

**Comment by davecheney** [comment]
SGTM. 👍
