### ISSUE TITLE
Virtual host exceeds allowed maximum length

### ISSUE THREAD

**Issue by ValFadeev** [heptio/contour#25]
Hi,
I am trying to use contour in conjunction with ingress objects for host-based routing to backend services. Here is an example of the `spec` section from the ingress definition:
```json
  "spec": {
    "rules": [
      {
        "host": "my-very-very-long-service-host-name.my.domainname",
        "http": {
          "paths": [
            {
              "backend": {
                "serviceName": "my-service-name",
                "servicePort": 8088
              }
            }
          ]
        }
      }
    ]
  }
```
Contour picks it up but throws an error because the generated virtual host name turns out to be too long: 
```
[2017-11-01 14:22:54.787][1][warning][upstream] source/common/router/rds_subscription.cc:65] rds: fetch failure: Invalid virtual host name: Length of default/my-service-name/my-very-very-long-service-host-name.my.domainname (73) exceeds allowed maximum length (60)
```
Unfortunately, I am unable to change the enforced naming convention to shorten the host names very quickly. Is there a workaround or a plan to make this configurable? What would the considerations be if the virtual host could be overridden through an annotation? Thanks!

**Comment by davecheney** [comment]
Thanks for raising this issue; I knew that at some point I would have to hash the names of the various elements going into a container name; namespace, ingress name, vhost. Look's like I'll have to raise the priority on this.

**Comment by davecheney** [comment]
Marking as 0.2, but it might be possible to get this backported to 0.1.1. I'll see

**Comment by davecheney** [comment]
@ValFadeev Hello. I think I've fixed this issue and this fix will be available in the `:master` tag in a few minutes. If you're using the quickstart examples from the README you can bounce your Contour pods and they will upgrade to the `:master` image (if you've deployed with `:v0.1.0` or `:latest` you'll need to change to `:master`).

You can do this simply with
```
kubectl -n heptio-contour delete po -l app=contour
```
If this hasn't fixed the problem, please reopen the issue and I'll have another shot.

Thanks

Dave

**Comment by ValFadeev** [comment]
Thanks for your quick response, really appreciated! Moved on to the next problem :)
