### ISSUE TITLE
Envoy doesnt appear to serve tls

### ISSUE THREAD

**Issue by alvaroaleman** [heptio/contour#265]
Hi,

Currently playing around with contour, when trying to connect via tls I get the following:

```
$ curl https://192.168.0.241:443 -H 'Host: my.host' -v -I -k
* Rebuilt URL to: https://192.168.0.241:443/
*   Trying 192.168.0.241...
* TCP_NODELAY set
* Connected to 192.168.0.241 (192.168.0.241) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: PROFILE=SYSTEM
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

The same curl against a nginx ingress controller running in the same cluster works perfectly fine:

```
$ curl https://192.168.0.41:443 -H 'Host: my.host' -I -k
HTTP/2 302 
server: nginx/1.13.7
date: Sat, 10 Mar 2018 00:17:42 GMT
content-type: text/html; charset=utf-8
location: http://my.host/auth/login/?next=/
content-language: en
vary: Accept-Language,Cookie
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15724800; includeSubDomains;
```

**Comment by davecheney** [comment]
@alvaroaleman sorry you're having problems. Can you please describe how you've deployed contour.

**Comment by davecheney** [comment]
Also, how are you generating that TLS certificate. It's unusual to offer TLS on an IP address (and AFAIK the `Host:` header is only consulted after TLS negotiation)

**Comment by alvaroaleman** [comment]
You are right about the `Host` header, I somehow thought it would get transferred unencrypted because of SNI.

When using the newly learned `--resolve` curl param everything works as expected:

```
curl --resolve my.host:443:192.168.0.241 https://my.host -IL
HTTP/2 302 
date: Mon, 12 Mar 2018 07:24:40 GMT
server: envoy
```
The only difference seems to be that nginx falls back to any certificate when it can't find the correct one which Envoy does not.

Thanks for your help!

**Comment by davecheney** [comment]
nginx treats the "first" server defined in the configuration as the
default, which is used when no other server matches. This could explain the
behaviour. This also matches the behaviour of the current ingress object,
which is sometimes hard to explain. Envoy also has a notion of "default",
but its applied explicitly by binding routes and hosts to a virtual host
called "*". Things get more complicated when you mix TLS into the mix as
there is no notion o a default HTTPS server, well, unless you're not
interested in checking the certs match the hostname,
