### ISSUE TITLE
Improve gRPC XDS handshaking

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#273]
Currently contour plays fast and loose with the xDS protocol[0]; we don't really check the sequence numbers sent to envoy, and we ignore the ack back. 

This should be improved for 0.5.

[0]: https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md

**Comment by rosskukulinski** [comment]
@davecheney is this still an open issue?

**Comment by davecheney** [comment]
Yes. There is a delta between the go-control-plane implementation of the
xDS protocol, which was written after ours, and our own. Closing that gap
is important to make sure we implement the nuances of xDS correctly.

**Comment by davecheney** [comment]
I'm going to bump this to 0.7 and we'll cover it with the general upgrades of the project dependencies early in the cycle.

**Comment by rosskukulinski** [comment]
Sounds good, thanks

**Comment by davecheney** [comment]
Lowering priority

**Comment by davecheney** [comment]
As one of our oldest issues its time to come clean and recognise that this work is not going to happen any time soon. I’m going to close this issue and will open a new one when and if required.

**Comment by lrouquette** [comment]
I'm surprised this is not a high priority item, especially in light of [this comment](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#when-to-send-an-update). From what I've seen while watching these logs for quite a while now, not respecting the protocol and [this issue](https://github.com/heptio/contour/issues/426) are the likely reasons for envoy to [OOM](https://github.com/heptio/contour/issues/599). Any thoughts?

**Comment by davecheney** [comment]
@lrouquette yup, we know we send too many updates to Envoy. This is being tracked in the context of #499.

This ticket existed from a time before envoyproxy/go-control-plane existed and was intended to be a placeholder to unify those two implementations. Simply put, that never happened, so this ticket has been closed.

**Comment by davecheney** [comment]
@lrouquette thank you for pointing out the mistake in the way we're handing the XDS transaction. I'm preparing a PR now that should correct the defect.
