### ISSUE TITLE
Support health checking of Contour

### ISSUE THREAD

**Issue by cten** [heptio/contour#283]
Most load balancers have the feature of checking whether an endpoint is healthy or not. In HAProxy a common way to do this is use the HEAD method and expect a specific return code. 
Can a health endpoint be added to Contour, whether its a /healthz path or just supporting the HEAD method on the base path doesn't really matter to me. 
Thanks

**Comment by stevesloka** [comment]
Sorry, misread this issue. My previous comment was health checking endpoints, not Contour itself.

**Comment by stevesloka** [comment]
To clarify this Issue, the description is to health check Contour, there's a new issue opened to track health checking Envoy: #695

**Comment by bpownow** [comment]
+1 on this issue. Thanks @stevesloka!

**Comment by davecheney** [comment]
Contour has supported  a `/heath` endpoint on the debug listener, `0.0.0.0:8000` since release 0.6.

To close this issue

- [ ] Does `/health` need to be renamed to `/healthz`? 
- [ ] `/health`/`/healthz` should be woven through the example `deployments/`

**Comment by cten** [comment]
That works for me, healthz might be more consistent with other apps but as
long as there is a health endpoint that's documented in good.
Thanks

**Comment by stevesloka** [comment]
I do agree that `/healthz` is a little more consistent, but today the health check endpoint always returns `200 OK` (https://github.com/heptio/contour/blob/master/internal/metrics/metrics.go#L217-L222). 

I think we need to expand on this and wire in some additional checks to determine if Contour is actually healthy or not. For instance, what if Contour can't reach the k8s api server, etc?
