### ISSUE TITLE
Support gRPC-Web

### ISSUE THREAD

**Issue by glerchundi** [heptio/contour#300]
Proposals:
1. One annotation `contour.heptio.com/http-filter.{name}` and just support those filters that require no config parameters, i.e `grpc_web` :)
2. Two annotations `contour.heptio.com/http-filter.{name}` and another one for the configuration `contour.heptio.com/http-filter.{http_filter_name}-config`
3. One annotation to enable it like the above and then another that points to a config map with custom http filter parameters.

Do you agree that it's preferable to put this on a `Ingress`?

In case there are no objections I would like to go with the first one. Start small and extend this feature in further PRs.

/cc @davecheney 

Reference:
https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.html#config-filter-network-http-connection-manager-v2-httpfilter

**Comment by glerchundi** [comment]
> @glerchundi thanks for raising this proposal. I'm not comfortable with opening this generic hole, it feels like configuration passthrough.

Yeah, that was my feeling too but I didn't find something that feels me completely comfortable.

> Instead what i'd prefer to see is perhaps binary annotations for thinks like grpc_web, or just sane defaults like gzip. We made a call in #217 to turn off tls 1.0 without an option to turn it on at all, I think we could do more like this.

Cool, seems reasonable at least for the `grpc_web` case. Will submit a PR with this added by default.

**Comment by davecheney** [comment]
@glerchundi cool. Thanks for looking into this.

**Comment by glerchundi** [comment]
As per #303, you'll re-initiate the discussion here.

> I'm ok with enabling this setting globally with a default of true if it applies transparently -- it's not clear from the reading of the envoy or grpc-web documentation if this is true -- and there is no reasonable reason to not leave it turned on for all users. This is the same argument i'll make for enabling gzip everywhere without an option to turn it off.

The idea is to have `grpc-web` filter **always on** at least if we can ensure that everything works transparently. Where transparently means everything works as it behaved before but in case Envoy founds a `content-type` with `application/grpc-web*` it will be automatically converted to a http2 gRPC request in the upstream.

Are we ok with this?

**Comment by davecheney** [comment]
If this can work transparently, then I don't see a reason to not turn it on
for everyone. If someone sends a request type of `application/grpc-web` and
it isn't the start of a tunneled grpc stream, then the backend is going to
reject it, or at least mishandle it badly enough that it won't cause any
harm.

Basically, if this can be shown to be transparent, then we can probably get
away with a much smaller change that just turns it on for everyone.

**Comment by glerchundi** [comment]
Ok, will create a new PR.
