### ISSUE TITLE
LDS and RDS race condition

### ISSUE THREAD

**Issue by Lookyan** [heptio/contour#306]
I discovered a problem with listener and route envoy initialization.

*Steps to reproduce:*
1. Create a kubernetes cluster with ~ 300+ services
2. Start envoy and contour simultaneously (everything will be ok)
3. Reload envoy

*Problem:*
After envoy reload it will have only clusters and endpoints initialized. Neither Listeners nor routes are there. I think there is a problem with grpc communication somewhere (maybe contour should push changes, but it thinks that everything is already sent).
After that to solve this problem we can reload contour. But after this action, we still won't see any ready listeners and routes. If we opened /stats page then we would see that listener is in the warming stage and it's waiting for routes initialization. But rds can't update routes configuration. 

For now, I'm digging into this problem and it seems like race condition in grpc communication because when envoy and contour start simultaneously everything works as expected.

**Comment by Lookyan** [comment]
More info from contour logs:
```
time="2018-03-28T23:56:58+03:00" level=info msg="waiting for notification" api=LDS connection=1 context=grpc version=0
time="2018-03-28T23:56:58+03:00" level=info msg="notification received" api=LDS connection=1 context=grpc version=110
time="2018-03-28T23:56:58+03:00" level=info msg="waiting for notification" api=LDS connection=1 context=grpc version=110
time="2018-03-28T23:58:09+03:00" level=error msg="stream terminated" api=LDS connection=1 context=grpc error="context canceled"
```

Then contour doesn't get any LDS streams (even after many envoy reloads).

**Comment by davecheney** [comment]
have a look on the envoy side, I think you might be hitting a limit on the
number of simultaneous grpc streams.

**Comment by davecheney** [comment]
```

contour::high_priority::max_connections::1024
contour::high_priority::max_pending_requests::1024

```
That's the problem. I need to raise the circuit breaking limits on the
static entry for the contour cluster, it comes from `contour bootstrap`.

The next limit we hit will probably be file descriptors.

**Comment by Lookyan** [comment]
I've updated it:

```
contour::outlier::success_rate_average::-1
contour::outlier::success_rate_ejection_threshold::-1
contour::default_priority::max_connections::100000
contour::default_priority::max_pending_requests::100000
contour::default_priority::max_requests::10000000
contour::default_priority::max_retries::3
contour::high_priority::max_connections::100000
contour::high_priority::max_pending_requests::100000
contour::high_priority::max_requests::10000000
contour::high_priority::max_retries::3
contour::added_via_api::false
contour::192.168.64.1:8002::cx_active::1
contour::192.168.64.1:8002::cx_connect_fail::0
contour::192.168.64.1:8002::cx_total::1
contour::192.168.64.1:8002::rq_active::121
contour::192.168.64.1:8002::rq_error::0
contour::192.168.64.1:8002::rq_success::0
contour::192.168.64.1:8002::rq_timeout::0
contour::192.168.64.1:8002::rq_total::121
contour::192.168.64.1:8002::health_flags::healthy
contour::192.168.64.1:8002::weight::1
contour::192.168.64.1:8002::region::
contour::192.168.64.1:8002::zone::
contour::192.168.64.1:8002::sub_zone::
contour::192.168.64.1:8002::canary::false
contour::192.168.64.1:8002::success_rate::-1
```

But the problem didn't disappear.

And about file descriptors - when we start contour and envoy simultaneously everything works fine. So it's not so clear why we don't hit this limit in this case.

**Comment by Lookyan** [comment]
I found a solution. I'm going to create a patch soon.

**Comment by davecheney** [comment]
Not sure why github won't close this, but it's fixed.
