### ISSUE TITLE
Enable gzip if not already enabled

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#310]
- check it doesn’t come for free (long shot)
- enable it unconditionally for a reasonable set of media types
- (later) add annotation to disable it (probably won’t do, I can’t think of a good reason to want to disable compression)

**Comment by rosskukulinski** [comment]
Envoy added support for a gzip HTTP filter in 1.6: https://github.com/envoyproxy/envoy/issues/269

Moving to 0.7.0 unless someone else has bandwidth to tackle.

**Comment by mattmoyer** [comment]
> (later) add annotation to disable it (probably won’t do, I can’t think of a good reason to want to disable compression)

One reason someone might want to do this is as a blanket mitigation for [BREACH](https://en.wikipedia.org/wiki/BREACH).

**Comment by StarpTech** [comment]
Hi, what's the status? As far I can test gzip is not enabled by default and I also can't find any hint in the docs.

**Comment by jpeach** [comment]
@StarpTech Contour always enables the Envoy gzip filter with the default setting, which are documented [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/gzip_filter).

**Comment by StarpTech** [comment]
@jpeach thanks, I will retest it.
