### ISSUE TITLE
Double check contour grpc cluster circuit breaker limits

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#313]
#309 adjusted the circuit breaker limits for the static `contour` cluster to somewhat arbitrary (but well meaning) values. 

This issue is to track double checking this work and adjusting as necessary.

**Comment by davecheney** [comment]
Bumping to 0.6, nobody has time to look at this now.

**Comment by rosskukulinski** [comment]
Have not heard any complaints or problems with the arbitrary values. Punting to 0.7.

**Comment by davecheney** [comment]
SGTM thank you.

**Comment by davecheney** [comment]
It's been a few releases and nothing has blown up. I'm going to close this issue and re-open iff or when a problem is reported.
