### ISSUE TITLE
write access logs to files

### ISSUE THREAD

**Issue by drobinson123** [heptio/contour#333]
Contour configures Envoy to write access log entries to stdout. Envoy already writes log entries to stdout, and the format is different to access logs. It would be great if Envoy allowed users to control where access log entries were written, and even disable access logs entirely.

My use-case: sending access logs to our internal log management system, for auditing and analytics purposes.

**Comment by davecheney** [comment]
Thanks for raising this issue. Feel free to reopen #328. In principal this sounds ok, but what about the contour logs?

**Comment by davecheney** [comment]
Closed by 815fd4d
