### ISSUE TITLE
Contour @master does not create/delete listeners after startup

### ISSUE THREAD

**Issue by danderson** [heptio/contour#363]
I installed Contour from the README instructions, which installs contour:master. I then installed kuard, which created an Ingress. However, Contour never started listening for HTTP connections (`curl http://192.168.16.240` resulted in "Connection refused", confirmed via `netstat -tnlp` in the pod).

While experimenting, I killed all Contour pods. When the deployment recreated them, the service was immediately functional. This seemed fully repeatable: Contour only creates listeners that match whatever ingresses exist in the cluster at startup, but does not respond to changes to ingresses (addition or deletion).

I reverted to contour:v0.5.0, and on that version everything works perfectly, creating/deleting ingresses results in the correct change to Envoy's listener set.

Reproduction steps:

- Make a cluster with no Ingress resources in it.
- Install Contour per the "Getting Started" in the readme
- Install kuard, again per the readme, which creates an Ingress resource
- Observe that you cannot load kuard via the Contour service IP, you'll get connection refused (or possibly another error depending on the exact LoadBalancer implementation).
- `kubectl delete po -nheptio-contour --all`, and wait for new pods to start.
- Observe that you can now load kuard.

This is with k8s 1.10.2, if that matters.

**Comment by alexbrand** [comment]
Doing a git-bisect seems to point to this commit https://github.com/heptio/contour/commit/8458d6e6475793790ddfb759583cda1daf422e42 as the potential problem.

I did some testing locally with `contour cli lds` and found that removing the `continue` introduced in that commit seems to fix the issue. I wonder if we always have to send a `DiscoveryResponse`, even if the resource list is empty? It is also possible that `contour cli lds` behaves differently than envoy?

**Comment by davecheney** [comment]
Thanks for your bug report. I think the issue is that when there is no filter -- discoveryrequest.resources == "", then contour should always return a response. If there is a filter, then contour should block until there is something matching the filter.
