### ISSUE TITLE
Feature Request: Watch namespace flag

### ISSUE THREAD

**Issue by davidjbrady** [heptio/contour#365]
Howdy

This is just a feature request to expose a flag that allows a user to specify which namespace to watch.

**Comment by davecheney** [comment]
Thanks for raising this issue. Have you checked out ingress classes -- you can ask contour to only listen for a specific ingress class (defaults to `contour` but is configurable) then you can annotate only the ingress records you want to match that ingress class.

**Comment by davidjbrady** [comment]
Thanks Dave, quick response. Yeah, I'm familiar with the the feature and made use of it from time to time, pretty useful :)

The purpose of this feature request for is to fulfill a multi-tenant use case. In which a number of teams isolated by namespaces may wish to use there own ingress controllers for accounting and security reasons... And may all love contour, but are bad at coordinating amongst each other to divy up ingress class names effectively :P

**Comment by davecheney** [comment]
> isolated by namespaces may wish to use there own ingress controllers for accounting and security reasons...

Thanks for explaining. This isn't the use case I had in mind for contour. I expect an ingress controller to be a cluster wide resource.

**Comment by davecheney** [comment]
I’m sorry this issue has been open for so long. Sadly its not something that we’re going to do in the foreseeable future—our view remains that ingress controllers are cluster wide resources.

I’m going to close this issue, but I want to highlight the [`—ingressroute-root-namespaces`](https://github.com/heptio/contour/blob/master/docs/ingressroute.md#restricted-root-namespaces) flag which could be used to implement this. You would have to convince your users to move to Contour’s IngressRoute CRD, and then they would each deploy their own Contour in their own namespace, and restrict it to look for ingressroute documents in said namespace.
