### ISSUE TITLE
Expose /stats path only

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#376]
To gather metrics from Envoy the `/stats` needs to be exposed from the admin interface. If running under host networking all ports are bound to the host IP and network policies are not applicable. 

I'd like to propose we create a static route inside Envoy to expose `/stats` over a configurable port (defaults to `:8001`). Given a standard deployment all L7 traffic would flow through a listener on `:80` or `:443` and stats metrics would flow through `:8001`.

The admin interface is still available via localhost so functionality is not lost.

**Comment by stevesloka** [comment]
That makes a lot of sense. I only did the bootstrap route since it seemed like a static config vs dynamic. Sounds good to revisit and also possibly move the statsd pieces into that logic as well.

**Comment by davecheney** [comment]
@stevesloka @rata if either of you have time to tackle this I'd appreciate it.

**Comment by stevesloka** [comment]
@davecheney I'm trying to figure out a good integration pattern here to implement this. Everything we do is based upon the dag right now. 

- Cluster: My thought was to add values to the ClusterCache by allowing it to have a map of static clusters: (https://github.com/heptio/contour/blob/master/internal/contour/cluster.go#L26). This map would then get added anytime the cache is updated and the dag rebuilt. 
- Route: Same for RouteCache, allowing for a static map lets us build out routes that are not dynamic: https://github.com/heptio/contour/blob/master/internal/contour/route.go#L29

Do you think this approach would work? Or have a different idea?
