### ISSUE TITLE
Error when deploying contour using getting started URL

### ISSUE THREAD

**Issue by awprice** [heptio/contour#384]
When using the "Getting started" URL to deploy contour with RBAC into my cluster, I received the following error:

```
$ kubectl create -f https://j.hept.io/contour-deployment-rbac
namespace "heptio-contour" created
serviceaccount "contour" created
error: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context
```
This is because the rendered YAML is not formed correctly.

I get this error when using both the RBAC and non-RBAC URLs:
- https://j.hept.io/contour-deployment-rbac
- https://j.hept.io/contour-deployment-norbac

**Comment by davecheney** [comment]
Thanks for raising this issue. Which version of k8s are you using? I was able to apply this RBAC configuration to my 1.9.4 (?) cluster without issue, although I was updating an existing configuration.

**Comment by awprice** [comment]
I'm using a 1.9.7 cluster on GKE, tried with both a 1.10 and 1.9.7 client. 

The issue is with the rendered YAML in this file, on line 27:
```
kind: IngressRouteapiVersion: extensions/v1beta1
```
https://raw.githubusercontent.com/heptio/contour/master/deployment/render/deployment-rbac.yaml

The CRD object and the deployment object have been joined together without a `---` separator and a newline to separate them. Once I manually updated the YAML to be in the correct syntax, it worked perfectly.

**Comment by davecheney** [comment]
Thanks, that explains the problem.
