### ISSUE TITLE
Important information missing

### ISSUE THREAD

**Issue by smartpierre** [heptio/contour#385]
Hi !
Thank you for maintaining this great tool !
I am using it on multiple clusters now and it's perfect.

I was creating a new cluster on AWS recently, started to install all my tools **before** my apps.
I installed Contour and the LoadBalancer created by Contour was showing nodes "OutOfService".
I spent days trying to pinpoint why the LB could not do the health check. Checking everything 5 times.

I deployed the example https://raw.githubusercontent.com/heptio/contour/master/deployment/example-workload/kuard.yaml
And to my surprise, LB showed nodes "InService".

I don't see anything in the docs mentioning that Contour must have at least 1 ingress to have a healthy LB.
I understand the logic now, but my first thought was that since Contour is creating the LoadBalancer, then it must take care of the health check. But it's more : Contour doesn't have any ingress, so LB shouldn't be healthy.

Anyway, maybe a small phrase should be added after creating the contour deployment ?
What do you think ?
Best regards.

**Comment by davecheney** [comment]
Hi,

Sorry you were confused by this. This is documented, https://github.com/heptio/contour/blob/master/docs/troubleshooting.md#envoy-container-not-listening-on-port-8080-or-8443, but to be fair, may not have been the right decision.

I don't think any more information can usefully be added to the getting started documentation, it's already too long as it is. The more reasonable alternative would be revisit the existing behaviour.

This will probably happen as part of issues like #376 and #202.

**Comment by smartpierre** [comment]
Indeed it's documented, reading the title it did not look like my issue, but after reading the text, that explain everything !

Thank you for taking the time to answer me, I appreciate it very much :)

I will follow-up on these issues, have a great day Dave.
