### ISSUE TITLE
Revisit decision to make open listeners optional

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#389]
#385 raised the question that the current behaviour of not opening a listener until there is a valid ingress, while justified, is non obvious for newcomers, especially in the case where the AWS elb won’t go green until an ingress is deployed. 

This issue tracks the decision to revert this and potentially always open listeners on 80 and 443. This has implications for security (opening ports we don’t necessarily need which might leak routes unintentionally — defence in depth) and for health checks for contour.

**Comment by davecheney** [comment]
This is not going to be addressed in the 0.7 timeframe.

**Comment by stevesloka** [comment]
The use-case of not having a health check endpoint is now resolved as that exists on a different listener. I think at this point, not creating a listener or returning a 404 since no paths are defined are almost the same UX.

**Comment by davecheney** [comment]
The current behaviour -- contour does not open an accepting socket until there is traffic to serve on that socket will remain the behaviour for contour 1.0.
