### ISSUE TITLE
Envoy fails to connect to Contour when running as separate pods

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#397]
We are running Contour and Envoy in different pods, Contour runs as a `Deployment` and Envoy runs as a `Daemonset`. Also, Envoy is running utilizing `host networking` within the Daemonset.

The issue we are seeing is that some of the Envoy's won't be able to connect to Contour, but some will. If we scale up the number of Contour replicas then it's possible to get all Envoy's to connect. However, if we deploy Envoy as a `Deployment` instead of `Daemonset` via host networking, using the same images, one Contour can support many Envoy's (we tested 20+). 

Here are some logs:
```
[2018-05-14 21:07:04.314][1][warning][upstream] source/common/config/grpc_mux_impl.cc:205] gRPC config stream closed: 1,
[2018-05-14 21:07:04.314][1][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
[2018-05-14 21:07:04.314][1][warning][upstream] source/common/config/grpc_mux_impl.cc:205] gRPC config stream closed: 1,
[2018-05-14 21:07:04.314][1][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
[2018-05-14 21:07:04.314][1][warning][upstream] source/common/config/grpc_mux_impl.cc:205] gRPC config stream closed: 1,
[2018-05-14 21:07:04.314][1][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
```

**Comment by davecheney** [comment]
Thanks for raising this issue. It looks like the gRPC stream (not necessarily the underlying TCP connection) is being closed, but its not clear which side is doing the dirty work. Can you please try to capture the matching logs from Contour.

**Comment by stevesloka** [comment]
Here are some logs from Contour. In this example, I have two replicas of Contour and they both show the same logs.

I did another quick test and putting the Contour pods on the `hostNetwork` does not have the same symptoms. 

I then did a final test by leaving Contour deployed as a `deployment` but exposing it's service as type `NodePort`, then having each Contour connecting to it via that node port (e.g. hostname:port), and have the same errors as connecting to Contour via ClusterIP. 

```
time="2018-05-17T00:46:11Z" level=info msg="args: [serve --incluster --xds-address 0.0.0.0 --xds-port 8001 --envoy-http-port 80]"
time="2018-05-17T00:46:11Z" level=info msg=started context=grpc
time="2018-05-17T00:46:11Z" level=info msg=started context=buffer
time="2018-05-17T00:46:11Z" level=info msg=started context=watch resource=services
time="2018-05-17T00:46:11Z" level=info msg=started context=watch resource=ingressroutes
time="2018-05-17T00:46:11Z" level=info msg=started address="127.0.0.1:8000" context=debugsvc
time="2018-05-17T00:46:11Z" level=info msg=started context=watch resource=endpoints
time="2018-05-17T00:46:11Z" level=info msg=started context=watch resource=ingresses
time="2018-05-17T00:46:11Z" level=info msg=started context=watch resource=secrets
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=1 context=grpc error_detail=nil resource_names="[]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.Cluster version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=1 context=grpc error_detail=nil resource_names="[]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.Cluster version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=4 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg="skipping update" connection=4 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=4 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=2 context=grpc error_detail=nil resource_names="[default/kubernetes/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=2 context=grpc error_detail=nil resource_names="[default/kubernetes/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=5 context=grpc error_detail=nil resource_names="[kube-system/calico-etcd]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=6 context=grpc error_detail=nil resource_names="[gimbal-contour/contour/xds]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=5 context=grpc error_detail=nil resource_names="[kube-system/calico-etcd]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=6 context=grpc error_detail=nil resource_names="[gimbal-contour/contour/xds]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=7 context=grpc error_detail=nil resource_names="[gimbal-contour/contour/xds]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=7 context=grpc error_detail=nil resource_names="[gimbal-contour/contour/xds]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=8 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg="skipping update" connection=8 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=8 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/https]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2018-05-17T00:46:13Z" level=info msg=stream_wait connection=9 context=grpc error_detail=nil resource_names="[gimbal-contour/envoy/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
```

**Comment by davecheney** [comment]
Thanks for the contour logs. There are no "stream terminated" lines which suggests that contour wasn't the one that closed the stream.

Some random suggestions to try:

1. the timestamps between the two log samples don't match up. It would be interesting to see if logs captured concurrently showed "obvious" times for the stream closed errors on the envoy side; 60 seconds, 300 seconds, that sort of thing.
2.  In a previous version of Contour the statsd port listener was accidentally the same port a contour's xds listener; is it possible that traffic indeed for contour is being misrouted to the statsd port?

**Comment by stevesloka** [comment]
Please see attached logs. My environment has 10 nodes in total. Contour is running as a deployment and envoy is running as a daemonset using host networking. I'm using the latest deployments defined here (https://github.com/heptio/gimbal/tree/master/deployment/contour) which shouldn't have the issue of the xds listen port. Also, 2 of the envoy instances connect, so would seem that the port issue wouldn't apply to this scenario. 

[contour1.log](https://github.com/heptio/contour/files/2028354/contour1.log)
[contour2.log](https://github.com/heptio/contour/files/2028355/contour2.log)
[envoy1.log](https://github.com/heptio/contour/files/2028356/envoy1.log)
[envoy2.log](https://github.com/heptio/contour/files/2028357/envoy2.log)
[envoy3.log](https://github.com/heptio/contour/files/2028358/envoy3.log)
[envoy4.log](https://github.com/heptio/contour/files/2028359/envoy4.log)
[envoy5.log](https://github.com/heptio/contour/files/2028360/envoy5.log)
[envoy6.log](https://github.com/heptio/contour/files/2028361/envoy6.log)
[envoy7.log](https://github.com/heptio/contour/files/2028362/envoy7.log)
[envoy8.log](https://github.com/heptio/contour/files/2028364/envoy8.log)
[envoy9.log](https://github.com/heptio/contour/files/2028365/envoy9.log)
[envoy10.log](https://github.com/heptio/contour/files/2028366/envoy10.log)

**Comment by davecheney** [comment]
Thanks for doing the detective work on this Steve.

If you have time, could you post a summary of the policy, how it got there
(if it's a default that might be applied to other clusters), and how it was
resolved then I'll try to update our troubleshooting document to help
others who might find themselves in this condition.

**Comment by stevesloka** [comment]
The policy was written to restrict access to the api's since there's no auth on any of the endpoints. There must be some issue applying that to pods that are on the hostnetwork. We have a PR to remove these from Gimbal (https://github.com/heptio/gimbal/pull/127/files#diff-a27d6bc73b6ebd17f668e8016508e15f)
