### ISSUE TITLE
Default resource limits

### ISSUE THREAD

**Issue by cten** [heptio/contour#409]
The sample deployment should probably have resource limits set. 

Possibly in the future a guide/recommendation for setting limits. 

Thanks to @rosskukulinski these 2 issues might help:
https://github.com/heptio/gimbal/issues/72
https://github.com/heptio/gimbal/pull/122

**Comment by davecheney** [comment]
I agree this would be good. I don't have any bandwidth to work on this.

**Comment by shreyas165** [comment]
Hi @cten, @davecheney,
I am interested in working on this issue. Some details on the resource limits and the scope of the issue would be helpful to get me started. 
Thank you.

**Comment by davecheney** [comment]
@shreyas165 thank you for offering to help. I'm afraid you'll have to do your own research and business analysis on this issue.

**Comment by shreyas165** [comment]
Hi @davecheney , I have worked on test cases but performance testing is a new area for me as well.
Will try analyzing the issue to the best of my knowledge.
Thank you.

**Comment by 2PacIsAlive** [comment]
Hi, is there any guidance yet on setting resource limits for contour?

**Comment by davecheney** [comment]
None yet I’m afraid. Please subscribe to this issue for updates.

**Comment by davecheney** [comment]
Great job! Thanks Steve.
