### ISSUE TITLE
Bootstrap command should log the final config to stdout

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#419]
When troubleshooting issues with envoy, it is sometimes desirable to look at the final configuration that was produced by the contour bootstrap command that is run through an init container.

Normally, one can exec into the envoy container and inspect the configuration file. In certain environments, however, the ability to exec into a container is not available (due to RBAC, for example), and thus it is difficult or impossible to inspect envoy's configuration file. 

As an enhancement to the bootstrap command, we could log the final configuration to stdout so that it can be inspected via `kubectl logs`.

**Comment by davecheney** [comment]
I can see this would be a useful feature, but you can always generate the same bootstrap configuration as your init container by running contour locally. I'm not saying this is _the_ solution to your requirements, but it is an answer you can use today without change.

**Comment by davecheney** [comment]
@alexbrand I had a quick play with trying to solve this with shell but couldn't really get it to work cheaply.

If you need this for your testing, please send a PR and I'll merge it; you can probably do this cheeply without upsetting the tests in internal/envoy like this
```
diff --git a/cmd/contour/bootstrap.go b/cmd/contour/bootstrap.go
index 908161f..68d4e27 100644
--- a/cmd/contour/bootstrap.go
+++ b/cmd/contour/bootstrap.go
@@ -31,7 +31,8 @@ func writeBootstrapConfig(config configWriter, path string) {
        check(err)
        switch filepath.Ext(path) {
        case ".yaml":
-               err = config.WriteYAML(f)
+               mw := io.MultiWriter(f, os.Stdout)
+               err = config.WriteYAML(mw)
                check(err)
        default:
                f.Close()
```

**Comment by shivanshu21** [comment]
I don't see any assignee. Is someone working on this?

**Comment by davecheney** [comment]
I’m sorry there is nobody working on this. When someone is assigned it will be assigned a milestone and an assignee will nominate themselves when they start work.

**Comment by davecheney** [comment]
This will be replaced by #1130
