### ISSUE TITLE
Implement Contour ksonnet library

### ISSUE THREAD

**Issue by hausdorff** [heptio/contour#43]
This is a follow up from our slack conversation some time ago. I'll outline what would be involved in this work and how people would use it.

## Background

A ksonnet library is collected into a set of _parts_ that can be used to configure and deploy an application on Kubernetes for many different scenarios. For example, in [redis][redis], we expose `parts.networkPolicy`, `parts.deployment`, `parts.secret` (for storing the password, if we need one), `parts.pvc` (if we wish to deploy redis backed by a persistent volume), and so on.

We expose a set of pre-fabricated combinations of these parts using _prototypes_, which can be used with `ks generate`. For example, the redis library exposes the following prototypes:

```
io.ksonnet.pkg.redis-all-features
io.ksonnet.pkg.redis-persistent
io.ksonnet.pkg.redis-stateless
```

Each of these uses a subset of the parts exposed by the library. For example, `io.ksonnet.pkg.redis-stateless` uses a deployment, a secret, but does not use a PVC. Using the `ks` tool to generate a fully-formed and functional manifest is as easy as:

```
ks generate io.ksonnet.pkg.redis-stateless lovely-cache --name redis
```

This would generate a file that contains (roughly) the following:

```
{
  kind: "List",
  apiVersion: "v1",
  items: [
    redis.parts.deployment.nonPersistent(namespace, name, name),
    redis.parts.secret(namespace, name, redisPassword),
    redis.parts.svc.metricDisabled(namespace, name),
  ],
}
```

## For Contour

The ultimate goal is that getting started for Contour users should be a couple of commands:

```
$ PATH=$PATH:$GOPATH/bin
$ go get github.com/ksonnet/ksonnet
$ ks init simple-contour && cd simple-contour
$ ks generate com.heptio.pkg.simple-contour contour --name simple-contour [... other flags here ...]
```

To accomplish this, I think we can follow basically the same pattern here:

- [ ] Put the "common" API objects in `deployment/` (_e.g._, the `DaemonSet`, `Deployment`, `NetworkPolicy`, and so on) into a `contour.libsonnet`.
- [ ] Create the rest of the scaffolding a ksonnet library needs -- notably `parts.yaml` folder.
- [ ] Create a set of prototypes that allow users to combine these parts into pre-fabricated "flavors".
  - I'll need your help with deciding which.
- [ ] Publish, either in heptio/contour or in ksonnet/parts.
- [ ] Update documentation.
- [ ] Consider whether to retire the scripts that generate the API objects

## Work for the future

Following this, and out of scope of this issue, is to talk about how we can make it very easy for people to write new apps against the Contour ingress controller. I think it's possible to have a good story there, but I don't think it's purely a question of templating, so we should defer this discussion for later.

[redis]: https://github.com/ksonnet/parts/blob/master/incubator/redis/redis.libsonnet

**Comment by AntonioMeireles** [comment]
(curious)  there's any progress on this ?

**Comment by davecheney** [comment]
@AntonioMeireles not yet I'm afraid.

**Comment by davecheney** [comment]
I'm sorry, this won't be implemented.

**Comment by rosskukulinski** [comment]
FYI - the team behind ksonnet is stepping back from the project: https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/
