### ISSUE TITLE
Rename IngressRoute CRD

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#444]
@jbeda wants to rename the IngressRoute CRD. This is probably a blocker on the 0.6 milestone.

I'm going to assign this to @rosskukulinski and @stevesloka. You have complete veto over changing or not changing the name of the CRD.

**Comment by rosskukulinski** [comment]
@davecheney I'm guessing this came out of the long-range planning meeting you had with @jbeda and @timh?

I believe the proposed rename is `HttpRoute`?  The intent here is to be very specific that the current IngressRoute design is very HTTP centric.  In the future, we may want to support more agnostic TCPProxy like behavior which would require a different CRD with appropriate spec fields.

Does that match up with your understanding?

**Comment by davecheney** [comment]
Ross, contour will not support tcp forwarding, that is outside the remit for an ingress controller. 

Tcp forwarding should be a separate product.

**Comment by rosskukulinski** [comment]
Yes, of course - I should have been more precise with my language.
