### ISSUE TITLE
internal/contour: delay notifications to avoid sending partial configuration

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#445]
From #428 

> A solution to this would be to introduce a "hold off" timer between maintaining a cache of watched objects and regenerating the DAG. A rolling hold off timer of, say, 200ms would restrict the update rate to no more than 5 per second -- which is a reasonable mutation rate -- while not introducing perceptible latency for end users. To avoid the hold off timer holding updates that arrived at a period of slightly less than the 200ms cutoff, an overall timer of, say, 500ms could be instituted.

To avoid sending a partial configuration as it is learned, or during startup, a holdoff period for notifying caches should be instituted.

**Comment by rosskukulinski** [comment]
I'm moving this to the beta.2 milestone as it may be required for https://github.com/heptio/gimbal/issues/72 and/or supporting large numbers of endpoints, services, and ingressroute objects.

**Comment by davecheney** [comment]
SGTM. I have some ideas for how this can be implemented for beta.2. It feels like a two or three day job.

**Comment by davecheney** [comment]
Now only one issue remains for this ticket I'm closing it as a duplicate of #577
