### ISSUE TITLE
ingressroute.spec.virtualhost.name: "" should be illegal

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#447]
It should be illegal to submit an ingressroute spec with a blank fqdn
```
Spec: ingressroutev1.IngressRouteSpec{
                                        VirtualHost: &ingressroutev1.VirtualHost{
                                                Fqdn: "",
                                        },
```
^ Should be rejected. All virtualhosts must have a name.

**Comment by stevesloka** [comment]
The CRD validation in #441 cannot validate since it's only required on a `root` IngressRoute. What should Contour do if this is found? Reject the IngressRoute and set a status on the object?

**Comment by davecheney** [comment]
Yup, we'll reject it.
