### ISSUE TITLE
ingressroute: add support for reporting status

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#449]
During processing of ingressroute documents the status of processing each document should be updated.

Spec: https://github.com/heptio/contour/blob/master/design/ingressroute-design.md#delegation-status

**Comment by stevesloka** [comment]
What versions of Kubernetes are we targeting? If we can use 1.10+ then we should utilize the `Status Subresource` field for this and not use a custom field. @rosskukulinski 

https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/

**Comment by rosskukulinski** [comment]
@stevesloka Currently we're tied to minimum version 1.9. Let me see if that can change.

**Comment by stevesloka** [comment]
The feature is Alpha as well so spec could change in the future.

**Comment by rosskukulinski** [comment]
Ah, in that case let's avoid the Subresource until minimum Beta

**Comment by alexbrand** [comment]
Non-exhaustive list of checks for status reporting:
* Non-numeric weight provided in route definition
* Negative weight provided in the route definition
* Invalid Load Balancing strategy provided
* Route delegates to a non-existent namespace
* Non-root Route that is not pointed to by a Root route
* Prefix in Root does not match route in delegated route

**Comment by davecheney** [comment]
Closed by 3d87eb6f5d60e2976975f6f8cc75f1277b166f44
