### ISSUE TITLE
[tracking] contour on arm64

### ISSUE THREAD

**Issue by vielmetti** [heptio/contour#45]
Tracking issue to identify any issues related to running Contour on arm64, and to report back successes.

**Comment by davecheney** [comment]
Hello,

I don't really want to encourage a practice of opening issues without a specific cause. If its ok with you, would you please close this issue and open specific issues (with details) when or if they occur. 

Thanks

Dave

**Comment by vielmetti** [comment]
OK, I'll close and reopen specific issues (to reference back here if that's OK).

**Comment by davecheney** [comment]
Thank you.
