### ISSUE TITLE
ingressroute.spec.virtualhost.aliases support or drop?

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#451]
Figure out how to add support for virtualhost aliases or drop them from the spec.

**Comment by rosskukulinski** [comment]
@davecheney I don't think this is necessary for the beta.1 milestone, but I _do_ think it should remain in the spec to be implemented for the 0.6 release.

**Comment by alexbrand** [comment]
@rosskukulinski @davecheney should we move this out of the 0.6.0-beta.1 milestone?

**Comment by rosskukulinski** [comment]
Done
