### ISSUE TITLE
internal/dag: ingressroute.spec.virtualhost.tls is not supported

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#458]
Basic, untested, support for building a dag from a ingressroute with a virtualhost is present, but untested

- [ ] add tests for adding an ingressroute and secret to the dag. Existing ingress + secret tests should provide a good template.
- [ ] dag only generates vhost:80 virtualhosts, this needs to be extended to support vhost:443 objects if a virtualhost.tls spec is present.

See also #455 #456

**Comment by rosskukulinski** [comment]
@davecheney TLS not required for beta.1.  I'm happy to move this to a beta.2 or full 0.6 milestone.

**Comment by davecheney** [comment]
ok to bump to 0.6, we can't release to the public without this feature.

**Comment by davecheney** [comment]
Closed by #596
