### ISSUE TITLE
ingressroute: Support enforcing mode

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#461]
Defined in the specification here: https://github.com/heptio/contour/blob/master/design/ingressroute-design.md#enforcing-mode

This will allow for more secure multi-team functionality where Root IngressRoute objects are only read from trusted namespaces

**Comment by alexbrand** [comment]
I thought this would be actionable but I think this is blocked on #448 as we don't have delegation yet.

**Comment by alexbrand** [comment]
In terms of feature yes, I think that is correct. However, given that delegation has not been fully fleshed out yet, I am not sure where this feature would fit in terms of code/architecture. I'll add an item to our sync agenda.

**Comment by davecheney** [comment]
I propose that we do this as a first cut of this feature for beta.1
```
diff --git a/cmd/contour/contour.go b/cmd/contour/contour.go
index 1f00a62..f07d36d 100644
--- a/cmd/contour/contour.go
+++ b/cmd/contour/contour.go
@@ -97,6 +97,11 @@ func main() {
        serve.Flag("use-proxy-protocol", "Use PROXY protocol for all listeners").BoolVar(&t.UseProxyProto)
        serve.Flag("ingress-class-name", "Contour IngressClass name").StringVar(&t.IngressClass)
 
+       var roots []string
+
+       // restricted mode
+       serve.Flag("ingressroute-roots", "Restrict contour to searching for ingress route roots to these namespaces").StringVars(&roots)
+
        args := os.Args[1:]
        switch kingpin.MustParse(app.Parse(args)) {
        case bootstrap.FullCommand():
```
Then plumb `roots` down the dag watcher. 

We can iterate on the UX of setting this field and redeploying contour in a later iteration.
