### ISSUE TITLE
internal/dag: backend field not populated when processing IngressRoute resources

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#462]
The `Route` struct contains a `backend` field that should be  one of `*v1beta1.IngressBackend` or `ingressroute.Service`, depending on whether we are processing a Kubernetes Ingress resource or a Contour IngressRoute resource.

Currently, the `backend` field is not set when processing IngressRoute resources.

(Ran into this while working on #457)

**Comment by davecheney** [comment]
I'll take this one, the backend field is _likely_ needed for determining the port of the child service, however

- routes may have more than one child service, so a singleton backend field doesn't make sense
- if the service object (that implements vertex, not the one from k8s) records the port, then we don't need to keep a copy of the part of the ingress doc that pointed to it on the route to disambiguate which fields of the service document we care about.

I have parts of this already in a git stash, I'll finish it today.
