### ISSUE TITLE
Validate IngressRoute resources and report status

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#490]
When contour is processing IngressRoute resources, it needs to validate that the resource is valid.

The following is an initial list of validations that we should perform:
- [x] Negative weight provided in the route definition
- [x] Invalid port number provided for service
- [x] ~~Invalid Load Balancing strategy provided~~ (This is covered by the CRD validation)
- [x] ~~Route delegates to a non-existent namespace~~ (Delegating to a non-existent namespace or IR does not invalidate the parent)
- [x] Orphaned route
- [x] Prefix in Root does not match route in delegated route
- [x] Delegation chain produces a cycle
- [x] Root IngressRoute created in non-allowed namespace
- [x] A given Route both delegates and has a list of services

Some of these can potentially be done upfront before the resource even hits the DAG. Others will most likely have to be performed while building the DAG.

**Comment by alexbrand** [comment]
Following @davecheney's suggestion from #491, we can tackle this in two takes as follows:

1. Perform validation and log any errors to stdout:
The dag's recompute method will not only return a new dag, but it will also return a slice of validation errors. This will require the introduction of a new type that holds the validation error and the ingressroute that it applies to:
```
package dag
type validationError struct {
    ingressRoute ingressroutev1.IngressRoute
    msg string
}
```

2. Once we have the initial validation working, _something_ will go over the validation errors and update the status field of the corresponding ingressroute resources.

**Comment by alexbrand** [comment]
We further discussed that the recompute method will have to return a list of statuses, instead of a list of validation errors. The reason for this is that we also need to know about the valid ingress routes.

**Comment by alexbrand** [comment]
The following table outlines the conditions, status and messages:

| Condition | Status | Message |
|------|-------|-------|
| valid IR | valid | valid IngressRoute
| Invalid port in service | invalid | route "/foo": service "home": port must be in the range 1-65535
| Root IR defined outside root namespace | invalid | root IngressRoute cannot be defined in this namespace
| prefix does not match parent's prefix | invalid | the path prefix does not match the parent's path prefix
| invalid weight in service | invalid | route "/foo": service "home": weight must be greater than zero
| root IR does not specify FQDN | invalid | Spec.VirtualHost.Fqdn must be specified
| IR delegation produces cycle in dag | invalid | route creates a delegation cycle: roots/self -> roots/self
| IR delegation produces cycle in dag #2 | invalid | route creates a delegation cycle: roots/parent -> roots/child -> roots/parent
| route has a list of services and also delegates | invalid | route "/foo": cannot specify services and delegate in the same route
| ingressroute is orphaned | orphaned | this IngressRoute is not part of a delegation chain from a root IngressRoute

**Comment by stevesloka** [comment]
> invalid weight in service

You should be able to define a service with a weight of zero. 

> prefix does not match parent's prefix

Is this one just orphaned?

**Comment by alexbrand** [comment]
Thanks @stevesloka! Updated the message for weights. The implementation was correct, but the message was not.

> prefix does not match parent's prefix
In my mind, it is not the same as an orphaned route, as it _is_ part of a delegation path from a root ingressroute. In other words, there is a parent that is pointing to it by name + namespace.

**Comment by alexbrand** [comment]
Update:
The following validations were stricken through from the list today:
- Invalid Load Balancing strategy provided: This is covered by the CRD validation that is performed by the API server. 
- Route delegates to a non-existent namespace: Delegating to a non-existent namespace or IngressRoute should not invalidate the parent. However, we should probably update the parent's status to let the owner know that something isn't quite right. Opened #510
