### ISSUE TITLE
ingressroute: loadbalancer strategy and healthcheck params misplaced

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#503]
From #498 

> At the moment the _services (terrible name, sorry) map is keyed by a tuple of namespace/name/port; so the same k8s service will result in two different service objects in the dag if a route points to two different ports on the same service. https://github.com/heptio/contour/blob/master/internal/contour/cluster_test.go#L220

> Arguably lbstrat and healthcheck params are properties of the service namespace/name/port tuple. I think I can argue that for the latter, why would the a service have two different ways of checking its health depending on which routes point to it. I could probably make the same argument for lbstrat. If that argument holds then those properties should be defined on the k8s service object via annotations, and incorporated into the dag.Service object -- which means they are not part of the _service's map key.

> However, because we currently define lbstrat and hc on the ingressroute object, it is possible to have more than one way to point to a single k8s service with different values for those parameters. So, what we should probably do in that case is make lbstrat and healthcheck params properties of the route so when the cds visitor is building the cds table it knows to emit distinct cluster values for each cluster depending on the path it took to reach that vertex.

> However, this argument is problematic because if a route has multiple service children, does that mean we need to store an array of healthcheck and lbstrat configurations on the Route object? The ingressroute document lets us define a different hc and lbstrat per service so we need to store and map an array of hc/lbstrat values in the route object to the route objects children.

> This is the same situation I found myself in when doing RDS, a ingressroute Route can have multiple service name / port pairs. But the child of a dag.Route was a k8s Service object, which can have multiple ports defined. Said another way, the ingressroute Route servicename field gave us the k8s service object to wrap in a dag.Service and insert into the graph, but it didn't contain enough information for the routeVisitor to recover the port details of the child dag.Service. The first solution I tried was to create a map of ports to children in the route object, but that was brittle. The better solution was to create a distinct dag.Service for a service name and port combination. This also matched the envoy Cluster model.

For 0.6 final we need too either:

a. create an intermediary object to hold cluster weights between the Route and the Service. The CDS walker will detect this and obtain the weights from the intermediary object.
b. Move the definition of the lbstrat and healthcheck params to annotations on the k8s service object

**Comment by rosskukulinski** [comment]
Not totally clear on the difference between this and #581, but keeping in 0.6.0 milestone.

**Comment by davecheney** [comment]
@rosskukulinski i'd prefer to keep this issue open. #581 won't address this issue, we'll just work around it.

**Comment by davecheney** [comment]
I'm going to move this to 0.7. 

This issue is a discussion on whether the lb/hc properties should be specified as keys on the route in the ingressroute object (which is how they are today in 0.6) or if they should be specified as _annotations_ on the k8s service object that the route points too. 

I think I can make an argument for the latter case, but 

a. that's more annotations on the service object 🤢
b. this doesn't take into account synthetic service objects generated by the gimbal discoverers when working with foreign openstack clusters. 

We could address b. through #515 at a later date.

Personally I think we need to define a new L7 service object for k8s in the same way ingressroute has been defined. But that is out of scope for the near future.

**Comment by davecheney** [comment]
This is done #1031
