### ISSUE TITLE
Validate that services have consistent load balancing strategies and health checks across all IngressRoutes

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#514]
The load balancing strategy and health check parameters are specified at the route, instead of at the service. Thus, we need to make sure that all routes that reference a certain service are using the same load balancing strategy and health check configuration.

**Comment by stevesloka** [comment]
This is very similar to #581 and should be addressed in the fix for that issue since it's describing `weights` but lbStategies and health checks fall in to the same problem space.

**Comment by rosskukulinski** [comment]
Marking as a dup of #591
