### ISSUE TITLE
Refactor and improve dag's processIngressRoute function

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#521]
The current implementation of the processIngressRoute function works, but it takes a rather long list of parameters. Most of these parameters can actually live on a struct given that they are either accumulating results or remaining unchanged while recursing.

**Comment by davecheney** [comment]
I'm going to move this up to beta.2, i have a feeling that we're going to be spending a lot of time in that code over the next month and this change is either going to fall out of a refactoring naturally, or we're going to frustrated with it enough that we'll just do the work.
