### ISSUE TITLE
Support inbound http/1.0 requests

### ISSUE THREAD

**Issue by yob** [heptio/contour#537]
Hi, thanks for a great tool. We're using contour in production and love the flexibility it provides.

We're noticed that contour 0.5 (and envoy 1.6.0) doesn't support inbound http/1.0 requests:

```
$ curl -v -0 http://example.com/health
> GET /health HTTP/1.0
> Host: example.com
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 426 Upgrade Required
< date: Tue, 10 Jul 2018 12:44:58 GMT
< server: envoy
< content-length: 0
```

```
$ curl -v http://example.com/health
> GET /health HTTP/1.1
> Host: example.com
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< x-content-type-options: nosniff
< content-length: 15
< x-envoy-upstream-service-time: 2
< date: Tue, 10 Jul 2018 12:49:05 GMT
< server: envoy
< 
{"status":"ok"}
```

This isn't a deal breaker for us, but we're building an API product and expect at least some of our clients may attempt a http/1.0 request and it'd be nice to send them a 301 to a TLS URL.

I notice that envoy 1.6.0 added support for http/1.0 requests (https://github.com/envoyproxy/envoy/issues/170) but I haven't been able to find a way to enable it via contour. Am I missing a config option?

**Comment by davecheney** [comment]
Thank you for raising this issue. TBH I'll have to refresh myself on the nuances of HTTP/1.0 requests and how they differ from HTTP/1.1. This looks like a pretty simple feature to add, and I think if its possible, we'll just turn it on for everyone.

One wrinkle that might come up, and i'm sketchy on the details because its' been so long, is the handling of the `Host:` header in http/1.0, something which might interact weirdly with Ingress's notion of the default vhost or ingress.

**Comment by yob** [comment]
Thanks. As I say, it's not a deal breaker for us - I just wanted to capture the issue as a "nice to have". 

Maybe it'll even save others a bit of research time if they wonder why `ab` tests don't work on a contour service (like I did.....)

**Comment by fraenkel** [comment]
Just need to tweak the envy config:
see https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#core-http1protocoloptions

**Comment by fraenkel** [comment]
One way is off a cluster, set the http_protocol_options or did I miss something?

**Comment by davecheney** [comment]
I’m honestly not sure, the original issue was envoy returning a 426 when it got a http/1.0 request. I haven’t dug into it at all, but it feels to me that this processing would happen before the request got to the point of choosing a cluster.

**Comment by fraenkel** [comment]
The other way is off the connection_manager which is a network filter, but I haven't figured out where that comes into play.

**Comment by davecheney** [comment]
That’s where I’m thinking the change probably needs to sit.

**Comment by fraenkel** [comment]
You have the http_connection_manager already in the current config, now you just need to know when/what to set the http1 protocol config.

**Comment by rosskukulinski** [comment]
We should get this in, but it's not essential for 0.6.0 which is focused on wrapping up remaining IngressRoute CRD work.
