### ISSUE TITLE
SSL Redirect

### ISSUE THREAD

**Issue by jhernandezb** [heptio/contour#55]
Hi,

Actually my ELB is configured to handle the SSL stuff, and its working fine but I want to enforce https when hitting the url. It will be awesome if contour could support ```ingress.kubernetes.io/force-ssl-redirect: "true"``` like NGINX does. [see here](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/tls.md#server-side-https-enforcement-through-redirect)

**Comment by davecheney** [comment]
Duplicate of #63
