### ISSUE TITLE
Improve root-ingressroute-namespaces configuration

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#560]
For 0.6, defining which namespaces are [allowed to create](https://github.com/heptio/contour/blob/master/docs/ingressroute.md#restricted-root-namespaces) root ingressroute objects is defined using a `--ingressroute-root-namespaces` CLI flag to contour.  Currently this must be defined once per allowed namespace, though #540 will allow comma-separated definition of namespaces.

Updating the list of namespaces requires rolling an update to the Contour Deployment, which is a bit drastic for production deployments.

Contour should support a mechanism to dynamically update the list of allowed root namespaces without restarting the Contour process or rolling an update to the Deployment.

One option would be to have Contour monitor a list of allowed namespaces defined within a ConfigMap (either via k8s API or mounted via filesystem).

A more complex, but more flexible option would be to implement a policy CRD that tracked this information.

**Comment by davecheney** [comment]
Closed, won't fix. Now we have split deployment, contour's lifetime is decoupled from the envoys it manages so there is less cost in updating the list of root ingressroutes.
