### ISSUE TITLE
internal/e2e: make e2e tests use workgroup

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#573]
The e2e tests have their own home grown goroutine manager. Can they use github.com/heptio/workgroup?

**Comment by rosskukulinski** [comment]
@davecheney I don't fully understand the nuances of this issue.  Is this important tech-debt to pay down for the 0.6.0 cycle?  Ok to slip to another release?

**Comment by rosskukulinski** [comment]
Sounds good

**Comment by vaamarnath** [comment]
I thought the work was to migrate the existing goroutines invocations to `heptio/workgroup`. I apologise for for raising the PR #892 without discussing with you @davecheney. It's my bad! 

Can you please provide some insights into what is the scope of work for this issue?

**Comment by davecheney** [comment]
I think its better to close this issue. There are other more important issues.
