### ISSUE TITLE
Disable panic threshold

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#579]
When setting healthchecks on an upstream, the panic threshold might confuse users: https://www.envoyproxy.io/docs/envoy/v1.6.0/intro/arch_overview/load_balancing#panic-threshold

The default is 50%, but we should disable it for now.

**Comment by davecheney** [comment]
I suggest setting it to 100% or whatever kicks out backends which fail their health check. That seems the easiest to document and is pretty defensible; if you fail your helthcheck we won’t even talk to you til you start passing again.

**Comment by rosskukulinski** [comment]
@davecheney I'm on board with completing this for beta.2

**Comment by rosskukulinski** [comment]
For this milestone, we will disable this feature in envoy.

For a future release, we might consider making this configurable.  @stevesloka would you mind opening a separate issue for making this configurable? [Or move this to 0.6.0 and open a new one for hardcoding]

**Comment by nwohlgemuth** [comment]
> For this milestone, we will disable this feature in envoy.
> 
> For a future release, we might consider making this configurable.

Is there any plan to make this setting configurable?

**Comment by davecheney** [comment]
@nwohlgemuth we don’t tend to track closed issues. Would you be so kind as to open a new feature request.
