### ISSUE TITLE
internal/contour: make HoldoffNotifier delay constants configurable

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#592]
#577 introduced a HoldoffNotifier type which is hard coded to a 100ms/500ms delay. This makes it unsuitable for use with our e2e tests so it is not currently used in the e2e path.

Investigate making the holdoff delays fields on the HoldoffNotifier itself and possibly use smaller values in the e2e tests.

**Comment by alexbrand** [comment]
Started looking into this. The challenge here I think is getting it wired into the e2e tests. If we make the delay > 0, it seems like we will have to make our tests assert multiple times with a timeout, and somehow have access to the delay and maxDelay params to know what value to use as timeout. 

Open to ideas if there's a better approach here.

**Comment by davecheney** [comment]
If this is hard then skip it, testing timeouts is messy. I’d prefer to test the hold off notifier in isolation.

**Comment by rosskukulinski** [comment]
I think this is worth resolving for 0.6 to pay down tech debt.

**Comment by rosskukulinski** [comment]
@davecheney I'm +1 for that -- Reading back over the thread I realize now there are more important things to tackle.

**Comment by rosskukulinski** [comment]
moved to 0.7

**Comment by davecheney** [comment]
Removing milestone, this is moderate tech debt, but I don't think qualifies for a planned release.

**Comment by andrewsykim** [comment]
Opened a PR for this here https://github.com/heptio/contour/pull/927

**Comment by davecheney** [comment]
Closing. The need to configure these constants is not important enough.
