### ISSUE TITLE
Switch from Dep to go modules

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#598]
Requires #597

https://go-review.googlesource.com/c/go/+/124384 introduces support for a `v8.0.0+incompatible` annotation in the `go.mod` file which should provide a bridge between semver dependencies and go 1.11 Semantic Import Versioning requirement. This will let us update `go.mod` without having to wait for `k8s.io/client-go` to rewrite the repository.

**Comment by davecheney** [comment]
Removing milestone, #691 is not going to happen for 0.7 and we might skip Go 1.11 completely.

**Comment by davecheney** [comment]
Revisit after #848

**Comment by davecheney** [comment]
This issue is open for anyone who wants to try it.

**Comment by vaamarnath** [comment]
I can pick it up @davecheney

**Comment by vaamarnath** [comment]
I have chosen to vendor the dependencies using `go mod vendor`. I have made the changes accordingly.
