### ISSUE TITLE
Contour does not delete IngressRoute metrics even after IngressRoute has been deleted

### ISSUE THREAD

**Issue by yutaokaz** [heptio/contour#611]
I found that Contour set IngressRoute metrics to 1 even if IngressRoute is deleted. I expected Contour does not return IngressRoute metrics about deleted IngressRoute.

I tried as bellow.
1. I create IngressRoute and confirm Contour create metrics: `contour_ingressroute_total{namespace}`  and set it to 1.
2. I delete IngressRoute, but metrics: `contour_ingressroute_total{namespace}` is still alive and set to 1.

I think this issue is caused by not initializing variables in `Metrics.SetIngressRouteMetric()`. And now I think Contour should initialize IngressRoute metrics variables before call `Metrics.SetIngressRouteMetric()` when updating metrics.

**Comment by rosskukulinski** [comment]
Ha! I also just opened #612.  These may be related.

**Comment by rosskukulinski** [comment]
Closing as duplicate of #612 which @stevesloka is already working on.
