### ISSUE TITLE
Unique fqdn validation does not consider aliases

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#626]
The validation added to ensure that a single fqdn is only referenced in a single IngressRoute does not take into consideration the fqdns mentioned in the aliases field. Thus, it is currently possible to define conflicting IngressRoutes. For example, creating an IngressRoute with fqdn = `example.com`, and another IngressRoute with an fqdn alias = `example.com`.

Related #625

**Comment by davecheney** [comment]
Closed as #642 removed support for aliases entirely.
