### ISSUE TITLE
Option to add X-Request-Start header to incoming requests

### ISSUE THREAD

**Issue by yob** [heptio/contour#646]
Some tracing applications support reporting on queuing time for incoming requests. Generally this is implemented by adding a `X-Request-Start` timestamp header to the requests as early as possible in the request path.

[New Relic](https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples) and [datadog](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#http-request-queuing) are two examples of tools that support this header.

It'd be great if there was a way to configure contour/envoy to add `X-Request-Start`.

The latest envoy docs [have an example that looks relevant](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#custom-request-response-headers), but I'm not sure there's a way to control that option via contour.

**Environment:**

- Contour version: 0.5.0
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP

**Comment by davecheney** [comment]
I like this. Ideally i'd like to see this enabled for all hosts rather than another knob that someone has to know to enable. If enough people complain we can talk about a knob to disable this on a per vhost basis.
