### ISSUE TITLE
retry-on, num-retries, and per-try-timeout support lost

### ISSUE THREAD

**Issue by williamhuangh** [heptio/contour#665]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

added `contour.heptio.com/num-retries`, `contour.heptio.com/retry-on` and `contour.heptio.com/per-try-timeout` to ingress object, and logs have no indication of retrying on 5xx timeouts

**What did you expect to happen:**

retry logs on 5xx timeouts, evidence in logs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Noticed that this issue was opened, "fixed", and closed https://github.com/heptio/contour/issues/485 but the code here was deleted and never added back in https://github.com/heptio/contour/commit/2a2a31a0d4df21bbe23948f129218046d16da949#diff-8233a03a118982ca5f389d6f03933517

These are now the supported annotation: https://github.com/heptio/contour/blob/master/internal/dag/annotations.go#L30-L36
which are inconsistent with the docs https://github.com/heptio/contour/blob/master/docs/annotations.md#contour-specific-ingress-annotations

**Environment:**

- Contour version: 0.6.0beta.2
- Kubernetes version: (use `kubectl version`): 1.10.6
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Fedora 28

**Comment by davecheney** [comment]
oops, this is my bad. I will make sure this is fixed before 0.6 is released.

**Comment by davecheney** [comment]
@williamhuangh I checked and the timeout properties are extracted from an annotation here

https://github.com/heptio/contour/blob/master/internal/dag/builder.go#L298

and applied to the object few lines later. I'm going to add some e2e tests to make sure they are being properly applied

**Comment by davecheney** [comment]
Well, this is embarrassing. It turns out that functionality never had any tests ... i'm fixing this now.
