### ISSUE TITLE
internal/dag: remove builder.Remove tests

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#667]
Remove the builder.Remove tests from builder_test.go, they're not adding anything now we always build a fresh dag from scratch. The e2e tests give us enough coverage for remove at a higher level.

**Comment by Atul9** [comment]
@davecheney I have opened up a PR for this #671

**Comment by davecheney** [comment]
@Atul9 thanks for offering to help, there are a set of tests in internal/contour/builder_test.go related to the `builder.Remove` method. Those are no longer needed and should be removed.

**Comment by Atul9** [comment]
@davecheney I read the code for `Remove` method where in case of `cache.DeletedFinalStateUnknown`for an object type the `Remove` method is called recursively.
 how to identify those set of tests which are no longer needed in `TestDAGRemove` method in builder_test.go?

**Comment by davecheney** [comment]
The goal of this issue is to remove TestDAGRemove. Sorry I should have made
that clearer in the original issue.

**Comment by davecheney** [comment]
Thank you, i'll review this in a week or so when we start the 0.7 cycle. I don't want to merge it now because I'm trying to close off the remaining 0.6 issues.
