### ISSUE TITLE
internal/contour: CDS Load Balancer Strategy field should always have a value

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#679]
At the moment the `type.googleapis.com/envoy.api.v2.Cluster.lb_strategy` field is allowed to be blank if no valid strategy has been provided.

We should ensure that this value is always present using a default that Contour controls.

**Comment by pickledrick** [comment]
Is this already defaulted in [](https://github.com/heptio/contour/blob/master/internal/contour/cluster.go#L190)?

**Comment by davecheney** [comment]
Thanks for confirming. Closing.
