### ISSUE TITLE
Implement cluster.alt_stats_name 

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#689]
Currently per cluster statistics are emitted with the name of the cluster. Prior to #581 this would be the pseudo name `namespace/name/portnum`. After #581, the pseudo name is `namespace/name/portnum/hash`. 

We can use [cluster.alt_stats_name][0] to normalise the reporting of statistics to the namespace,name,portnum tuple, or even to the namespace,name tuple.

[0]: https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v2/api/v2/cds.proto#cluster

**Comment by davecheney** [comment]
Note to implementers; doing this work is straight forward, but please do not proceed without a clear decision on the format of the alternative name for statistics.

**Comment by seancrwhite** [comment]
Hi there, is anyone currently looking at this? I'd like to contribute and think this would be a good place for me to start.

**Comment by davecheney** [comment]
@seancrwhite got for it; but please get agreement from @rosskukulinski and @alexbrand on the format for the name before sending a PR. Thanks.

**Comment by seancrwhite** [comment]
@davecheney will do!

**Comment by seancrwhite** [comment]
@rosskukulinski @alexbrand upon review I think namespace_name_portnum would be the best naming convention for these stats. Thoughts?

**Comment by rosskukulinski** [comment]
@seancrwhite I'm on board with that naming convention

**Comment by davecheney** [comment]
Too late for 0.8. Please feel free to send a PR and mark it for review in 0.8
