### ISSUE TITLE
Metrics update

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#718]
Since Contour has been updated to use Envoy v1.7.X, we should be able to remove the prometheus_forwarder container which was used to gather metrics from Envoy's statsd interface. 

Additionally, we should be able to use the Prometheus interface path and remove the annotation `prometheus.io/format: "prometheus"`. 

Full testing will need to be done as well as the Histograms (which are new in this release) to validate for functionality.

**Comment by stevesloka** [comment]
In Envoy 1.7, histograms aren't exposed to Prometheus yet. Will need to wait for a newer version of Envoy.

**Comment by rosskukulinski** [comment]
https://github.com/envoyproxy/envoy/issues/1947

**Comment by rata** [comment]
This is fixed, IIUC, with:

 * e52f96e8e3efda172f514d26883b1dae422ca915 for usage of the Prometheus interface path and remove the annotation `prometheus.io/format: "prometheus"`.

* a8c69837746088e084952d9dfbb6238d3143a74f: Upgrade to envoy 1.10, as envoy 1.10 includes histograms

Also, just in case, documentation is updated here too: https://github.com/heptio/contour/pull/1085

So, I think it is safe to close this one :)

**Comment by davecheney** [comment]
@stevesloka i’m pretty sure we’ve covered off all of this over the last three releases. Would you be able to confirm and either close this issue or move it to 0.14 with a note about the work remaining.

**Comment by stevesloka** [comment]
Yup good to close! 🎉
