### ISSUE TITLE
Contour should support JWT validation

### ISSUE THREAD

**Issue by fkpwolf** [heptio/contour#748]
**Describe the solution you'd like**
should support JSON Web Token (JWT)  validation

**Anything else you would like to add:**
Since Envoy has supported JWT validation, can Contour add this feature easily? https://github.com/kubernetes/ingress-nginx/issues/1850 Ingress Nginx need extra effort to support this since it should support "Allow custom Lua snippets" at first.

**Comment by davecheney** [comment]
Can you please explain what JWT validation does? Is it something that should be handled by the proxy layer or is it something better handled at the application later?

**Comment by fkpwolf** [comment]
JWT token in HTTP header is used to check if a request has been authorized or not. k8s used it a lot. Yes, it can be handled by application also, but API gateway like Kong treats it as part of middle layer with other feature like logging and monitoring.

**Comment by stevesloka** [comment]
Similar to https://github.com/heptio/contour/issues/432

**Comment by fkpwolf** [comment]
close as duplicated with #432
