### ISSUE TITLE
AWS NLB doc incorrect

### ISSUE THREAD

**Issue by dlaidlaw** [heptio/contour#757]
The documentation at https://github.com/heptio/contour/blob/master/docs/deploy-aws-nlb.md says:

> We then set up an NLB to point to all of the nodes that Contour is running on. This cannot be done currently through Kubernetes. The AWS cloud provider only knows how to create classic ELBs.

This is incorrect. The NLB has been available as a LoadBalancer type for a while now, since 1.9 I believe. It is done by adding the annotation: `service.beta.kubernetes.io/aws-load-balancer-type` See the source code: https://github.com/kubernetes/kubernetes/blob/release-1.9/pkg/cloudprovider/providers/aws/aws.go#L96

The documentation should be updated to reflect this.

**Comment by davecheney** [comment]
Thanks for the correction. I'll update the documentation.

**Comment by rochacon** [comment]
It is important to mention that Service LoadBalancer with NLB does not support all control annotations yet, such as [health check interval](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L389-L400), so if using the NLB through Service you may need to tweak the `terminationGracePeriod` of Contour to achieve zero downtime rollouts.

**Comment by davecheney** [comment]
I’m not in a position to verify this change. PRs improving the NLB documentation greatly appreciated
