### ISSUE TITLE
Prometheus annotation points to port 9001 but Envoy binds to 8002

### ISSUE THREAD

**Issue by rochacon** [heptio/contour#766]
**What steps did you take and what happened:**

I was trying to setup Prometheus metric collection for Envoy and Contour, however after setting the format scrape rule Prometheus was still marking the target as `DOWN`. After checking the generated envoy configuration I've noticed that the Envoy `/stats` path was bind to port 8002 instead of 9001 (the one in the `prometheus.io/port` annotations).
After changing the annotation to point to port 8002 Prometheus was able to collect Envoy metrics without issues.

**What did you expect to happen:**

Prometheus should be able to collect metrics by following the documented `prometheus.io/port` annotation.

**Anything else you would like to add:**

I had proxy protocol enabled, so I'm not sure if this was related to it or not.
I'm also not sure if this is just a documentation issue or actually an unexpected behavior.

**Environment:**

- Contour version: 0.6.1
- Kubernetes version: (use `kubectl version`): 1.10.9
- Kubernetes installer & version: kops
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): CoreOS Stable 1855.4.0

**Comment by rosskukulinski** [comment]
@stevesloka could you take a look at this?

**Comment by stevesloka** [comment]
Hey @rochacon thanks for raising this. A bit of history, we had `9001` as the default port but switched because it conflicted with the default admin Envoy port. We since changed it but forgot to update the example deployment files. 

I opened up #772 to fix.

**Comment by rochacon** [comment]
@stevesloka cool, I thought in opening the PR from the start but wanted to confirm the issue. Thank you for the fix.
