### ISSUE TITLE
Link broken in "TLS support" doc

### ISSUE THREAD

**Issue by harper1011** [heptio/contour#795]
**What steps did you take and what happened:**
In "[TLS support"](https://github.com/heptio/contour/blob/master/docs/tls.md#tls-support) documentation page, a link is broken which lead to 404 page not found
The broken link is: "YAML v2 bootstrap configuration."

**What did you expect to happen:**
The link should point to proper documentation page

**Comment by davecheney** [comment]
Thanks for spotting that. I'll get it fixed for 0.8
