### ISSUE TITLE
Provision ALB on AWS ?

### ISSUE THREAD

**Issue by praveenchandran** [heptio/contour#801]
Hi Everyone,

Can I provision an ALB instead of Classic or Network load balancer on AWS. If yes, what would be the correct annotations for it?

Thank you.

**Comment by davecheney** [comment]
Closing as answered

**Comment by tirelibirefe** [comment]
> Hi Everyone,
> 
> Can I provision an ALB instead of Classic or Network load balancer on AWS. If yes, what would be the correct annotations for it?
> 
> Thank you.

Good approach and very good question, here is the answer:

1) install and consifure aws-load-balancer controller.
2) set envoy service as "nodeport" not loadbalancer. 
3)Create an ingress for envoy nodeport service and confiure it based on alb controller specific settings like ssl. 
That would create and ALB and terminate ssl requests alb level. That configuration also makes possible waf of aws.

**Comment by praveenchandran** [comment]
Thanks @tirelibirefe! 
I was looking for some native support, to provision the ALB, from contour itself. I ended up doing something similar to what you suggested. I exposed the contour service as nodeport and instead of using an ingress controller to provision the ALB, I provisioned it via terraform and I have more control over the configurations like Bucket logging, WAF association, Cert management etc..

**Comment by tirelibirefe** [comment]
Hello,
Nice...
This approach which is terminating ssl at LB level is ignored in all design considerations of Contour, I don't know why. On the other hand it's very important consideration WAF usage on cloud. 

I believe  LB level SSL termination must be considered in design concepts and reference architectures by Contour.

**Comment by youngnick** [comment]
@tirelibirefe, thanks for that. In general we encourage users to bring SSL down to Contour for two reasons:
- to avoid traffic being unencrypted on the hop between the external LB and Contour
- to allow Contour to use the SNI for traffic routing.

Would you be able to log a separate issue with your use case though? Then we can discuss it there.
