### ISSUE TITLE
Restrict namespaces the secret watcher operates in

### ISSUE THREAD

**Issue by robbiemcmichael** [heptio/contour#816]
Contour currently has to be configured with the ability to [watch secrets across all namespaces](https://github.com/heptio/contour/blob/master/internal/k8s/watcher.go#L59) which it uses to be able to handle TLS termination for the virtual hosts.

Since Contour can be configured to [restrict which namespaces are allowed to have root IngressRoutes](https://github.com/heptio/contour/blob/master/docs/ingressroute.md#restricted-root-namespaces), it should also be able to register watchers in these specific namespaces to minimise the privileges it requires to run.

**Comment by davecheney** [comment]
This is a good suggestion. I think we can adjust the secret watcher if
root-namespaces is enabled.

**Comment by rosskukulinski** [comment]
This seems like a good idea.  We won't be able to dynamically update the RBAC configuration, but this feature would allow users to proactively lock down the permissions and still have contour function properly.

**Comment by davecheney** [comment]
Restricting this issue to only watching secrets from namespaces if `root-namespaces` is enabled is tentatively scheduled for 0.15.

note to implementors: this will interact with TLS certificate delegation. That interaction must be documented and agreed here before starting work.
