### ISSUE TITLE
Enabling EC2 ELB PROXY protocol support with Classic ELB breaks HTPS

### ISSUE THREAD

**Issue by wadeholler** [heptio/contour#817]
**What steps did you take and what happened:**
Installed via "Get Started"
Followed instructions for TLS enablement and EC2 ELB PROXY protocol support
Connectivity to a subsequently created ingress target over https faulted TLS negitiation.

Example:
```bash
ubuntu@ip-10-42-1-190:~$ openssl s_client -connect tempingress.homewsc.net:443 -servername tempingress.homewsc.net
CONNECTED(00000003)
140160867645080:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 337 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1543255466
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**What did you expect to happen:**

Expected TLS connectivity to work for the ingress

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 0.8
- Kubernetes version: (use `kubectl version`): 1.12.2
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): ubuntu and centos

**Comment by davecheney** [comment]
Thanks for raising this issue. Can you please show the `kubectl -o yaml` output of the contour service document. I want to see where in out documentation the bug is.

**Comment by davecheney** [comment]
Timed out, please reopen if you feel this is in error.
