### ISSUE TITLE
Ajax GET requests being cached

### ISSUE THREAD

**Issue by afayes** [heptio/contour#824]
**What steps did you take and what happened:**
I am testing out contour ingress controller with ingress route resource for my application. I can see that AJAX requests have an expires header to set to 2 hours in the future. However, this has broken my application. After issuing an AJAX delete request to delete a data item, a subsequent GET request is issued but because of caching it gets the old list of data

**What did you expect to happen:**
Request should not be cached unless otherwise configured to be cached explicity.

**Environment:**

- Contour version: Not sure how to get version. I can see images being used are: gcr.io/heptio-images/contour:master and docker.io/envoyproxy/envoy-alpine:v1.7.0
- Kubernetes version: 1.10
- Kubernetes installer & version: I used amazon EKS to set up kubernetes cluster
- Cloud provider or hardware configuration: AWS - Amazon EKS
- OS (e.g. from `/etc/os-release`): local machine is a mac, kubernetes is set up using Amazon EKS

**Comment by davecheney** [comment]
Thanks for your issue. As far as I know envoy does not have a caching facility. Can you please provide some more detail, curl -v would be perfect.

**Comment by afayes** [comment]
My app is currently running here: http://ae7626db1f32f11e8a03b0e8108d4e9d-1460728722.us-east-1.elb.amazonaws.com

**Comment by afayes** [comment]
my kubernetes depoyment files content is:
`apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  labels:
    app: computer-service
  name: kuard
  namespace: default
spec: 
  virtualhost:
    fqdn: ae7626db1f32f11e8a03b0e8108d4e9d-1460728722.us-east-1.elb.amazonaws.com
  routes: 
    - match: /
      services: 
        - name: computer-ui
          port: 80
    - match: /api
      services: 
        - name: computer-service
          port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: computer-service
  labels:
    app: computer-service
    group: computer-service
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: computer-service
---
apiVersion: v1
kind: Service
metadata:
  name: computer-ui
  labels:
    app: computer-ui
    group: computer-service
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: computer-ui
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: computer-service
  labels:
    app: computer-service
    group: computer-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: computer-service
  labels:
    app: computer-service
    group: computer-service
spec:
  selector:
    matchLabels:
      app: computer-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: computer-service
    spec:
      containers:
      - image: afayes/computer-service-k8s
        name: computer-service
        env:
         - name: SPRING_DATASOURCE_URL
           value: jdbc:h2:file:/app/data/computer-service-db
         - name: ALLOWEDORIGINS
           value: "http://www.abulfayes.com"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: computer-service
          mountPath: /app/data
      volumes:
      - name: computer-service
        persistentVolumeClaim:
          claimName: computer-service
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: computer-ui
  labels:
    app: computer-ui
    group: computer-service
spec:
  selector:
    matchLabels:
      app: computer-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: computer-ui
    spec:
      containers:
      - image: afayes/computer-ui-k8s
        name: computer-ui
        ports:
        - containerPort: 80
          name: http

`

**Comment by afayes** [comment]
curl output:
` curl -v http://ae7626db1f32f11e8a03b0e8108d4e9d-1460728722.us-east-1.elb.amazonaws.com/api/v1/computers
*   Trying 34.237.104.167...
* TCP_NODELAY set
* Connected to ae7626db1f32f11e8a03b0e8108d4e9d-1460728722.us-east-1.elb.amazonaws.com (34.237.104.167) port 80 (#0)
> GET /api/v1/computers HTTP/1.1
> Host: ae7626db1f32f11e8a03b0e8108d4e9d-1460728722.us-east-1.elb.amazonaws.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
< Date: Wed, 28 Nov 2018 21:53:48 GMT
< x-envoy-upstream-service-time: 6
< Server: envoy
< Expires: Wed, 28 Nov 2018 23:53:48 GMT
< Transfer-Encoding: chunked
< 
* Connection #0 to host ae7626db1f32f11e8a03b0e8108d4e9d-1460728722.us-east-1.elb.amazonaws.com left intact
[]`

**Comment by afayes** [comment]
You can see in the curl response, the header: Expires: Wed, 28 Nov 2018 23:53:48 GMT
This causes the browser to cache the result but should not. There is nothing in my app that adds this header. I do not think Amazon's load balancer is adding it, the only other place that it is being added is the ingress controller

**Comment by davecheney** [comment]
Thank you for the explanation. I’ll do some investigating.

**Comment by davecheney** [comment]
How far in the future was that expires header for you ? (Time zones are hard)

**Comment by afayes** [comment]
2 hours ahead

**Comment by davecheney** [comment]
Hmm, that does look auto generated. My suspicion is this is being added by the gzip compression filter we added in 0.7. 

I’ll have a hunt for the culprit next week.

**Comment by afayes** [comment]
Cool

**Comment by davecheney** [comment]
@afayes i'm not able to reproduce the problem. Here is my test instance running on GKE
```
% curl -v https://httpbin.davecheney.com/ip
*   Trying 35.189.26.87...
* TCP_NODELAY set
* Connected to httpbin.davecheney.com (35.189.26.87) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=httpbin.davecheney.com
*  start date: Nov  5 23:39:00 2018 GMT
*  expire date: Feb  3 23:39:00 2019 GMT
*  subjectAltName: host "httpbin.davecheney.com" matched cert's "httpbin.davecheney.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /ip HTTP/1.1
> Host: httpbin.davecheney.com
> User-Agent: curl/7.62.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: envoy
< date: Mon, 10 Dec 2018 01:52:40 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-credentials: true
< content-length: 29
< x-envoy-upstream-service-time: 3
<
{
  "origin": "10.152.0.3"
}
* Connection #0 to host httpbin.davecheney.com left intact
```
How have you deployed contour in your environment? Are you using an ELB?

**Comment by davecheney** [comment]
@afayes ping. Are you able to update the issue. Thanks.

**Comment by afayes** [comment]
Not sure why I was having the issue.
