### ISSUE TITLE
IngressRoute delegation use cases?

### ISSUE THREAD

**Issue by kidlj** [heptio/contour#840]
except for...

- server aliases
- blue/green deployments

I'm wondering if there are more use cases or reasons for this design?  Thanks.

**Comment by glerchundi** [comment]
@kidlj for me the use-cases are security related concerns:
* access control based on kubernetes namespaces.
* tls secrets on the edge namespace and path management on another.

**Comment by davecheney** [comment]
@kidlj thanks for your question; the best answers are probably found in the blog posts the Contour team have made 

- https://blog.heptio.com/improving-the-multi-team-kubernetes-ingress-experience-with-heptio-contour-0-6-55ae0c0cadef
- https://blog.heptio.com/flexible-software-deployment-patterns-with-ingressroute-a49a43253992

Additionally I made a presentation to the GDG Melbourne chapter last November about the challenges the current k8s Ingress object presents, and how we're addressing them in IngressRoute.

- https://dave.cheney.net/paste/ingress-is-dead-long-live-ingressroute.pdf

**Comment by kidlj** [comment]
@glerchundi @davecheney Thanks.
