### ISSUE TITLE
Support regex in Ingress `spec.rules.http.paths.path` field

### ISSUE THREAD

**Issue by alvaroaleman** [heptio/contour#841]
**What steps did you take and what happened:**

I tried to use a regex (`/.*`) in `spec.rules.http.paths.path` of an Ingress which should work [according to the upstream go docs](https://github.com/kubernetes/kubernetes/blob/f83bb59047b1de54dd24ca629da4598917f4f283/pkg/apis/extensions/types.go#L189). It resulted in a 404 from envoy:

```
$ curl https://my-tld/hello-world -i
HTTP/2 404 
date: Tue, 01 Jan 2019 15:55:13 GMT
server: envoy
```

**What did you expect to happen:**

The same as what currently happens when using just `/` in the `path` value, a rule that catches all traffic except if there is another path with a narrower match.

**Anything else you would like to add:**

Not sure if of relevance, but the discussion around this emerged here: 
https://github.com/kubernetes/test-infra/pull/10441#discussion_r244493962

**Environment:**

- Contour version: `v0.8.0`
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.4", GitCommit:"0c81dc1e8c26fa2c47e50072dc7f98923cb2109c", GitTreeState:"clean", BuildDate:"2018-12-07T00:22:06Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by davecheney** [comment]
@alvaroaleman thanks for raising this issue. Tbh supporting regexes as advertised in the ingress spec is complicated because the ingress spec defines a specific flavour of regex which neither the nginx or envoy ingress data planes support.

In Contour we try to detect if the path spec is a regex, and switch from prefix matching to regex matching. 

For the regex you specified, you can replace it with `/` and it will achieve the same thing.

**Comment by yob** [comment]
We're haven't tried using regex paths yet, but we're interested.

> In Contour we try to detect if the path spec is a regex, and switch from prefix matching to regex matching

For clarity - does this mean regex paths are an option in contour today (0.10)?

**Comment by davecheney** [comment]
@yob they are supported, sorta, in the k8s ingress object. There is no regex support in IngressRoute.

**Comment by davecheney** [comment]
I'm going to close this issue the OP's question was answered a long time ago.

If you find a bug with regex support k8s Ingress, please raise a bug, we'll try to fix it.

If you would like regex support ingressroute, please raise a bug.

**Comment by yob** [comment]
cheers
