### ISSUE TITLE
Deployment of v0.8.1 fails to start envoy 

### ISSUE THREAD

**Issue by wadeholler** [heptio/contour#842]
**What steps did you take and what happened:**
Attempted to upgrade to v0.8.1 - however I just followed the Main README.md instructions on adding contour to my cluster.  With the following tweaks:

appearent envoy error:

```
[2019-01-02 15:52:47.316][1][critical][main] source/server/server.cc:80] error initializing configuration '/config/contour.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:: invalid name endpoint: Cannot find field.): {"endpoint":"/healthz","pass_through_mode":false}
```

updated with our private registry target
updated with annotation for internal ELB
changed contour:master to contour:v0.8.1

**What did you expect to happen:**

Contour to deploy and run the contour pods successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v0.8.1
- Kubernetes version: (use `kubectl version`): 1.13.0
- Kubernetes installer & version: custom / kubeadm
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by stevesloka** [comment]
Hey, @wadeholler I did some digging in this. If you use the `master` tag of Contour everything will work fine. I think it's related to the envoy go-control-plane updates that came out since the `v0.8.1` tagged release. 

I think we could build a `v0.8.2` to get a tagged release that works with Envoy `v1.8.0`. What do you think @davecheney?

In the meantime, you could use Envoy `v1.7.0` with Contour `v1.8.1` if you need a quick fix (that's what I was running previously).

**Comment by davecheney** [comment]
Hi,

The expected use case is Contour 0.8.x uses Envoy 1.7.0. Contour 0.9. will use Envoy 1.8.0. If Contour 0.8.x is not broken with Envoy 1.7.0 we probably won't backport support for Envoy 1.8.0.

**Comment by wadeholler** [comment]
Thanks all. I thought I was doing a good thing by setting Contour to a
release instead of master in deployment. This cluster isn’t prod yet but it
will be at the end of the month. Sorry I caused you extra work and
investigation. I’ll roll envoy back to 1.7.0 when using contour 0.8.X.

Thanks again.

/close

**Comment by davecheney** [comment]
Thanks @wadeholler. I'm sorry the process isn't smoother, Envoy is evolving pretty quickly and so the version of contour is pretty closely tied to the version of Envoy.

At the moment this dependency is expressed in the deployment manifests we ship with each release branch, https://github.com/heptio/contour/blob/release-0.8/deployment/deployment-grpc-v2/02-contour.yaml#L29, but I'd like to make this better in the future -- although I'm not immediately sure what that will entail.
