### ISSUE TITLE
Upgrade to Go 1.12

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#848]
Upgrade to Go 1.12 for Contour 0.10.x

**Comment by davecheney** [comment]
Go 1.12 might make it across the line before March, but it's too risky to schedule this upgrade for 0.10

**Comment by Avni-Sharma** [comment]
Can I take this up?

**Comment by davecheney** [comment]
Yes, please send a PR once the 0.11 cycle opens (and go 1.12 has been released)

**Comment by davecheney** [comment]
Fixed by #904
