### ISSUE TITLE
Port support for retry-oriented annotations to IngressRoute objects

### ISSUE THREAD

**Issue by scottslowe** [heptio/contour#863]
**Describe the solution you'd like:**
Per https://github.com/heptio/contour/blob/master/docs/annotations.md, Contour supports retry-oriented annotations for Ingress objects; however, it does not appear that Contour supports these same annotations for IngressRoute objects. Customers are requesting support for these retry-centric annotations for IngressRoute objects as well.

**Environment:**
This would apply to any supported environment.

- Contour version: N/A
- Kubernetes version: (use `kubectl version`): Any supported version
- Kubernetes installer & version: Any supported version
- Cloud provider or hardware configuration: Any supported platform
- OS (e.g. from `/etc/os-release`): Any supported OS

**Comment by davecheney** [comment]
I believe we delivered this in Contour 0.12.
