### ISSUE TITLE
Switch from proto.struct to proto.any configuration for bootstrap configuration

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#876]
go-control-plane v0.6.4 (?) introduced a new way of specifying opaque filter config; rather than a proto.struct, use a proto.any. Both can be constructed by encoding an gRPC proto message, but the former involves an icky conversion via jsonpb.

The latter should give us more type safety -- we avoid using the jsonpb/struct hack in internal/envoy by constructing struct types directly, which is no better than the previous mechanism of using text/template. 

Switching to the config_any mechanism should give us more insulation from the changes to the grpc data types.

Blocked on:

- [x] #999 
- [x] https://github.com/envoyproxy/go-control-plane/issues/175

**Comment by vaamarnath** [comment]
@davecheney I am willing to pick this work. I would love if you could give me some direction on how to proceed with this work. 
I have gone through the code in `internal/contour/config.go` which has the template `yamlConfig`. I saw that it is used to create the yaml configs. Though, I didn't see where `WriteYAML()` is being invoked to understand the execution flow. Is it invoked from the envoy for configuring itself? For fixing this issue, is the requirement to change this implementation to protobuf using proto.any?

**Comment by davecheney** [comment]
This issue is already assigned, please choose another.

**Comment by davecheney** [comment]
Bumping til 0.12. @vaamarnath you're welcome to work on this, but please not until the 0.12 cycle.

**Comment by davecheney** [comment]
As far as I can see this is complete, all filter configurations are using TypedConfig.

**Comment by davecheney** [comment]
Opps, one more. Will send a final PR
