### ISSUE TITLE
Split Contour and Envoy containers into their own pods

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#881]
This ticket describes a long term plan to change the default mechanism for deploying Contour.

Currently the default deployment for Contour colocates a contour process and an envoy container in the same pod. This is convenient, envoy can talk over the container loopback to contour for its configuration, but it is not the only way to deploy contour. For instance Gimbal deploys contour and envoy in their own pods; one as a deployment, the other as a daemonset. This is the mechanism I want to move towards as the default way of deploying Contour. Specifically

- Contour is deployed as a classic deployment
- Envoy is deployed as a daemonset

This change would deliver the following benefits

- We no longer need one Contour per Envoy, this will reduce load on the API server. Ideally I would like to deploy only one Contour and rely on the kubelet's restart mechanism to handle upgrades and outages of the control plane. If this were achieved then it would avoid the need for leader election when updating status, and possibly mitigate status update loops like #854 
- Upgrades and configuration changes to Contour's deployment would not affect the Envoy pods, this would address issues where a change to Contour's flags causes a rolling drop of all traffic in flight across envoy's because the kubelet kills all the containers in the pod during reload.
- If configuration changes to the control plane no longer caused data plane outages, this would reduce the need to move contour's configuration into a configmap. The configmap being a way to hold changing configuration data which contour would have to watch and learn to reconfigure itself without exiting. This means contour doesn't need to watch config maps, and we avoid having to teach contour to restart itself internally, a procedure which will surely lead to bug reports in the field. 
- The crash of a contour process would no longer cause its sibling enovy to be killed.

This proposal is not without downside

- Currently the traffic between envoy and contour is not secured as we rely on the container loopback address. This would require an encrypted and authenticated channel between contour and envoy. #862 

This change would not remove the ability for users to deploy contour colocated with envoy in the same pod. We're just not going to push it as the default option any more.

**Comment by so0k** [comment]
Based on the docs we are running contour in it's own deployment and using the Kube injected Environment variables for envoy to get xds config from contour. As highlighted in this issue, it seems the downside to this deployment is unsecured communication between envoy and contour in the kube cluster... this is not really highlighted in the docs

perhaps I could do a PR to the docs to add a caveat regarding the communication?

side note, couldn't we use mTLS from istio to secure communication between envoy and contour until this feature gets added?

**Comment by davecheney** [comment]
Rather than fixing the docs I want to make the communication between contour and envoy secure. 

This is a high priority item for me.

**Comment by davecheney** [comment]
This is urgent, but blocked on #898. Moving to 0.12

**Comment by youngnick** [comment]
With the merge of #1203, Phase 1 of this ticket is now complete. Remaining phases:
- Phase 2: Improve the UX - this will be fixed by #1215, and was originally covered by #1184, but the design fell out of work on #862 
- Phase 3: Currently covered by #1185 for design.

**Comment by davecheney** [comment]
Merging into #1185
