### ISSUE TITLE
Contour fails to assemble proper DAG for tls-based endpoints

### ISSUE THREAD

**Issue by joshrosso** [heptio/contour#887]
**What steps did you take and what happened:**
I previously validated https://github.com/heptio/contour/pull/866. It has since been superseded by https://github.com/heptio/contour/pull/886. During validation of https://github.com/heptio/contour/pull/886, the DAG for my HTTPS endpoint no longer attached to the service.

In this validation, Contour runs as a `daemonset` on nodes with the label `node-role.kubernetes.io/ingress=`. Contour's container ports (`8080`,`8443`) are configured to hostPorts (`8080`,`8443`) respectively. This is the same configuration used to validate https://github.com/heptio/contour/pull/866.

## Testing Steps

1. Deploy the kuard.io example with tls.

    ```
    kubectl apply -f https://gist.githubusercontent.com/joshrosso/a48cad2023065e29e6213c35ca989d98/raw/15ea28496b954f276b73d46aff5688f48bf1441c/kuard.yaml
    ```

2. Deploy known good Contour (version `0.9.0`).

    ```
    kubectl apply -f https://gist.githubusercontent.com/joshrosso/ad62107b950b2c839ebb98ebcf366e31/raw/903b77120bd369c313c41525fc42a02a18341c03/contour-0.9.0.yaml
    ```

3. Request kuard.io with `-H 'Host: kuard.io:443'` to trick envoy.

    ```
    curl -v -H 'Host: kuard.io:443' https://kuard.io:8443 -k
    ```

4. Verify the response is `200`.

5. Delete the Contour (`0.9.0`) daemonset.

    ```
    kubectl delete -f https://gist.githubusercontent.com/joshrosso/ad62107b950b2c839ebb98ebcf366e31/raw/903b77120bd369c313c41525fc42a02a18341c03/contour-0.9.0.yaml
    ```

6. Deploy the Contour (`joshrosso/contour:0.10-j.1`) daemonset, built off https://github.com/heptio/contour/commit/7618aeb67b323d7e372d3738940028f61c295ccc.

    ```
    kubectl apply -f https://gist.githubusercontent.com/joshrosso/ba6d2ec32e290538239c0bbff417afb2/raw/2cd2ced4319c382dc42aeae9bad1cc0f8d84380f/contour-0.10.0.yaml
    ```

    > This includes the flag modifications described in https://github.com/heptio/contour/pull/886.

7. Request kuard.io with `/etc/hosts` trickery.

    ```
    curl -v https://kuard.io:8443 -k
    ```

8. Verify the response is `404`.

    ```
    < HTTP/2 404
    < date: Tue, 12 Feb 2019 03:42:35 GMT
    < server: envoy
    ```

## Differences

Aside from images, the only manifest differences in `0.9.0` and `joshrosso/contour:0.10-j.1` are as follows.

```
@@ -180,8 +180,10 @@ spec:
         args:
         - serve
         - --incluster
-        - --envoy-http-port=8080
-        - --envoy-https-port=8443
+        - --envoy-external-http-port=8080
+        - --envoy-external-https-port=8443
+        - --envoy-service-http-port=8080
+        - --envoy-service-https-port=8443
       - image: docker.io/envoyproxy/envoy-alpine:v1.9.0
         name: envoy
         ports:
```

Exporting the DAG, you can see the following difference between Contour versions.

`0.9.0`:

![image](https://user-images.githubusercontent.com/6200057/52610336-c17c8200-2e4e-11e9-8c6b-914edd007705.png)

`joshrosso/contour:0.10-j.1`:

![image](https://user-images.githubusercontent.com/6200057/52610347-c6d9cc80-2e4e-11e9-960f-92004826f181.png)

**What did you expect to happen:**

While not familiar with Contour's DAG, I'd expect it to be similar to:

![image](https://user-images.githubusercontent.com/6200057/52610440-2041fb80-2e4f-11e9-9684-3776bc853c43.png)

Otherwise I'm misunderstanding how to configure Contour relative to how it was in https://github.com/heptio/contour/pull/866.

/cc @davecheney @stevesloka

**Comment by davecheney** [comment]
Confirmed. Thanks @joshrosso. The bug looks like its related to the `--envoy-external-http-port=8080 --envoy-external-https-port=8443` flags

**Comment by joshrosso** [comment]
I validated this today with a build at https://github.com/heptio/contour/commit/e07ca4a96c647c7f383ac47c1c60852f3dc2b044. The DAG is being built correctly.
