### ISSUE TITLE
TCP port forwarding

### ISSUE THREAD

**Issue by Nefelim4ag** [heptio/contour#891]
Add a CRD or ConfigMap for tcp port forward.

We can't use Ingress Route for all our services (some of them not use http & etc),
so we currently use haproxy for tcp port forwarding from K8s.

K8s 1.12+
Linux
Several local baremetal setups

May be i misunderstood documentation and contour already can do that.

Thanks.

**Comment by davecheney** [comment]
Thank you for raising this issue.

Contour can do TCP forwarding when the TCP stream is encapsulated in TLS. This is currently implemented only in IngressRoute, we haven't backported it do Ingress.

You can mix and match Ingress and IngressRoute objects in a k8s cluster using Contour. 

Can you please tell me more about your requirements, perhaps there is something that can be done to satisfy them.

**Comment by Nefelim4ag** [comment]
As example, we expose rtmp.
Some times Postgres & etc app specific things. All without ssl.

**Comment by davecheney** [comment]
Thank you for your reply. At the moment contour needs TLS encapsulation to use the SNI handshake message to direct the connection to the correct backend service. Without this encapsulation the only way I know to separate the different TCP streams is to assign each service it its own tcp port. You mentioned that in your environment you are using bare metal, so I'm guessing you're using your own firewall or similar to direct traffic into your k8s cluster, why not just send the traffic directly to the services you needed, and cut contour out of the loop?

**Comment by Nefelim4ag** [comment]
@davecheney, sorry for long answer

Yep, we have firewall, but it between external networks & cluster, so it know nothing.

We use currently:
internet - external firewall -  K8s(VIP/VRRP - Haproxy/Ingress - SVC - Pod)

Thanks.

**Comment by Nefelim4ag** [comment]
Another example, currently K8s kubectl use SPDY for exec.
So envoy can't pass exec to API server.

**Comment by davecheney** [comment]
If you need raw tcp forwarding to a service on a bare metal cluster I suggest something like MetalLB. That operates at Layer 3.

**Comment by davecheney** [comment]
Thank you for raising this issue. I am going to close it because it is outside the scope of Contour's requirements. Contour is an L7 http reverse proxy, this is somewhat complicated by our support for L4 TCP+TLS proxying, but this does not make Contour a generic L3 TCP firewall. I think you would be better served by using a different product for your cluster.

**Comment by pschichtel** [comment]
Adding this just because I found this via Google and haven't found any other explicit statements: This would be covered using contour's Gateway API support, specifically using TCPRoute.
