### ISSUE TITLE
IngressRoute: Control backend idle timeout

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#894]
Contour should provide a way to control how long connections between Envoy and a k8s service are kept open after the request has completed.

**Comment by bpicolo** [comment]
@davecheney This seems like a necessary configuration option right now in order to support gRPC streaming connections, they currently drop as idle connections fairly quickly it seems.

I'm unsure if there's an idle time for <client> -> <envoy>, but that would probably need to be exposed as well?

**Comment by phylake** [comment]
One suggestion here: there's a notable lack of support for parsing duration as strings (in Go, not contour). I think that led to some [interesting value overloading](https://github.com/heptio/contour/blob/v0.9.0/internal/dag/dag.go#L64-L68) that could be resolved with a pointer to a custom `type Duration`

In `apis/contour/v1beta1/ingressroute.go` I added the following

```golang
type Duration struct {
	time.Duration
}

func (recv Duration) MarshalJSON() ([]byte, error) {
	return json.Marshal(recv.String())
}

func (recv *Duration) UnmarshalJSON(bs []byte) (err error) {
	var iface interface{}

	if err = json.Unmarshal(bs, &iface); err != nil {
		return
	}

	switch value := iface.(type) {
	case float64:
		recv.Duration = time.Duration(value)
	case string:
		recv.Duration, err = time.ParseDuration(value)
	default:
		err = errors.New("invalid duration")
	}
	return
}
```

And added this
```diff
diff --git a/apis/contour/v1beta1/ingressroute.go b/apis/contour/v1beta1/ingressroute.go
index 26ff2a2..fe2fa02 100644
--- a/apis/contour/v1beta1/ingressroute.go
+++ b/apis/contour/v1beta1/ingressroute.go
@@ -127,6 +127,8 @@ type Route struct {
 	HashPolicy []HashPolicy `json:"hashPolicy,omitempty"`
 
 	PerFilterConfig map[string]interface{} `json:"perFilterConfig,omitempty"`
+
+	IdleTimeout *Duration `json:"idleTimeout,omitempty"`
 }
 
 // TCPProxy contains the set of services to proxy TCP connections.

```

This allowed for a few nice things imo
1. It establishes a well-defined precedent in IngressRoute. Only [`HealthCheck.TimeoutSeconds`](https://github.com/heptio/contour/blob/v0.9.0/apis/contour/v1beta1/ingressroute.go#L116) would need changed internally. I didn't look to see if it would be backward-compatible
1. As a user I can specify a more intuitive duration (e.g. `60s`) and assume that if no value is provided then a sensible default was given (in the case of idle timeout anyway)
1. The semantics (nil pointer, pointer to a zero value, pointer to an actual value) match 1:1 w/ the [ultimate destination](https://github.com/envoyproxy/go-control-plane/blob/v0.6.1/envoy/api/v2/route/route.pb.go#L1375) of the field

/cc @jcrowthe

**Comment by davecheney** [comment]
Duplicate of #944. Closing
