### ISSUE TITLE
Provide way to configure port that Envoy listens on

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#9]
Right now envoy is locked to 8080 and contour is 8000. This is fine with pod networking but may not be great with host networking.

**Comment by dungeonmaster18** [comment]
Hi @davecheney , I would like to work on this issue if you can guide me through this. I am completely new here.

**Comment by davecheney** [comment]
Duplicate of #48

**Comment by davecheney** [comment]
@dungeonmaster18 thanks for your offer of help. The first step should be to write up either in the issue (#48) a high level design of what needs to change inside contour to implement this feature, and how you plan to test these changes. Once there is agreement that the approach is reasonable, it's time to code.
