### ISSUE TITLE
upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by sgonzalezO** [heptio/contour#908]
**What steps did you take and what happened:**
I don't know if this a bug or it's something I'm doing wrong.

We have deployed a wordpress web site on GKE and we are using Heptio Contour as our Ingress controller to our deployment. Sometimes, when we request a web page, we can see the error "upstream connect error or disconnect/reset before headers" on the browser. If we hit the F5 key several times, the web page suddenly appears. We don't see any error on the Apache web logs

**What did you expect to happen:**
The requested web page is rendered the right way.

**Anything else you would like to add:**
Can some one point me out how to debug this error?. I tried using "Troubleshooting" from the project with no luck.

**Environment:**
Google Kubernetes Engine

- Contour version: Contour v0.9.0

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.6", GitCommit:"144b681e3870074abfdaaf176e48b1b13360d7e5", GitTreeState:"clean", BuildDate:"2019-02-09T00:08:19Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: Using GKE

- Cloud provider or hardware configuration: GKE (1.11.7-gke.6)
- OS (e.g. from `/etc/os-release`): GKE node version: 1.11.7-gke.6

Thanks in advance.

**Comment by davecheney** [comment]
Thank you for raising this issue.

The "upstream connect error or disconnect/reset before headers" message is usually because the backend pod disconnected immediately, or envoy had a stale IP address as the pod moved elsewhere.

Can you please do `kubectl get endpoint $YOURSERVICE -w` and check if the endpoint document is being updated frequently.

If you have access to the envoy admin interface via the troubleshooting documentation, can you please post the output of the /clusters page.

**Comment by sgonzalezO** [comment]
This is the endpoint output (about 15 mins waiting): 

> (master)💰  date
jueves, 28 de febrero de 2019, 16:47:41 WET
(master)💰  kubectl get endpoints wordpress-service -w
NAME                ENDPOINTS                                   AGE
wordpress-service   10.48.1.7:80,10.48.1.7:3306,10.48.1.7:443   99d
^C
(master)💰  date
jueves, 28 de febrero de 2019, 17:00:20 WET

We have only one wordpress Pod. Usually it's on the same node all the time and changes when we update the Cluster.

Those are /cluster page outputs:
> monitoring/prometheus-grafana-service/3000/da39a3ee5e::default_priority::max_connections::1024
monitoring/prometheus-grafana-service/3000/da39a3ee5e::default_priority::max_pending_requests::1024
monitoring/prometheus-grafana-service/3000/da39a3ee5e::default_priority::max_requests::1024
monitoring/prometheus-grafana-service/3000/da39a3ee5e::default_priority::max_retries::3
monitoring/prometheus-grafana-service/3000/da39a3ee5e::high_priority::max_connections::1024
monitoring/prometheus-grafana-service/3000/da39a3ee5e::high_priority::max_pending_requests::1024
monitoring/prometheus-grafana-service/3000/da39a3ee5e::high_priority::max_requests::1024
monitoring/prometheus-grafana-service/3000/da39a3ee5e::high_priority::max_retries::3
monitoring/prometheus-grafana-service/3000/da39a3ee5e::added_via_api::true
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::cx_active::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::cx_connect_fail::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::cx_total::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::rq_active::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::rq_error::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::rq_success::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::rq_timeout::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::rq_total::0
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::health_flags::healthy
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::weight::1
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::region::
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::zone::
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::sub_zone::
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::canary::false
monitoring/prometheus-grafana-service/3000/da39a3ee5e::10.48.10.3:3000::success_rate::-1
service_stats::default_priority::max_connections::1024
service_stats::default_priority::max_pending_requests::1024
service_stats::default_priority::max_requests::1024
service_stats::default_priority::max_retries::3
service_stats::high_priority::max_connections::1024
service_stats::high_priority::max_pending_requests::1024
service_stats::high_priority::max_requests::1024
service_stats::high_priority::max_retries::3
service_stats::added_via_api::false
service_stats::0.0.0.0:0::cx_active::2
service_stats::0.0.0.0:0::cx_connect_fail::0
service_stats::0.0.0.0:0::cx_total::2
service_stats::0.0.0.0:0::rq_active::0
service_stats::0.0.0.0:0::rq_error::0
service_stats::0.0.0.0:0::rq_success::18630
service_stats::0.0.0.0:0::rq_timeout::0
service_stats::0.0.0.0:0::rq_total::18630
service_stats::0.0.0.0:0::health_flags::healthy
service_stats::0.0.0.0:0::weight::1
service_stats::0.0.0.0:0::region::
service_stats::0.0.0.0:0::zone::
service_stats::0.0.0.0:0::sub_zone::
service_stats::0.0.0.0:0::canary::false
service_stats::0.0.0.0:0::success_rate::-1
monitoring/prometheus-server-service/9090/da39a3ee5e::default_priority::max_connections::1024
monitoring/prometheus-server-service/9090/da39a3ee5e::default_priority::max_pending_requests::1024
monitoring/prometheus-server-service/9090/da39a3ee5e::default_priority::max_requests::1024
monitoring/prometheus-server-service/9090/da39a3ee5e::default_priority::max_retries::3
monitoring/prometheus-server-service/9090/da39a3ee5e::high_priority::max_connections::1024
monitoring/prometheus-server-service/9090/da39a3ee5e::high_priority::max_pending_requests::1024
monitoring/prometheus-server-service/9090/da39a3ee5e::high_priority::max_requests::1024
monitoring/prometheus-server-service/9090/da39a3ee5e::high_priority::max_retries::3
monitoring/prometheus-server-service/9090/da39a3ee5e::added_via_api::true
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::cx_active::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::cx_connect_fail::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::cx_total::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::rq_active::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::rq_error::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::rq_success::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::rq_timeout::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::rq_total::0
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::health_flags::healthy
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::weight::1
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::region::
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::zone::
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::sub_zone::
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::canary::false
monitoring/prometheus-server-service/9090/da39a3ee5e::10.48.10.3:9090::success_rate::-1
contour::default_priority::max_connections::100000
contour::default_priority::max_pending_requests::100000
contour::default_priority::max_requests::60000000
contour::default_priority::max_retries::50
contour::high_priority::max_connections::100000
contour::high_priority::max_pending_requests::100000
contour::high_priority::max_requests::60000000
contour::high_priority::max_retries::50
contour::added_via_api::false
contour::127.0.0.1:8001::cx_active::1
contour::127.0.0.1:8001::cx_connect_fail::0
contour::127.0.0.1:8001::cx_total::1
contour::127.0.0.1:8001::rq_active::10
contour::127.0.0.1:8001::rq_error::0
contour::127.0.0.1:8001::rq_success::0
contour::127.0.0.1:8001::rq_timeout::0
contour::127.0.0.1:8001::rq_total::10
contour::127.0.0.1:8001::health_flags::healthy
contour::127.0.0.1:8001::weight::1
contour::127.0.0.1:8001::region::
contour::127.0.0.1:8001::zone::
contour::127.0.0.1:8001::sub_zone::
contour::127.0.0.1:8001::canary::false
contour::127.0.0.1:8001::success_rate::-1
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::default_priority::max_connections::1024
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::default_priority::max_pending_requests::1024
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::default_priority::max_requests::1024
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::default_priority::max_retries::3
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::high_priority::max_connections::1024
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::high_priority::max_pending_requests::1024
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::high_priority::max_requests::1024
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::high_priority::max_retries::3
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::added_via_api::true
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::cx_active::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::cx_connect_fail::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::cx_total::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::rq_active::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::rq_error::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::rq_success::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::rq_timeout::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::rq_total::0
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::health_flags::healthy
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::weight::1
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::region::
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::zone::
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::sub_zone::
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::canary::false
monitoring/prometheus-alertmanager-service/9093/da39a3ee5e::10.48.10.3:9093::success_rate::-1
default/svc-firma/80/da39a3ee5e::default_priority::max_connections::1024
default/svc-firma/80/da39a3ee5e::default_priority::max_pending_requests::1024
default/svc-firma/80/da39a3ee5e::default_priority::max_requests::1024
default/svc-firma/80/da39a3ee5e::default_priority::max_retries::3
default/svc-firma/80/da39a3ee5e::high_priority::max_connections::1024
default/svc-firma/80/da39a3ee5e::high_priority::max_pending_requests::1024
default/svc-firma/80/da39a3ee5e::high_priority::max_requests::1024
default/svc-firma/80/da39a3ee5e::high_priority::max_retries::3
default/svc-firma/80/da39a3ee5e::added_via_api::true
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::cx_active::0
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::cx_connect_fail::0
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::cx_total::1
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::rq_active::0
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::rq_error::0
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::rq_success::2
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::rq_timeout::0
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::rq_total::2
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::health_flags::healthy
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::weight::1
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::region::
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::zone::
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::sub_zone::
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::canary::false
default/svc-firma/80/da39a3ee5e::10.48.1.2:80::success_rate::-1
default/procesos-iso2k-service/80/da39a3ee5e::default_priority::max_connections::1024
default/procesos-iso2k-service/80/da39a3ee5e::default_priority::max_pending_requests::1024
default/procesos-iso2k-service/80/da39a3ee5e::default_priority::max_requests::1024
default/procesos-iso2k-service/80/da39a3ee5e::default_priority::max_retries::3
default/procesos-iso2k-service/80/da39a3ee5e::high_priority::max_connections::1024
default/procesos-iso2k-service/80/da39a3ee5e::high_priority::max_pending_requests::1024
default/procesos-iso2k-service/80/da39a3ee5e::high_priority::max_requests::1024
default/procesos-iso2k-service/80/da39a3ee5e::high_priority::max_retries::3
default/procesos-iso2k-service/80/da39a3ee5e::added_via_api::true
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::cx_active::0
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::cx_connect_fail::0
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::cx_total::2
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::rq_active::0
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::rq_error::0
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::rq_success::2
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::rq_timeout::0
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::rq_total::2
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::health_flags::healthy
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::weight::1
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::region::
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::zone::
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::sub_zone::
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::canary::false
default/procesos-iso2k-service/80/da39a3ee5e::10.48.1.3:80::success_rate::-1
default/wordpress-service/80/da39a3ee5e::default_priority::max_connections::1024
default/wordpress-service/80/da39a3ee5e::default_priority::max_pending_requests::1024
default/wordpress-service/80/da39a3ee5e::default_priority::max_requests::1024
default/wordpress-service/80/da39a3ee5e::default_priority::max_retries::3
default/wordpress-service/80/da39a3ee5e::high_priority::max_connections::1024
default/wordpress-service/80/da39a3ee5e::high_priority::max_pending_requests::1024
default/wordpress-service/80/da39a3ee5e::high_priority::max_requests::1024
default/wordpress-service/80/da39a3ee5e::high_priority::max_retries::3
default/wordpress-service/80/da39a3ee5e::added_via_api::true
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::cx_active::0
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::cx_connect_fail::27
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::cx_total::4723
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_active::0
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_error::421
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_success::7673
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_timeout::312
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_total::8603
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::health_flags::healthy
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::weight::1
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::region::
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::zone::
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::sub_zone::
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::canary::false
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::success_rate::-1

Thanks.

**Comment by davecheney** [comment]
It looks like your pod at ip 10.48.1.7:80 is unwell.

**Comment by davecheney** [comment]
It is possible that contour is not waiting long enough for the response from your wordpress service.

**Comment by sgonzalezO** [comment]
> It looks like your pod at ip 10.48.1.7:80 is unwell.

Because of "cx_connect_fail::27"?

> It is possible that contour is not waiting long enough for the response from your wordpress service.

This is our IngressRoute definition:

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: www-opencanarias-com
  namespace: default
  annotations:
    contour.heptio.com/request-timeout: "1m"    # 1 minute timeout
    contour.heptio.com/retry-on: "5xx"
    contour.heptio.com/num-retries: 3
spec:
  virtualhost:
    fqdn: www.opencanarias.com
    tls:
      secretName: opencanarias-ssl-certs
  routes:
    - match: /
      services:
        - name: wordpress-service
          port: 80
```

**Comment by davecheney** [comment]
Yes, and 
```
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_error::421
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_success::7673
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_timeout::312
default/wordpress-service/80/da39a3ee5e::10.48.1.7:80::rq_total::8603
```

**Comment by sgonzalezO** [comment]
So this is not a Contour bug. I'm going to close the Issue.

Thanks for your help.
