### ISSUE TITLE
Unable to create Ingress Route without a secret name through the Go API

### ISSUE THREAD

**Issue by 256dpi** [heptio/contour#917]
I'm creating ingress routes programmatically using the Go client. While this generally works without issues, I ran into one scenario where it fails. When I try to create a ingress route with TLS passthrough and therefore omit the `spec.virtualhost.tls.secretName` I get the following error: 

```
spec.virtualhost.tls.secretName in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
```

Is it possible that there is a validation function that expects `secretName` to always be present?

**Environment:**

- Contour version: 0.9.0
- Kubernetes version: 1.11 (kubectl: 1.13)
- Cloud provider or hardware configuration: GKE

**Comment by davecheney** [comment]
I'm sorry about this. The ingress validations are a nightmare, we have no tests for them and frankly I'd like to delete them.

**Comment by 256dpi** [comment]
If you can point me to the related files, I'm happy to take a look. :-)

**Comment by davecheney** [comment]
deployment/common/contour.yaml (or thereabouts )

**Comment by 256dpi** [comment]
I'm fairly new to Kubernetes, so I might have missed some stuff. But my guess is that the validation schema is actually correct, since there are other properties that have a regex validation but are still allowed to be absent. So far as I understand OAI you explicitly require validation by setting the `required` key.

Now, my hunch is that we should flag the `SecretName` struct field in the API definition with `json:"secretName,omitempty"`. If the key is absent it would not be checked by the OAI validator that Kubernetes uses. I will try test this in the next few days. @davecheney Would this potentially break other stuff?
