### ISSUE TITLE
use shared informer factories for watchers

### ISSUE THREAD

**Issue by andrewsykim** [heptio/contour#930]
**Describe the solution you'd like**
Use informer factories for running Kubernetes informers/watchers (see https://github.com/heptio/contour/pull/929 for an example reference). 

The motivation behind this is mostly aesthetic. The informer factory abstracts a lot of the plumbing required to start and stop listers/watchers in Kubernetes. It also provides a few convenient methods like `WaitForCacheSync` which blocks until all active informers had a chance to sync its cache. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by davecheney** [comment]
Fixed in #929
