### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by andrewsykim** [heptio/contour#931]
**Describe the solution you'd like**
I really like the [Contribution Workflow](https://github.com/heptio/contour/blob/master/CONTRIBUTING.md#contribution-workflow) for this project. I think it would be super helpful if we reference the expected workflow in a PR template to inform new contributors in case they missed it from the README. I'm happy to put the PR template together! 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by davecheney** [comment]
SGTM.
