### ISSUE TITLE
X-FORWARDED-FOR on GKE

### ISSUE THREAD

**Issue by remmeier** [heptio/contour#945]
I deployed Contour on GKE through the official Helm chart (resp. its current PR). I would have expected a x-forwarded-for to be present representing the client API. But I rather get single IP addresses from nodes in the kubernetes cluster like:

```
x-forwarded-for=10.164.0.58
x-forwarded-for=10.164.15.192
x-forwarded-for=10.164.15.192
```

the incoming real IP address in the service is the podIP of the countour pod (as expected). The setup is rather simple, contour runs as LoadBalancer service and gets an external IP address reserved within Google Cloud. No further external firewalls or load balancers are in place.

I would have expected to somehow feed a base configuration of envoy into countour, but that does not seem to be possible (https://github.com/heptio/contour/issues/939).

The solution likely lies in one of the flags here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#x-forwarded-for. I suspect it would also be possible to set `externalTrafficPolicy: Local`, but that does not seem like the way to go due to the loss of load balancing features and setting that `x-forwarded-for` would already be sufficient.

**Comment by davecheney** [comment]
What is likely happening is because the GKE load balancer is in tcp mode and does not support the PROXY protocol the remote IP address is lost. 

I deploy on gke as well and haven’t yet found a way to enable PROXY support which will recover the remote ip

**Comment by remmeier** [comment]
aha, thx for that clarification. So I added `externalTrafficPolicy: Local` after all to the contour service which then makes it work.
