### ISSUE TITLE
Pin version of Contour in quickstart

### ISSUE THREAD

**Issue by randomvariable** [heptio/contour#952]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The https://j.hept.io/contour-deployment-rbac set of manifests on the front page reference gcr.io/heptio-images/contour:master, which can cause issues with CRD or role changes in subsequent releases that cause the pod to go into `CrashLoopBackoff` when it is replaced.

The quickstart should reference the latest release of Contour that matches the rest of the objects defined in the manifest.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v0.10.0
- Kubernetes version: (use `kubectl version`): 1.13.4
- Kubernetes installer & version: kubeadm 1.13.4
- Cloud provider or hardware configuration: bare metal, kube-router
- OS (e.g. from `/etc/os-release`): Fedora 29 x86-64

**Comment by davecheney** [comment]
I agree we should do this. There are some administrative problems with updating the shortlink on each release which need to be addressed internally.

**Comment by davecheney** [comment]
I'm trying to make this work, #1465, but I can't figure out the right netlify fu
