### ISSUE TITLE
Keep TCP connection alive/serving on pod restarts in Kubernetes

### ISSUE THREAD

**Issue by rbkumar88** [heptio/contour#962]
Hi,

We are using envoy as edge proxy for our tcp traffic and we have the connections to a upstream service(e.,g a TCP server service) in kubernetes. we don’t want to loose the client TCP connection in case of pod restarts..can Contour sit in k8s as a ingress controller. and perform the smooth load balancing in between my envoy edge proxy and the pods (TCP serveR).

in the sense the client connections are long-lived and typically don't want them to be lost in case of upstream pod restarts and still want the TCP connections to continue and serve the client.

Thanks

**Comment by davecheney** [comment]
I am sorry but this is not possible when using TCP mode. If Envoy is forwarding a tcp stream to the backend there is no way for it to redirect it to another backend mid stream.
