### ISSUE TITLE
Configure a Global TLS min protocol version for the entire cluster

### ISSUE THREAD

**Issue by sudeeptoroy** [heptio/contour#980]
**Describe the solution you'd like**
Introduce a new global min TLS version configuration which can be set during the contour installation. With this global min TLS configuration "spec.virtualhost.tls.minimumProtocolVersion" would only take effect when the value is higher than the one mentioned during deployment. 

**Anything else you would like to add:**
We are aware of the setting "spec.virtualhost.tls.minimumProtocolVersion" which users need to embed in their IngressRoute definition. Present default is TLS 1.1 and it may not be the standard in many firms. Thus we have to mutate and validate each IngressRoute resource for exception. 

**Environment:**

- Contour version: all
- Kubernetes version: (use `kubectl version`): all
- Kubernetes installer & version: all
- Cloud provider or hardware configuration: all
- OS (e.g. from `/etc/os-release`): all

Blocked on:
- [ ] #1130

**Comment by stevesloka** [comment]
@sudeeptoroy are you suggesting a flag on Contour to set this? Currently, the root ingressroute has the setting which rolls down to each route in the fqdn.

**Comment by sudeeptoroy** [comment]
yes I am suggesting deployment specific or a new global resource definition which cannot be overwritten by users of the platform.

**Comment by davecheney** [comment]
Currently we configure envoy to use tls 1.1 or later. 

Are you asking for a flag to enforce tls 1.2 or later? Why shouldn’t we just make 1.2 the minimum? Can you please outline your requirements for prohibiting tls 1.1? They may form the basis of a policy to remove tls 1.1 support for contour.

**Comment by sudeeptoroy** [comment]
TLS 1.1 protocol has dependency on the MD5 and SHA-1 digest algorithms and for various other reasons it’s not the approved protocol in many firms. Also to use TLS 1.1 or TLS 1.2 depends on organization's activities.

wrt to this issue:
1. yes updating the default to TLS 1.2 would definitely resolve the issue for us now.
2. Contour has TLS version defined as min and max to cater to large audience and as a user of this feature we should be able to define the min accepted version according to the firm.

>Are you asking for a flag to enforce tls 1.2 or later?
yes

**Comment by davecheney** [comment]
My points is, we already clamp the lower bound to tls 1.1, what are
the justifications for making this bound 1.2? Alternatively, if it
were possible to prohibit MD5 or SHA-1 digests with TLS/1.1 would that
suffice?

**Comment by sudeeptoroy** [comment]
TLS 1.2 is governed by a separate security group and it comes as a mandate for us to follow.

**Comment by moderation** [comment]
A colleague of @sudeeptoroy here. There is a mandate within our heavily regulated firm (and industry) and that TLS 1.1 cannot be used. [Chrome](https://security.googleblog.com/2018/10/modernizing-transport-security.html), [IE](https://blogs.windows.com/msedgedev/2018/10/15/modernizing-tls-edge-ie11/), [Firefox](https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/) and [Safari](https://webkit.org/blog/8462/deprecation-of-legacy-tls-1-0-and-1-1-versions/) have all announced the deprecation of TLS 1.0 and 1.1. There is a fairly long deprecation cycle. Despite our requirement to set a floor version of TLS to 1.2 my guess is that there will likely be users of Contour that still require TLS 1.1 for legacy apps etc.

We'd be thrilled if you set TLS 1.2 as the floor version but I suspect having a way to set a minimum globally will help us but also allow those with different requirements to operate.

**Comment by davecheney** [comment]
This is blocked on #1130. Tentatively scheduled for 0.15

**Comment by davecheney** [comment]
Closed by #1273
